### ISSUE TITLE
Cannot delete users as long as they are assigned as submitters or candidates

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1004]
When I do so, I get this error:
```
Error: Uncaught (in promise): Error: Error: Update of assignment_candidate/4: You try to set following required fields to an empty value: ['user_id']
Error: Error: Update of assignment_candidate/4: You try to set following required fields to an empty value: ['user_id']
```

**Comment by reiterl** [comment]
The user.delete action is a simple delete action. In my opinion the problem is that while deleting the user the relation code tries to reset the user_id of assignment_candidate or submitter. But the user_id is required, so it fails. 
But I don't have an idea, how to fix this.

**Comment by jsangmeister** [comment]
Only possibility with the current setup is to cascade the deletion so that the assignment candidates and submitters are deleted as well. I think this is okay, because a user should typically not be deleted, but instead be set to inactive (for exactly these kinds of cases)

**Comment by jsangmeister** [comment]
Thought I had time for this, but nevermind. This should just have to be adjusted in the models.yml - maybe we should wait for #1009 with this.
