### ISSUE TITLE
Move model/database related files to the backend

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1008]
All database related files should be moved to the backend-submodule. With this change the dependencies between the subrepositories are easier to manage. One goal is, that the backend with all it's databse-related files is always in a consistent state including the migrations.

Affected files are:
- models.yml
- models.py (generated from models.py)
- initial-data.json
- example-data.json
- permission.yml
- permission.py (generated)

We have to look for all the checking and generating and have to guarantee the consistency. 
It seems that the autoupdate-service is the only direct dependant of this.
Feel free to complement this description, if you are missing things.

**Comment by reiterl** [comment]
I thought there is code, which checks the model.yml. This should be moved to the backend, too. In my opinion.

**Comment by r-peschke** [comment]
> I thought there is code, which checks the model.yml. This should be moved to the backend, too. In my opinion.

Yes, all the checks and tests have to run in the backend
