### ISSUE TITLE
Some more defaults for a meeting

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1012]
After #1009 is merged, enhance some default values for a meeting:

- `assignment_poll_default_type` should be `analog`
- `assignment_poll_default_method` should be `Y`
- `assignment_poll_default_group_ids` and `motion_poll_default_group_ids` should have only the id for the group with the name `delegates` within a meeting

The last point means, when a meeting is created, some default groups are created, too. One of these groups has the name `delegates`. This group's id should be the value for the both keys.

**Comment by jsangmeister** [comment]
Note: The last point cannot be expressed in the `models.yml`, it has to be manually implemented in `meeting.create`.
