### ISSUE TITLE
Cannot set PDF logos

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#1014]
I  _think_ that this one worked before, but I could be mistaken.

I need to set the PDF logos. Following request was send:

```json
{
    "action": "meeting.set_logo",
    "data": [
        {
            "id": 1,
            "mediafile_id": 3,
            "place": "pdf_header_L"
        }
    ]
}
```

it seems that the "place" attribute was somewhat generic? However, the backend sends the following answer.

```json
{
    "success": false,
    "message": "Datastore service sends HTTP 400. {'msg': \"The key 'used_as_logo_$pdf_header_L_in_meeting_id' is no fqid, fqfield or collectionkey\", 'type': 1, 'type_verbose': 'INVALID_FORMAT'}"
}
```

perhaps the format just changed? Cannot find it out.

**Comment by jsangmeister** [comment]
only lowercase letters are allowed in field names - the error message is a bit misleading here, since the error occurs in the datastore when validating the write request. I would suggest to change the replacement to `pdf_header_l` or even `pdf_header_large`.

**Comment by tsiegleauq** [comment]
yep works that way
