### ISSUE TITLE
Implement chat- and chat-group-related actions

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1024]
## Chat group actions

- [x] [chat_group.create](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.create)
- [x] [chat_group.update](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.update)
- [x] [chat_group.delete](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.delete)
- [x] [chat_group.sort](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.sort)

## Chat message actions

- [x] [chat_message.create](https://github.com/OpenSlides/OpenSlides/wiki/chat_message.create)
- [x] [chat_message.update](https://github.com/OpenSlides/OpenSlides/wiki/chat_message.update)
- [x] [chat_message.delete](https://github.com/OpenSlides/OpenSlides/wiki/chat_message.delete)

These actions require to implement new collections `chat_message` and `chat_group`.

**Comment by reiterl** [comment]
What fields have the `chat_message` and `chat_group` collections?

**Comment by GabrielInTheWorld** [comment]
`chat_group`
```js
{
  id: Id
  name: String
  weight: Number

  read_group_ids: Id[]
  write_group_ids: Id[]
  meeting_id: Id
}
```

`chat_message`
```js
{
  id: Id
  content: HTMLStrict
  created: Timestamp

  user_id: Id
  chat_group_id: Id
  meeting_id: Id
}
```

**Comment by reiterl** [comment]
Which fields are required? How are they linked? Do we need other fields in other collections?

**Comment by reiterl** [comment]
what restriction mode do the fields have?

**Comment by GabrielInTheWorld** [comment]
`chat_group`
```js
{
  restriction_mode: A
  
  // Required fields
  id: Id
  name: String
  meeting_id: Id
  chat_message_ids: Id[]

  // Optional fields
  /**
  * Only ids of groups which are in the same meeting
  */
  read_group_ids?: Id[]

  /**
  * Only ids of groups which are in the same meeting
  */
  write_group_ids?: Id[]

  /**
  * Starting at 0, every new chat_group has a weight one higher 
  * than the highest weight of a chat_group in the same meeting
  */
  weight?: Number 
}
```

`chat_message`
```js
{
  restriction_mode: A

  // Required fields
  id: Id
  content: HTMLStrict
  created: Timestamp
  user_id: Id
  chat_group_id: Id
  meeting_id: Id
}
```

Adjustments of already existing collections:

`meeting`
```js
{
  // [...]
  // New fields
  chat_group_ids: Id[] // <-- ids of chat_groups in this meeting
  chat_message_ids: Id[] // <-- ids of chat_messages in this meeting
}
```

`user`
```js
{
  // [...]
  // New fields
  chat_message_ids: Id[] // <-- ids of chat_messages sent by this user
}
```

**Comment by reiterl** [comment]
* chat_group already exists in the model. Why that?
* Why is chat message in chat group required?
* Restriction mode should be per field.

**Comment by reiterl** [comment]
* there exists a meeting/read_chat_group_ids and meeting/write_chat_group_ids. Why should this be changed?

**Comment by reiterl** [comment]
* Id and must fields are not required in the other models. Why should it be required in chat_message?

**Comment by reiterl** [comment]
* user/chat_message_ids mixes msgs from different meetings. Do we really want this?

**Comment by GabrielInTheWorld** [comment]
> * user/chat_message_ids mixes msgs from different meetings. Do we really want this?

Right. This must be a template-field.
```yml
user:
  chat_message_$_ids:
    type: template
    replacement_collection: meeting
    fields:
      type: relation-list
      to: chat_message/user_id
```

**Comment by GabrielInTheWorld** [comment]
> * Id and must fields are not required in the other models. Why should it be required in chat_message?

Which "must fields"? Okay, then, `Id` is not required. I thought it, since every model needs to have an `Id`.

**Comment by GabrielInTheWorld** [comment]
> * there exists a group/read_chat_group_ids and group/write_chat_group_ids. Why should this be changed?

Leave this as it is. I don't say to change these relations.

**Comment by reiterl** [comment]
* Which restriction_mode should `user/chat_message_$_ids` have?

**Comment by GabrielInTheWorld** [comment]
> * Which restriction_mode should `user/chat_message_$_ids` have?

Right. Restriction_mode `B`.
