### ISSUE TITLE
Implement the key `organization/enable_chat`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1032]
A superadmin can (de-) activate the chat globally for all meetings in an organization.
Therefore, implement the key `organization/enable_chat` in the `organization` collection. 

I made changes accordingly in the wiki:

- [OS4#Chat](https://github.com/OpenSlides/OpenSlides/wiki/Chat)
- [organization.update](https://github.com/OpenSlides/OpenSlides/wiki/organization.update)
- [chat_group.create](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.create)
- [chat_group.delete](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.delete)
- [chat_group.sort](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.sort)
- [chat_group.update](https://github.com/OpenSlides/OpenSlides/wiki/chat_group.update)

**Comment by jsangmeister** [comment]
The client will have to be adjusted to display `meeting/enable_chat` correctly: This should not be available (greyed out or something?) if `organization/enable_chat ` is false.
