### ISSUE TITLE
Default poll backend

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1037]
It is currently not possible to set the default vote-backend of a poll.

There are some configs to define the default type and groups, but not the backend: https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1069-L1080

The poll-backend decides, if the poll data is saved in redis or postgres.

Should we add a field `meeting/poll_default_type`?

**Comment by ostcar** [comment]
I talked with @emanuelschuetze about this. He thinks, that the only way to configure this in the UI should be in the meeting-settings. So it should not be possible to set this when creating a poll.

Therefore the field is required.

I realize know, that there are three fields: `motion_poll_default_backend`, `assignment_poll_default_backend` and `poll_default_backend`.

Could you add this three fields and make sure they are used when a poll is created?

**Comment by jsangmeister** [comment]
Summary:
- add the fields `motion_poll_default_backend`, `assignment_poll_default_backend` and `poll_default_backend` to the models and data files
- add the fields to `meeting.update` & test them
- add the field `backend` to `poll.{create|update}` & test them
  - changing the `backend` should only be available in the `CREATED` state

**Comment by ostcar** [comment]
There is another issue in this context. I was sure that the current default backend is the fast-backend (redis). But I am wrong. The current default is is long (postgres). This should also be changed. The normal case should be the fast backend.

https://github.com/OpenSlides/openslides-backend/blob/69ea974776320d2f01fa73b825f28a0b05243109/global/meta/models.yml#L2534
