### ISSUE TITLE
models.yml: Move restriction_mode of topic

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1038]
The models.yml has to be adjusted. All fields from `topic` have to be moved to restriction_mode A. restriction_mode B was removed.

https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1847-L1890

See https://github.com/OpenSlides/openslides-autoupdate-service/issues/359

**Comment by ostcar** [comment]
The same for topic:

https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2855-L2946

**Comment by ostcar** [comment]
> @ostcar Please set - as always - the correct labels to see to which repo an issue belongs.

Could you tell me which labels do you think I should set here? I though I set all relevant labels. This issue belongs to the backend-repo (that why I opened it in the backend repo)

**Comment by GabrielInTheWorld** [comment]
> > @ostcar Please set - as always - the correct labels to see to which repo an issue belongs.
> 
> Could you tell me which labels do you think I should set here? I though I set all relevant labels. This issue belongs to the backend-repo (that why I opened it in the backend repo)

At least the label for the respective repo (in this case `backend`) should be set.

**Comment by ostcar** [comment]
> > > @ostcar Please set - as always - the correct labels to see to which repo an issue belongs.
> > 
> > 
> > Could you tell me which labels do you think I should set here? I though I set all relevant labels. This issue belongs to the backend-repo (that why I opened it in the backend repo)
> 
> At least the label for the respective repo (in this case `backend`) should be set.

Thanks for the tip. I added it. But I still don't understand why a issue in the backend repo needs the backend label.

**Comment by GabrielInTheWorld** [comment]
> Thanks for the tip. I added it. But I still don't understand why a issue in the backend repo needs the backend label.

Under our ["kanban board"](https://github.com/orgs/OpenSlides/projects/1), we can then filter by this label. Therefore, it is for us helpful to distinguish between the several repos. ;-)

**Comment by jsangmeister** [comment]
BTW: I think when we first introduced the board, the feature did not exist yet, but now you can filter by e.g. `repo:OpenSlides/openslides-backend` and don't need the labels anymore.

**Comment by ostcar** [comment]
What is the conclusion? Should I add the repo label in the future or can you use the filter?

**Comment by jsangmeister** [comment]
> What is the conclusion? Should I add the repo label in the future or can you use the filter?

If @r-peschke gives his okay, we can delete the labels and you do not have to set them anymore. But there are still milestones: Milestone 4.0 is for everything which needs to be adressed before the initial 4.0 release, 4.1 for everything after. If you are not sure, you can leave it out, but if possible, add the correct milestone (e.g. this or the performance issues should 4.0, since without it a functional release is not really possible). Also maybe interesting for @normanjaeckel
