### ISSUE TITLE
Deactivate Travis to remove deprecated .travis.yml

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#105]

**Comment by jsangmeister** [comment]
Also make GH Actions required, like travis currently is.

**Comment by FinnStutzenstein** [comment]
Done.

**Comment by FinnStutzenstein** [comment]
The status for actions in the repo settings:

```
Enable local and third party Actions for this repository

This allows any Action to execute, whether the code for the Action exists within this repository, organization, or a repository owned by a third party.
```

**Comment by jsangmeister** [comment]
See #106. Travis is still running and required on a freshly created PR...

**Comment by jsangmeister** [comment]
In #95 travis is also still required but doesn't report a status. Can't merge anything currently, it seems like

**Comment by normanjaeckel** [comment]
Can someone please explain to me what the advantage of GitHub actions comparing to Travis is? I do not understand the effort we do on this here.

**Comment by jsangmeister** [comment]
In OS3, we had so much trouble with Travis that we decided to switch to github actions. So far, it seems to run better and more stabile with out any issues encountered. If you want, I think @tsiegleauq can tell you many travis horror stories ;)

**Comment by FinnStutzenstein** [comment]
Yes, travis is very unstable for the last half a year or so. Sometimes the pipeline doesn't trigger or the status doesn't get reported to github. Very annoying.
