### ISSUE TITLE
meeting_import don't treat meeting- and committee-membership correct

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1070]
Functionally it adds a user to a meeting, because he is the calling user. In contrast `meeting_ids` or opposite relation `user_ids`  is defined as a calculated field, that bases on group membership. IMO this is a bug with influence on the counting of active users.

The relations committee_ids and user_ids in committee are not handled anyway.

Technically both relations are defined as registered calculated fields with a special mechanism. This is not used on the implemented version of import meeting, because those are working with backend-actions. 

Are there more imports with this problem?

**Comment by jsangmeister** [comment]
Can you describe in more details, e.g. with an example, what the problem is? Or maybe we can talk about this tomorrow/next week. I'm not sure what the exact problem is.

**Comment by jsangmeister** [comment]
Ok, we talked about it and it seems to me the best solution is to just call the `CalculatedFieldHandlers` from the import code. There should be almost no special code necessary, just some restructuring in the `RelationManager` (see https://github.com/OpenSlides/openslides-backend/blob/a8a6754eb7e2556453be9cdd1e9649432a69c4f0/openslides_backend/action/relations/relation_manager.py#L34) where the calculated field handlers are called. This method can maybe just directly be called from the import, this has to be tested. Anyway, almost no logic should need to be implemented.
