### ISSUE TITLE
Add migration index to models.yml

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1073]
The models.yml should contain a property `_migration_index` with the current index. The validation tool should check this index according to the current migration status.

**Comment by reiterl** [comment]
Do you mean adding a hand-coded `_migration_index` to the models.yml? This would be possible, but it is another stone at the feet of the people, which develop the models. I am against it.
The validation tool (aka checker) is used in different areas of the code. We should not check the current index there.

**Comment by r-peschke** [comment]
I don't think we need this.
The migrations are written after changes in models.yml/py and, since they are in same repo, we never had a problem with their syncronicity. 
@normanjaeckel Why do you need this?

**Comment by normanjaeckel** [comment]
If you think we do not need this, it is ok for me.
But: At the moment the initial data are sent to the datastore without any migration index. Please fix this. The initial request should set the correct migration index.

**Comment by jsangmeister** [comment]
Do you mean adding the migration index to https://github.com/OpenSlides/OpenSlides/wiki/organization.initial_import? Yes, I agree that we should do that.

**Comment by normanjaeckel** [comment]
No. It is about the request from backend to the datastore. If we use the default initial data, the migration index is not sent to datastore. If I use custom initial data, I can provide the migration index inside the data. This should not be any problem.

**Comment by r-peschke** [comment]
@normanjaeckel With #1264 the Migration Index is mandatory in initial data and will be used to initialize the datastore's MI. On success you'll find a dictionary in response.json['result'][0][0]  with the data_migration_index, backend_migration_index and a message. This covers the case the data_migration_index is lower than the backend_migration_index. In this case the message is set to ""Data imported, but must be migrated!". See also https://github.com/OpenSlides/OpenSlides/wiki/organization.initial_import.
@emanuelschuetze , @jsangmeister FYI

**Comment by jsangmeister** [comment]
Just reviewed it, I would prefer a flag instead of a message string for convenience

**Comment by r-peschke** [comment]
> Just reviewed it, I would prefer a flag instead of a message string for convenience

Implemented a flag: migration_needed
