### ISSUE TITLE
Enable querying health status from outside the stack

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-backend#1075]
For a basic status monitoring of instances, it would be helpful to be able to query the `/internal/health` resource (or something similar) from outside the stack.  The goal is to find an *indicator* for whether an instance is running and ready.  It is not necessary to thoroughly check all services or aspects of the instance.  I imagine that a healthy backend service would be the best indicator.

From my understanding, it would be rather easy to make the route available.  However, `/internal/health` responds with a lot of data.  For the given purpose, that is not ideal.  Maybe we need an additional route that simply replies with a concise `OK` instead.  Alternatively, maybe the `/internal/health` response does not need to be so long and could be reduced?

In https://github.com/OpenSlides/OpenSlides/issues/6301 I suggest to use Docker's `HEALTHCHECK`s which is a very similar use case.  Ideally, the solution for this issue would be equally suitable for `HEALTHCHECK`.

**Comment by jsangmeister** [comment]
@normanjaeckel if you agree/don't need it anymore, I would just remove the output from the health route and make it public.
