### ISSUE TITLE
Repeated test failure on actions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#108]
The first few tests sometimes fail with the new docker compose setup for system tests. I ran the GH actions for #95 three times without code changes, the first 2 times the first 4 tests failed with `Connection reset by peer`. On the third try, it worked and I could merge the PR.

**Comment by jsangmeister** [comment]
Okay, seems like it's not necessarily the first tests that fail. Currently on #107:

    tests/system/action/test_general.py .......                              [ 11%]
    tests/system/action/agenda_item/test_create.py F                         [ 13%]
    tests/system/action/agenda_item/test_numbering.py F..                    [ 18%]
    [...]

The specific error:

    openslides_backend.shared.exceptions.DatabaseException: Cannot reach the datastore service on http://localhost:9010/internal/datastore/reader/filter. Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    
    openslides_backend/services/datastore/http_engine.py:51: DatabaseException

**Comment by FinnStutzenstein** [comment]
> `http://localhost:9010`

localhost seems to be wrong.

**Comment by FinnStutzenstein** [comment]
I tested on current master: In the dev setup the DS writer (didn't checked the reader) is spawned on port 8000. This is not right, too.

**Comment by normanjaeckel** [comment]
I do not know how I can help here.

**Comment by jsangmeister** [comment]
But why does this error only occur on some tests? The rest are running fine and if I'm running them locally, no error ever happened.

**Comment by FinnStutzenstein** [comment]
Fixed with #111
