### ISSUE TITLE
`projector.add_to_preview` throws an error

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1081]
I sent this payload: 
```js
[{"action":"projector.add_to_preview","data":[{"ids":[3],"content_object_id":"topic/9","meeting_id":2,"options":{}}]}]
```

and got this error:
```js
{"success": false, "message": "data must not contain {'meeting_id'} properties", "action_error_index": 0, "action_data_error_index": 0}
```

But the action `projector.add_to_preview` expects a [meeting_id](https://github.com/OpenSlides/OpenSlides/wiki/projection#project-something-projectorproject)...

**Comment by jsangmeister** [comment]
Seems like either the changes from https://github.com/OpenSlides/openslides-backend/pull/622 are missing in `projector.add_to_preview` or it is not needed there and the wiki entry is wrong. I cannot tell which one is right. Maybe @r-peschke can answer this?

**Comment by jsangmeister** [comment]
> We can adjust the wiki entry. I _think_, we can get a `meeting_id` from the related `content_object`.

Can users or other out-of-meeting objects be added to the preview? Probably yes, right? Then we need the meeting id and the code would have to be adjusted (plus a test for adding e.g. a user to the preview, so it is ensured this works).

**Comment by r-peschke** [comment]
> Seems like either the changes from #622 are missing in `projector.add_to_preview` or it is not needed there and the wiki entry is wrong. I cannot tell which one is right. Maybe @r-peschke can answer this?

The changes from #622 for `projector.project` are missed in `projector.add_to_preview` including the `meeting_id`. In #622 it is used to assert that the used objects belong to the given meeting.
