### ISSUE TITLE
Change all `meeting/logo_$_id`and `meeting/font_$_id` from template field to json field

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#1087]
Since the autoupdate does not inform us anymore, that logos and fonts where unset (https://github.com/OpenSlides/openslides-autoupdate-service/pull/337), the client has no meaningful way to guess if a previously set logo or font was ever unset. Thus we would require to change all these template fields to json fields, so we can receive this information again.

The fields in question are the following:

Logo Places:
```
`projector_main`,
`projector_header`,
`web_header`,
`pdf_header_l`,
`pdf_header_r`,
`pdf_footer_l`,
`pdf_footer_r`,
`pdf_ballot_paper`
```

Font Places:
```
`regular`,
`italic`,
`bold`,
`bold_italic`,
`monospace`,
`chyron_speaker_name`
```

related:
https://github.com/OpenSlides/openslides-client/issues/618
https://github.com/OpenSlides/openslides-client/issues/675

**Comment by jsangmeister** [comment]
In https://github.com/OpenSlides/openslides-client/issues/675 it is described that the client receives an update for the template fields (e.g. `logo_$_id`) if a replacement is deleted. Therefore, it should be possible to propagate this change to the structured fields (e.g. `logo_$web_header_id`), or not? Of course this would require special handling for template fields, but I'm assuming this is already present anyway.

If that's for some reason not possible, we could still restructure the field, but this would require a new migration and adjustments in all places in the tests where these fields were used.
