### ISSUE TITLE
Add `allow_submitter_delete` as attribute for `motion_state`

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#1091]
Add the attribute "allow_submitter_delete" to motion states so submitters can withdraw their own motions.
The implication is, like `allow_submitter_edit`, that submitters are allowed to delete their own motion. (Otherwise, only motion managers are allowed to delete a motion.) This must be checked in the `motion.delete` action.

**Comment by jsangmeister** [comment]
@emanuelschuetze why did you remove milestone and tag? Is this not needed anymore?

**Comment by jsangmeister** [comment]
Closing in favor of the new feature of withdrawing in a specific state for the submitter.
