### ISSUE TITLE
Provide the action `user.send_invitation_email` at an orga-layer

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1094]
Currently, users can only send invitation emails from within a meeting. We have to provide this function from an orga-layer.
To do so, add  these fields to the `models.yml`:
- organization/users_email_subject
- organization/users_email_body
- organization/url

and follow the instructions, which are not already fulfilled, in [the description](https://github.com/OpenSlides/OpenSlides/wiki/user.send_invitation_email).

**Comment by reiterl** [comment]
The user.send_invitation_email code uses:
  ```
          [
                "name",
                "users_email_sender",
                "users_email_replyto",
                "users_email_subject",
                "users_email_body",
                "users_pdf_url",
            ]
```
If no meeting_id is given, the code misses information.

**Comment by jsangmeister** [comment]
I suspect the fields "users_email_sender" and "users_email_replyto" also have to be added to the organization. The rest is described in the wiki what should be used.

**Comment by reiterl** [comment]
Can we rename `organization/url` in `organization/users_pdf_url` to be consistent with the names?

**Comment by jsangmeister** [comment]
I don't think the name is fitting since it is never actually used in any PDFs. We could talk about renaming `meeting/users_pdf_url` to `meeting/url`, though.

**Comment by reiterl** [comment]
Okay, it stays "url" in organization.
