### ISSUE TITLE
User restriction groups have changed

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1116]
The exta_data_permission was removed. Some fields have to be in other groups.

See https://github.com/OpenSlides/OpenSlides/wiki/user-restrictions/_compare/e646d973bff554800ca9cdee3c1720e5ad999878...9a6e8f788b4a45b015ffaa38ad5547fca28923ee

Could you change the models.yml and then ping me?

**Comment by ostcar** [comment]
Also remove the user.can_see_extra line from the permission file: https://github.com/OpenSlides/openslides-backend/blob/fc4c90d95c1b5a48680b6557e7881465169e7c1b/global/meta/permission.yml#L60

**Comment by jsangmeister** [comment]
done in https://github.com/OpenSlides/openslides-backend/pull/1118
