### ISSUE TITLE
Implement the new model `structure_level` and its actions

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1126]
- [ ] The new model `structure_level` has the following properties and relations:

```js
{
    restriction_mode: A

    id: Id
    name: String
    meeting_id: Id // the related meeting to a structure_level
    user_ids: Id[] // all assigned users to a structure_level
}
```
Changes to existing collections:

- [ ] `user`

```js
{
    // New field
    restriction_mode: A
    structure_level_$_ids: Id[] // <-- ids of assigned structure_levels  
}
```

- [ ] `meeting`

```js
{
    // New field
    restriction_mode: B
    structure_level_ids: Id[] // <-- ids of all structure_levels within a meeting  
}
```

New actions:

- [ ] [structure_level.create](https://github.com/OpenSlides/OpenSlides/wiki/structure_level.create)
- [ ] [structure_level.create](https://github.com/OpenSlides/OpenSlides/wiki/structure_level.delete)
- [ ] [structure_level.create](https://github.com/OpenSlides/OpenSlides/wiki/structure_level.update)

- [ ] Update the implementation of the action [user.update](https://github.com/OpenSlides/OpenSlides/wiki/user.update)

**Comment by jsangmeister** [comment]
Note regarding the `good first issue` label: Probably the hardest and extensive issue of this list, but should structurally still be doable.

**Comment by r-peschke** [comment]
Is this a replacement for the existing structure_level_$-field? The we should do a migration, too.

**Comment by luisa-beerboom** [comment]
Needs to be rewritten for template-field-removal:

structure_level should be connected to user, meeting_user, organization and maybe meeting.
We should discuss whether to use separate models for organizations and meetings, or whether to share the structure levels between orga and meetings.
