### ISSUE TITLE
Handle errors from vote-service

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1132]
When the backend create, stops or clears a poll, the vote-service could return an error. If this happens, this error has to be handled.

For example, if the backend sends a "create" request to the vote-service, but it fails, then the poll is started in the backend but not started in the vote service.

You can test this with the vote service before this [pr](https://github.com/OpenSlides/openslides-vote-service/pull/88). When you create a poll with many users (for example 2000), the vote-service needs more then 30 seconds for the create request.So the backend gets a timeout from the vote-service but does not stop the poll in the datastore. For the user, it looks like the poll has started, but he can not send any vote-requests. This issue should be fixed but you can use the old version to test the behavior of the backend, when the vote-service returns with an error.

**Comment by reiterl** [comment]
Is this issue current?

**Comment by jsangmeister** [comment]
Yes. You'll have to find a way to provoke an error in the vote service (maybe by sending an invalid payload in a patched method in a test) and implement correct handling for this. Currently it seems like the issue is just ignored, so the poll is started in the backend but not in the vote service.

**Comment by reiterl** [comment]
I send a wrong payload to the vote service (mod of get_endpoint "id" to "ids") in poll.start. The action aborts with "{'success': False, 'message': 'Vote service sends HTTP 400 with the following content: b\'{"error":"invalid","message":"no id argument provided"}\\n\'.'}" and 400. So what is the problem?

**Comment by ostcar** [comment]
The first problem is, that the error message is an internal error message that should not be sent to the client.

The next problem is the state in the datastore. You have to make sure, that if the autoupdate service does not start the poll, you have to reset the state in the datastore.

**Comment by jsangmeister** [comment]
> The next problem is the state in the datastore. You have to make sure, that if the autoupdate service does not start the poll, you have to reset the state in the datastore.

This is not a problem because if the action aborts, no write requests are sent to the datastore. The initial problem described here was that the vote service threw an error which the backend seemingly didn't catch. So you'll have to find what error that was to handle it correctly. @ostcar linked a PR above; if you set the vote service to the commit before that PR in the docker-compose file, you can create a poll with a huge amount of users and try to start it. I created a similar test recently which you can use as an orientation: https://github.com/jsangmeister/openslides-backend/blob/5235ffb9eb2d5659640a7b32186999a1d3c99337/tests/system/action/poll/test_stop.py#L195

**Comment by reiterl** [comment]
I tested some more. One of my tests shows following situation:
1. The start action aborts with 400 and sends the vote service error message.
2. But the poll is created in the datastore.
This is problematic, because vote service and datastore are out of sync.

**Comment by ostcar** [comment]
To help you test this, I created this PR on the current main-branch: https://github.com/OpenSlides/openslides-vote-service/pull/105

With it, you can define the returned state and error message of any request send to the vote-service.

You can set the Get-Attributes "error" and "status". For example:

```
curl -X POST "localhost:9013/internal/vote/create?id=1&status=302&error=foobar"
```
This will return a request with an http status code 302 and will output "foobar".

This are all the possible error codes, that the vote-service will send: https://github.com/OpenSlides/openslides-vote-service/blob/81eb81ad84e65b77eb94781d6919fa6255a26820/internal/vote/error.go#L38-L61

**Comment by ostcar** [comment]
Currently, the vote-service checks, that the field `poll/state` is set to `started`: https://github.com/OpenSlides/openslides-vote-service/blob/81eb81ad84e65b77eb94781d6919fa6255a26820/internal/vote/vote.go#L66

So currently, it is not possible to start a poll in the vote-service before the state is changed in the datastore.

I think, I can remove that check. When the backend starts a poll, it is not necessary for the vote-service to check the poll/state again. If you agree on that, then you could first start the poll in the vote-service and afterwards change the state in the datastore.

When the datastore-write requests fails, then you SHOULD call "clear" in the vote-service. But this is not necessary. If you don't do it, it is still possible to start the vote again in a later request. You can send the same request the to vote-service multiple times and will get the same response.

**Comment by jsangmeister** [comment]
> Currently, the vote-service checks, that the field `poll/state` is set to `started`: https://github.com/OpenSlides/openslides-vote-service/blob/81eb81ad84e65b77eb94781d6919fa6255a26820/internal/vote/vote.go#L66
> 
> So currently, it is not possible to start a poll in the vote-service before the state is changed in the datastore.
> 
> I think, I can remove that check. When the backend starts a poll, it is not necessary for the vote-service to check the poll/state again. If you agree on that, then you could first start the poll in the vote-service and afterwards change the state in the datastore.
> 
> When the datastore-write requests fails, then you SHOULD call "clear" in the vote-service. But this is not necessary. If you don't do it, it is still possible to start the vote again in a later request. You can send the same request the to vote-service multiple times and will get the same response.

I think this sounds good. @reiterl you would have to remove the `get_on_success` method in `poll.start` and move it to the beginning of the action. Also, in `poll.stop`, errors from the poll service should be caught when clearing the poll.

**Comment by reiterl** [comment]
Is the vote service updated, so that I can do the `poll.start` change?
@jsangmeister  can you more verbose describe, what I need to change in `poll.stop`?

**Comment by ostcar** [comment]
I changed the behavior with this PR: https://github.com/OpenSlides/openslides-vote-service/pull/113

This PR also changed something, I wonted to do for a long time. I changed the url to "start" a poll from `/create` to `/start`.

For this to work, you have to change the backend here: https://github.com/OpenSlides/openslides-backend/blob/fb283a8eaae42f3683ec3df3d6cc6ec6c4febc13/openslides_backend/services/vote/adapter.py#L60

Both changed (my PR in the vote service and the backend-change) have to be merged at the same time.

**Comment by jsangmeister** [comment]
> @jsangmeister can you more verbose describe, what I need to change in `poll.stop`?

In the `on_success` method of `poll.stop`, `clear` is called on the stopped poll(s). If an error happens there, it seems not to be caught anywhere which means the request returns an error although the poll was stopped. This should be changed so errors from the vote service are caught there and logged to indicate that the clearing failed, but the response should still be a successful one since the actual `stop` was successful.

**Comment by ostcar** [comment]
Another hint. All requests to the vote service can be send multiple times. So if `poll.start`, `poll.stop`, `poll.clear` fails, you can try it again. This is especially relevant on network errors.
