### ISSUE TITLE
Implement the flag `is_hidden` to the collection `mediafile`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1133]
We need the flag `is_hidden` for mediafiles.

**Comment by reiterl** [comment]
Why do we need this flag? As far as I understand, this should be handled by the permissions.

**Comment by jsangmeister** [comment]
As discussed, the base use case (usage of mediafiles on the projector which should not be visible in the files section) is already doable by using permissions. The use case of specifically hiding files from specific users is more complex and should be tackled with a more complete apporach, if it is really needed.

**Comment by GabrielInTheWorld** [comment]
> As discussed, the base use case (usage of mediafiles on the projector which should not be visible in the files section) is already doable by using permissions. The use case of specifically hiding files from specific users is more complex and should be tackled with a more complete apporach, if it is really needed.

Therefore, I will close this until we really need such a feature.
