### ISSUE TITLE
Presenter get_user_scope

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1135]
Returns a dict for all given user_ids with the user scope and id, details see [presenter get_user_scope](https://github.com/OpenSlides/OpenSlides/wiki/get_user_scope)

**Comment by jsangmeister** [comment]
I think this should be restricted to user-managers (either in the meeting, committee or organization), shouldn't it?

**Comment by r-peschke** [comment]
This way it should have some benefit, otherwise we don't need it al all, see action [delete_or_remove_from_meeting](https://github.com/OpenSlides/openslides-backend/issues/1134)

**Comment by reiterl** [comment]
In the result dict is an entry "id". What is this entry for? I can calculate the user scope. But not a strange "id" stuff.

**Comment by reiterl** [comment]
Is there a way to get the user scope?

**Comment by r-peschke** [comment]
> In the result dict is an entry "id". What is this entry for? I can calculate the user scope. But not a strange "id" stuff. I found a get_user_scope method with collection and id as return values. I use this.

This is the right way:-) The id is the id of scope's object, maybe of the one meeting, one committee or the 1 for the one and only organization;-)
