### ISSUE TITLE
meeting clone failed if meeting has a mediafile

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1145]
- create new meeting
- create new mediafile (e.g. empty folder)
- clone meeting => error `{"success": false, "message": "\tmediafile/942: ", "action_error_index": 0, "action_data_error_index": 0}`
- remove mediafile in meeting
- clone again => works successfully

**Comment by reiterl** [comment]
The problem seems to be the validation of `attachment_ids`. It is a `GenericRelationListField`.
The clone checker validates it and checks if it is a list. But in a new created empty directory it is None.

I write a fast patch in clone for this. But need to talk to @jsangmeister about it.
