### ISSUE TITLE
Add `user/pronoun`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1156]
Update the user collection so that a pronoun can be specified for a user (as just a string field, restriction mode A) and update the [user.create](https://github.com/OpenSlides/OpenSlides/wiki/user.create), [user.update](https://github.com/OpenSlides/OpenSlides/wiki/user.update) and [user.update_self](https://github.com/OpenSlides/OpenSlides/wiki/user.update_self) actions accordingly.

**Comment by jsangmeister** [comment]
Isn't this overkill? The `gender` collection only has one sensible field, `name`. Why not just use a string in the user model as we do it currently? The check for this string can be adjusted more easily and just as flexible.

**Comment by jsangmeister** [comment]
Updated title and description as discussed
