### ISSUE TITLE
Presenter get_meetings

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1157]
Details siehe Presenter [get_meetings](https://github.com/OpenSlides/OpenSlides/wiki/get_meetings)

**Comment by jsangmeister** [comment]
Shouldn't the OML be `can_manage_organization`? This has nothing to do with users.

**Comment by reiterl** [comment]
As far as I know, this is no longer needed, as we add an archived_meeting_ids to organization. So I close here.
