### ISSUE TITLE
Add route for listing available actions

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-backend#1159]
The `health` route used to return a json-object describing available actions.
As discussed the functionality for this behavior is still present, but no longer available on the health route. So it should be served on a new one.

What about `localhost:9002/system/action/help`?
Though feel free to change up the name, if you got something more fitting.

Also this should be put into the readme once implemented as it is a very good (and complete) source of documentation.

**Comment by jsangmeister** [comment]
It should be noted that "good" documentation is relative here: everything the method outputs is the json schema of all actions, without any additional help texts or even description of parameters. For details to that one still has to consult the wiki.

Unassigning me in case somebody else has time to do this.

**Comment by reiterl** [comment]
I don't understand the description of this issue. What should be done here?

**Comment by jsangmeister** [comment]
The `health` route was changed here: https://github.com/OpenSlides/openslides-backend/commit/811cde32605ab62799b0c37f557a8540dd6ed03c

Previously, it output it huge batch of data containing all schemas of all actions, which were gathered using the method `ActionHandler.get_health_info`, which still exists: https://github.com/OpenSlides/openslides-backend/blob/551a3fc4767a1981d014c1ed5523774cbb9a81fd/openslides_backend/action/action_handler.py#L77

The goal is to implement a new route in `openslides_backend/http/views/action_view.py` with a name like `info` (see above) which outputs exactly the information returned by the aforementioned method.
