### ISSUE TITLE
Performance on motion.delete with a "big" database

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1172]
Experienced by Frank and @emanuelschuetze : Real use case: A 150MB meeting.json was imported and 7 times cloned. Deleting motions afterwards lasts each time longer, up to a minute for 3-4 motions.

**Comment by reiterl** [comment]
I got the export.json from @r-peschke . I try to import it, but after 30 sec I got a worker timeout.
backend_1           | [2022-04-27 11:25:05 +0000] [26] [CRITICAL] WORKER TIMEOUT (pid:210)
And the Client had a dialog popped up: The server didn't respond.

**Comment by reiterl** [comment]
I found a env `OPENSLIDES_BACKEND_WORKER_TIMEOUT` and will set it to a larger value.

**Comment by reiterl** [comment]
I had a problem with `topic/option_ids`. After I removed these fields, I could import the meeting.

I cloned the meeting seven times and deleted 3-4 motions from them.
3 motion deletion in the "Copy -Copy-Copy-Copy" meeting was 5 secs.
cloning one meeting is 2 mins. So no problems. I see, that a meeting has 3000 votes.

**Comment by reiterl** [comment]
Cloned some more times. Switch into the latest cloned meeting. Remove three motions. 5 sec.

**I cannot reproduce the problem.** I think with our performance improvements, we fixed this issue.

**Comment by r-peschke** [comment]
> I had a problem with `topic/option_ids`. After I removed these fields, I could import the meeting.
> 

@jsangmeister There is no topic/option_ids in models.py. In OS3-export there is this field. Don't you know, what it is for?

**Comment by jsangmeister** [comment]
The idea was probably to be used analogously to `motion/option_ids`: Every motion poll has exactly one option with the poll as its content object. For topic polls, this should be analogous, I think: one option with the topic as the content object. We should probably talk with @luisa-beerboom how the view is currently implemented and change it, if needed.

**Comment by jsangmeister** [comment]
Just talked with @luisa-beerboom and topic polls always have options with text instead of content objects, so the relation is not needed. Will remove it from the OS3 export.
