### ISSUE TITLE
Provide the `sequential_number` of a displayable model when creating it 

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1176]
Can the CREATE action of a displayable collection (mentioned in #1130) return the id of the new model as well as its `sequential_number`?

This would save some network requests.

**Comment by jsangmeister** [comment]
Yes, this should be easy to do. `create_action_result_element` can be overridden in the `sequential_number_mixin.py` to add the sequential number to the result.

**Comment by GabrielInTheWorld** [comment]
Maybe it won't be necessary to provide a sequential_number after creating a model.

**Comment by GabrielInTheWorld** [comment]
> Maybe it won't be necessary to provide a sequential_number after creating a model. Therefore, wait until I have finished [OpenSlides/openslides-client#733](https://github.com/OpenSlides/openslides-client/issues/733).

Yes, it is relevant, but not urgent.
