### ISSUE TITLE
Implement a `weight` field for groups

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1189]
Implement a `weight` field for groups, so the client knows how meeting-groups are ordered. This is especially useful for cloned meetings, because after cloning one, it is not obviously in which order they were once.
This means, the first created group has the `weight` of - for example - 0, the next one a `weight` of 1, etc. Then, in a cloned meeting groups should have the same weight as in the original one.

**Comment by jsangmeister** [comment]
TODOs:
- adding the field to models definition
- migration which copies the id into the weight field (suffices for the ordering)
- add the weight handling analogous to e.g. `motion_submitter` in the `create` action
- @GabrielInTheWorld is a `sort` action needed?

**Comment by GabrielInTheWorld** [comment]
> * @GabrielInTheWorld is a `sort` action needed?

Not yet.
