### ISSUE TITLE
Restricter Service

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#12]
The backend needs a restricter service. It is needed to get the data for the autoupdate service.

Therefore the backend needs an url `/restrict` that takes a list of keys and a user id. The handler should return a dict of key-values pairs where the key is one of the requested key and the value is the value the user is allowed to see. Keys, that the user is not allowed to see, should not be in the returned dict.

Related fields are fields with the suffix _id or _ids, that point to another collection. They should only contain the numbers, the user is allowed to see. If the user is not allowed to see any of the id, the field should not be returned at all.

A related field with a single relation (suffix _id) has be a single number. For example "5" oder "4563". Only digits are allowed.

A related field with a multiple relation (suffix _ids) has to start with a `[` and end with `]`. In between should be numbers separated with `,`. For example `[5,4563]`. Whitespaces are not allowed: `[5, 4563]`. To generate a valid value with python, use: `json.dumps([1, 4563], separators=(",", ":"))`.

It is ok, when the restricter does not return an related field when the user has the permission to see some of the related collections. For example if the user does not have the permission `can_see_all_users` the restricter does not have to return the field `organisation/1/user_ids` even if the user is allowed to see some users.

There will be a lot of requests from the autoupdate-service to the restricter. So the restricter should be as fast as possible. If this is a performance problem, it would be a good idea to use a different protocol as http1.1. For example http2.0 would use an open tcp connection between the autoupdate-service and the restricter, this could reduce with a lot of overhead. (grpc uses http2, I don't know if wsgi can be used on top of http2.)

Please tell me, when you have a first implementation to test the service.

**Comment by normanjaeckel** [comment]
Please have a look at #19. We may decide which format in detail you want to send to me.

**Comment by normanjaeckel** [comment]
@ostcar Changed format a little bit. Now you can try (but don't be disappointed because it almost does nothing ... ;-) )

**Comment by ostcar** [comment]
I implemented the adapter: https://github.com/OpenSlides/openslides-autoupdate-service/pull/17

And I added some comments in #19. Maybe we should discuss them here instead.

To run the autoupdate service together with the backend use:

```
docker build github.com/openslides/openslides-autoupdate-service --tag autoupdate
docker run -e RESTRICTER_SERVICE=backend --network=host autoupdate
```

Afterwards you can connect to the autoupdate service and retrieve the restricted "values" from the backend:
```
curl localhost:8002/autoupdate/ -d '[{"ids": [5], "collection": "user", "fields": {"name": null}}]'
```

**Comment by normanjaeckel** [comment]
Resctriction service is gone from the repository. @ostcar Please add a link here where the restrictions service now lives. Than you may close this issue.

**Comment by ostcar** [comment]
Here is the new restricter. Currently, it does nothing: https://github.com/OpenSlides/openslides-autoupdate-service/tree/master/internal/restrict
