### ISSUE TITLE
wrong list of entitled users

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1220]
For a poll the calculated list of entitled users is wrong.

Currently there are listed all _present_ users of meeting. That's not correct.
Expected: all users of defined voting group independent of present state (e.g. all delegates).

Probably [this for loop in poll/mixins.py#L165](https://github.com/OpenSlides/openslides-backend/blob/main/openslides_backend/action/actions/poll/mixins.py#L165) has to be fixed...

**Comment by alveolus** [comment]
Note: The number should not include all delegates, but all persons who belonged to a group with voting rights during the voting.
