### ISSUE TITLE
`/app/openslides_backend/models/field.py` line 469 throws a `NotImplementedError`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1228]
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/app/openslides_backend/http/application.py", line 92, in __call__
>     return self.wsgi_application(environ, start_response)
>   File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
>     response = self.dispatch_request(request)
>   File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
>     response_body, access_token = view_instance.dispatch(request)
>   File "/app/openslides_backend/http/views/base_view.py", line 111, in dispatch
>     return func(request)
>   File "/app/openslides_backend/http/views/action_view.py", line 38, in action_route
>     response = handler.handle_request(request.json, user_id, is_atomic)
>   File "/app/openslides_backend/action/action_handler.py", line 112, in handle_request
>     results = self.execute_write_requests(self.parse_actions, payload)
>   File "/app/openslides_backend/action/action_handler.py", line 149, in execute_write_requests
>     write_requests, data = get_write_requests(*args)
>   File "/app/openslides_backend/action/action_handler.py", line 186, in parse_actions
>     write_request, results = self.perform_action(element, relation_manager)
>   File "/app/openslides_backend/action/action_handler.py", line 223, in perform_action
>     write_request, results = action.perform(
>   File "/app/openslides_backend/action/actions/meeting/import_.py", line 65, in perform
>     instance = self.base_update_instance(instance)
>   File "/app/openslides_backend/action/action.py", line 293, in base_update_instance
>     return self.update_instance(instance)
>   File "/app/openslides_backend/action/actions/meeting/clone.py", line 81, in update_instance
>     checker.run_check()
>   File "/app/openslides_backend/models/checker.py", line 317, in run_check
>     self.check_model(collection, model)
>   File "/app/openslides_backend/models/checker.py", line 340, in check_model
>     errors = self.check_normal_fields(model, collection)
>   File "/app/openslides_backend/models/checker.py", line 384, in check_normal_fields
>     field.validate(model[fieldname], model)
>   File "/app/openslides_backend/models/fields.py", line 469, in validate
>     raise NotImplementedError
> NotImplementedError
> ```

It could be this snippet (in `models/fields.py`):
```python
class TemplateHTMLStrictField(BaseTemplateField, HTMLStrictField):
    def validate(self, value: Any, payload: Dict[str, Any] = {}) -> Any:
        if type(value) == dict:
            sup: Any = super()
            return {key: sup.validate(struc) for key, struc in value.items()}
        elif type(value) == list:
            return value
        elif value is None:
            return None
        raise NotImplementedError()
```

_Originally posted by @GabrielInTheWorld in https://github.com/OpenSlides/openslides-backend/issues/1182#issuecomment-1023994621_

**Comment by jsangmeister** [comment]
Can you provide the meeting data which provoked this error?

**Comment by jsangmeister** [comment]
This is another error than #1242 since it is another line. Can you try again with https://github.com/OpenSlides/openslides-backend/pull/1243 to get more verbose error messages and provide the payload you sent?

**Comment by jsangmeister** [comment]
@GabrielInTheWorld This is another error than https://github.com/OpenSlides/openslides-backend/issues/1242 since it is another line. Can you try again with https://github.com/OpenSlides/openslides-backend/pull/1243 to get more verbose error messages and provide the payload you sent?

**Comment by jsangmeister** [comment]
Closing this for now. Please open a new issue with more data and the new, more verbose error message if the error occurs again.
