### ISSUE TITLE
Remove empty fields from initial and example data as well as all imports/clones

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1233]
The empty fields serve no purpose and should be removed. The checker needs to be adjusted to check not for all fields to be present, but only the required fields. Tests can also be adjusted to not include the empty fields anymore.

**Comment by reiterl** [comment]
I am working on this issue. I will use the `is_partial` feature of the checker.

**Comment by emanuelschuetze** [comment]
As discussed, please kepp only organisation, user and theme in initial data. Other fields can be removed.
