### ISSUE TITLE
Remove `meeting/enable_chat`

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-backend#1234]
So right now the superadmin can `Enable chat globally`, but activating it doesn't mean meetings will have chat enabled now.

So one possible change would be to make the `meeting.enable_chat` field follow `organization.enable_chat` by default upon creation.
However this would require to manually enable it in all meetings created before this change.

Alternatively the `meeting.enable_chat` could be removed completely and enabling chat would work analogous to enabling evoting - globally for the instance.
A person with admin rights would then disable the chat for participants of a meeting by removing the permission. from the group.
Actually from what I can tell, I think a new permission 'can see chat' would make sense for this.

I discussed this with @emanuelschuetze and we are favoring the 2nd proposal.

**Comment by jsangmeister** [comment]
Sounds good to me. It should however be noted that meeting admins will always see the chat which may lead to confusion/irritation or maybe just annoyance since the admin doesn't want to see the chat menu point on the left if it is not used in the meeting. But if you have this in mind, we can do it as you suggested. @emanuelschuetze @peb-adr @GabrielInTheWorld

**Comment by peb-adr** [comment]
Yes we were aware of that.
But the same goes for e.g. elections - they are also visible to the admin, even if not used.
So this would actually make for more consistency imo.

**Comment by jsangmeister** [comment]
Ok. Things to do:
- Remove `meeting/enable_chat` and write migration for it
- Add permission `chat.can_see` and add it the places where needed
  - the autoupdate service will have to take it into account for the restrictions of chats and chat messages

**Comment by emanuelschuetze** [comment]
> Add permission chat.can_see

Why? A normal user can see the chat only if admin creates a chat group with read permission for e.g. delegates. The chat.can_manage permission should be sufficient.

**Comment by jsangmeister** [comment]
> > Add permission chat.can_see
> 
> Why? A normal user can see the chat only if admin creates a chat group with read permission for e.g. delegates. The chat.can_manage permission should be sufficient.

Yes, true. I just followed @peb-adr's suggestion ;)

**Comment by jsangmeister** [comment]
Since now the only change would be to remove the field, an alternative solution would be to keep the functionality as-is and just grey out the setting in the client if the ogranization field is `False`. This would give more control to meeting owners to individualize their meetings. But if you rather want the field removed, that is also easy.

**Comment by peb-adr** [comment]
> > > Add permission chat.can_see
> > 
> > 
> > Why? A normal user can see the chat only if admin creates a chat group with read permission for e.g. delegates. The chat.can_manage permission should be sufficient.
> 
> Yes, true. I just followed @peb-adr's suggestion ;)

Oh see I was a bit confused about that, but I guess @emanuelschuetze would be right that is sufficient.

**Comment by peb-adr** [comment]
> Since now the only change would be to remove the field, an alternative solution would be to keep the functionality as-is and just grey out the setting in the client if the ogranization field is `False`. This would give more control to meeting owners to individualize their meetings. But if you rather want the field removed, that is also easy.

Would it though?
I observe, that only the superadmin can see the check box for `meeting.enable_chat`.
I don't think the "normal" admin would have anything to lose or gain from this, no?
So now already if `meeting.enable_chat == true` the admin's only way to hide it is with user permissions.

Removing the field would make the superadmins life easier though as they don't have to click and check fro every meeting if chat is enabled.

Also am I right in assuming, that removing the `meeting.enable_chat` field would need action in the client, which right now is probably evaluating that for showing/hiding chat in the side bar.

**Comment by jsangmeister** [comment]
> Would it though? I observe, that only the superadmin can see the check box for `meeting.enable_chat`.

You are right, I did not have the permissions in mind. Ok for me to remove the field then.
