### ISSUE TITLE
Prevent spaces at the start and end of usernames

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-backend#1244]
### Setup
Latest Dev Setup

### Describe the bug
`.../committees/import`
When importing committees via CSV file, the usernames of administrators are created spaces (one or more) before them

`.../accounts/...`
In the detail view of an account it is not noticeable that there is a space in front of the username. This leads to the fact that persons cannot log in.  If you copy _username_ and _initial password_ from there, the "wrong login" (without spaces) is copied.

`.../accounts/.../edit`
However, if you go to the edit view of an account, then in the _username_ field there is (one or more) space before the username.

### Problem
This causes massive login problems.

#### CSV file
The content in the "Administrators" column in my CSV file is structured like this: `FirstName1 LastName1; FirstName2 LastName2; FirstName3 LastName3; FirstName4 LastName4`.
→ So: `[First username][Semicolon][Space][Next username][Semicolon][Space][Last username]`

- The usernames of the administrators are separated by a semicolon.
- Before each semicolon is a space, so that the content of the cell is readable for humans.
- There is no semicolon after the last username.

### How to Reproduce
Import committees via CSV with more then one username in a cell, separated by a semicolon

### Expected behavior in this case
User names are created without space **before** them.

### Expected behavior in general

- During import the system checks if there is space **before** or **after** a user name.
- If there is, the space **before** or **after** a username is removed and the username is created correctly.
- Spaces **within** the string, e.g. between first name and last name, will be preserved.

### Important Note
Please check if this is also the case in other columns. Not only here in the committee import, but everywhere where you can import via CSV. For example participant import within an event.

Maybe the issue https://github.com/OpenSlides/openslides-backend/issues/1240 is also related to this?

**Comment by alveolus** [comment]
Detail View `.../accounts/...`

<img width="321" alt="20220225-135421" src="https://user-images.githubusercontent.com/23032204/155718736-c68c15a4-c2e7-4347-a64a-9adb46b17816.png">

Edit View `.../accounts/.../edit`

<img width="199" alt="20220225-135528" src="https://user-images.githubusercontent.com/23032204/155718759-6790631d-571b-4668-998c-5260c3bc58fa.png">

**Comment by jsangmeister** [comment]
Trimming the username should be pretty easy. But I'm not sure if this is more of a task for the client - after all, the client is the one sending "invalid" data here, so I think the client is responsible for the trimming of the names. What do you think @r-peschke @GabrielInTheWorld? (this could also be a good issue for @bug0002)

**Comment by jsangmeister** [comment]
There are multiple solutions for this problem:
- prevent all usernames from starting or ending with a whitespace, regardless of the creation method: I'm against this, since it takes away freedom from teh user. If he explicitely wants to create a username starting with a whitespace (e.g. for added security/indentation/whatever), he would not be able to.
- don't do anything: The way the CSV import (and CSV files in general) are designed is that they take asingle delimiter (`;` in this case) and everything else is data, so the "correct" solution would be to correctly format the data you want to import (without the starting spaces) and import this. If you really want spaces e.g. for readability, you can wrap the names in quotes like this: `"[name1]"; "[name2]"; ...`.
- only trim usernames in the import: Possible, but not entirely logical. This would mean that `...; [name];...` would be correctly trimmed, but also that `...;" [name]";...` would be trimmed, also the data clearly states that the name should start with a space. As written above this would take away freedom from the users. But this would be an okay solution for me and would only require little client work.

**Comment by jsangmeister** [comment]
Talked with @r-peschke and @emanuelschuetze. We will generally prevent usernames from starting or ending with a whitespace. Things to do:
- `user.{create,update}`: Trim `first_name`, `last_name` and `username` (if given and before the username is automatically generated). 
  - Only `user.create`: If no `username` is given, it is no longer generated with whitespaces between the names and the optional number at the end.
 
See https://github.com/OpenSlides/openslides-client/issues/889 for client changes.

**Comment by r-peschke** [comment]
> Talked with @r-peschke and @emanuelschuetze. We will generally prevent usernames from starting or ending with a whitespace. Things to do:
> 
>     * `user.{create,update}`: Trim `first_name`, `last_name` and `username` (if given and before the username is automatically generated).
>       
>       * Only `user.create`: If no `username` is given, it is no longer generated with whitespaces between the names and the optional number at the end.
I agree concerning the whitespaces. But how will you create unique usernames without the number?

**Comment by jsangmeister** [comment]
> I agree concerning the whitespaces. But how will you create unique usernames without the number?

The "without" was only referring to the spaces __between__ the name and the number, not the number itself. So to be clear: 
- before: "Max Mustermann 1"
- after: "MaxMustermann1"

**Comment by emanuelschuetze** [comment]
Reopened because spaces in usernames are not correct removed, e.g. "Max Mario Muster Mann" -> "Max MarioMuster Mann"
So please remove all whitespaces also in first and last name.

**Comment by r-peschke** [comment]
I think we should remove the leading and trailing spaces in first and last name.
Building the username we should join them without space and then remove all spaces from the joined username.
Firstname: "Max Mario", lastname: "Muster Mann", but username: "MaxMarioMusterMann"
