### ISSUE TITLE
Accounts: Error when creating a user manually

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-backend#1245]
**Setup**
Latest Dev Setup

### Describe the bug
`…/accounts/create`
When creating an account, the following error message will be displayed: `data.default_vote_weight must match pattern ^-?(\d|[1-9]\d+)\.\d{6}$`

<img width="579" alt="20220225-135834" src="https://user-images.githubusercontent.com/23032204/155719855-e1a987f6-6204-423b-80c9-e1be91d4b101.png">

### How to reproduce
Create an account and leave the "Default vote weight" field empty.

### Expected behavior
Account is created without cryptic error message. 

@emanuelschuetze What would make sense at this point? Understandable hint with the info that this is a mandatory field? Or automatically value 0 or 1, if nothing is specified?

**Comment by jsangmeister** [comment]
This is a backend bug, an empty value (`None`) should be valid for this field since it isn't required. Has to be changed in the validation in `fields.py`.

**Comment by jsangmeister** [comment]
@alveolus do you have permission to set the project and milestone for issues? If so, please always set "OpenSlides 4" as a project and either "4.0" or "4.1" as the milestone, depending on how urgent you see the issue. If we disagree, we will just change it, but it's better if there is a milestone set to begin with :)

**Comment by jsangmeister** [comment]
> This is a backend bug, an empty value (`None`) should be valid for this field since it isn't required. Has to be changed in the validation in `fields.py`.

Correction: This seems like a client bug. If `None` is given, the error described in https://github.com/OpenSlides/openslides-backend/issues/1242 is thrown. The error described here is only thrown if a non-null value which does not match the decimal pattern is given, e.g. an empty string.

So, it seems like the client is sending an empty string (`""`) for some reason. This should be investigated and maybe the field additionally validated in the client to prevent thease "cryptic" error messages and provide better ones from the client side.

**Comment by alveolus** [comment]
@jsangmeister Yes, I can set Project and Milestone. For future issues, I will do it the way you described.

**Comment by jsangmeister** [comment]
Should be already fixed in the client.
