### ISSUE TITLE
Unify migrations output

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#1248]
Here https://github.com/OpenSlides/openslides-backend/blob/main/openslides_backend/migration_handler/migration_handler.py#L57 the migrations output is "message". In all other cases it is "output". Please use the same property in all cases.

Question for me: Is it correct that the content of "status" is always an integer (0, 1 or 2) and the content of "output" is always a string?

**Comment by jsangmeister** [comment]
Recently talked about this with @peb-adr. The key "message" was used for a verbose message of the status, while "output" is used for  all actual outputs of the migration. We came to the conclusion that the "message" is redundant and can be removed.

> Question for me: Is it correct that the content of "status" is always an integer (0, 1 or 2) and the content of "output" is always a string?

Yes.

**Comment by jsangmeister** [comment]
Additional info: In the case of an error (`success=False`/status code >= 400) the `message` field is used to provide additional information about the error. But this will all be documented with #1227
