### ISSUE TITLE
Change the `calculate_inherited_groups_helper` and add unit tests for it.

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1260]
Then you can change the `calculate_inherited_groups_helper` as suggested above and add unit tests for it.

_Originally posted by @jsangmeister in https://github.com/OpenSlides/openslides-backend/pull/1200#discussion_r823748625_

**Comment by reiterl** [comment]
Add a pull request for this. I have just use another function with the parent_id code and call it at the different places.
I don't think more tests are needed, as there are a lot of tests.
