### ISSUE TITLE
Generalize model/field access

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#128]
Currently, if you want to access a model or field in an action, you have to call the datastore manually like this (copied from #127):

    def update_instance(self, instance: Dict[str, Any]) -> Dict[str, Any]:
        id_ = int(str(instance.get("id")))
        model = self.database.get(
            FullQualifiedId(Collection("motion_comment_section"), id_)
        )
        if model.get("comment_ids"):
            raise ActionException(
                f"Cannot delete motion comment section '{id_}' with existing comments."
            )
        return instance

This is extremely verbose and a huge overload when done regularly. I think the Django approach of wrapping the model and fetching the fields on-demand is well suited here. Since we have the definition of all models and fields, we only need a wrapper analogous to the one we use in the client which does the described, so the above code can be simplified to:

    def update_instance(self, instance: MotionCommentSection) -> MotionCommentSection:
        model = self.get_model() // this is also copied from django, we can automatically fetch the right model from action name and id
        if model.comment_ids:
            raise ActionException(
                f"Cannot delete motion comment section '{model.id}' with existing comments."
            )
        return model

I can try and implement a prototype of this if you want.

**Comment by normanjaeckel** [comment]
I think this sounds like a violation of one or more of the solid principles. We should not create a super magic model class. This I remember we said in dev meeting in January

**Comment by normanjaeckel** [comment]
@ostcar ?

**Comment by jsangmeister** [comment]
It would not be a "super magic model class" but just a wrapper which eases the field access. What we discussed in the dev meeting was that we do not want allmighty models which include all the business logic, but this would not be the case here.

**Comment by jsangmeister** [comment]
Seems like we are not doing this.
