### ISSUE TITLE
New forwarding of motions

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1291]
Dependency: #1290

To facilitate the management of motion forwarding, we will
1. remove the old way: The forwarding user don't need any right in the receiving meeting, the existing right `motion.can_forward_into_this_meeting` will be removed completely from the system.
2. There is a new right `motion.can_forward`. The user needs this right in the source.meeting of the motion. In the target meeting there is no right necessary.
3. Forwarding is only possible, if the motions state has the flag `allow_motion_forwarding` and, old rule, has no parent (meaning `lead_motion_id` and `statute_paragraph_id` are empty).
4. New fields `forwarding_user_id` in committee as relation to users `forwarding_committee_ids`, initially empty. On first forwarding this user will be created `inactive` with the standard group of target-meeting and the name of the source committee. On further forwardings use this user with a new membership of standard group of new meeting, if necessary. The dummy user should have `is_physical_person` set to `False`.
5. New field `forwarded` as creation-timestamp in the motion of the receiving meeting, Restriction-mode B. We cannot use the field `created` anymore, because this is now dependent from the `motion_state`, see #1290.  
6. Use the existing action `motion.create_forwarded` with unchanged payload and same data-handling, except that the dummy user of the committee should be used as a submitter instead of the request user.
7. User, who may see the motion, also have the right to see the motion.forwarded (new timestamp field in created motion) and meeting.name of following motions: motion.origin_id, motion.derived_motions_ids, motion.all_origin_ids, motion.all_derived_ids. This will be implemented in autoupdate-service https://github.com/OpenSlides/openslides-autoupdate-service/issues/455

**Comment by reiterl** [comment]
How must the `get_forwarding_meetings` presenter be updated?

**Comment by jsangmeister** [comment]
> Motion doesnot include a `parent_id`. I don't touch the amendents permission code.

"parent_id" referred to both `lead_motion_id` and `statute_paragraph_id`, as motions with one of those are amendments and cannot be forwarded. I updated the description.

> How must the `get_forwarding_meetings` presenter be updated?

Not at all, if I see it correctly.

> Do we need a migration for the `forwarded` field?

No, since the feature is not in productive use yet.

> What place in the right hierarchy has the new right `motion.can_forward`?

@r-peschke should probably answer this. I would assume parallel to `can_create`, with `can_see` under it.

**Comment by reiterl** [comment]
The old permission is used in get_forwarding_meetings. It *must* be updated.

**Comment by jsangmeister** [comment]
> The old permission is used in get_forwarding_meetings. It _must_ be updated.

You are right, I only checked the wiki. Since the user does not need any permission in the target meeting, the check could just be dropped and all active meetings of all forwardable committees would be returned. This makes the presenter however pretty useless. Maybe we should drop it altogether and the client fetches the data via the autoupdate service and then drops all inactive meetings? @GabrielInTheWorld @r-peschke

**Comment by r-peschke** [comment]
> > The old permission is used in get_forwarding_meetings. It _must_ be updated.
> 
> You are right, I only checked the wiki. Since the user does not need any permission in the target meeting, the check could just be dropped and all active meetings of all forwardable committees would be returned. This makes the presenter however pretty useless. Maybe we should drop it altogether and the client fetches the data via the autoupdate service and then drops all inactive meetings? @GabrielInTheWorld @r-peschke

Then we had to make some changes in autoupdate-service: The user is not allowed to see the committee-fields name, forward_to_committee_ids  and default_meeting_id, see https://github.com/OpenSlides/openslides-autoupdate-service/blob/main/internal/restrict/collection/committee.go

**Comment by jsangmeister** [comment]
> Then we had to make some changes in autoupdate-service: The user is not allowed to see the committee-fields name, forward_to_committee_ids and default_meeting_id, see https://github.com/OpenSlides/openslides-autoupdate-service/blob/main/internal/restrict/collection/committee.go

Right. Then I will update the presenter description accordingly.

**Comment by reiterl** [comment]
I think `forwarding_user` and `forwarding_committee` are the wrong names for id fields.
Better `forwarding_user_id` and `forwarding_committee_id`. Or?
What logic should this new user follow?

**Comment by r-peschke** [comment]
> I think `forwarding_user` and `forwarding_committee` are the wrong names for id fields. Better `forwarding_user_id` and `forwarding_committee_id`. Or? What logic should this new user follow?

yes, you are right about the names. The second question I don't understand. You have to see that the new user is always in the standard_group of all meetings the user did forwardings.

**Comment by reiterl** [comment]
So if `forwarding_user_id` in the committee was empty, I would create a *committee user* and add it to the default group of the meeting the forwarding was to.
If the `forwarding_user_id` in the committee was not empty, I would add this user to the default group of the meeting, which the forwarding was to.

**Comment by reiterl** [comment]
What restriction mode should the forwarding_user_id and the forwarding_committee_id have?

**Comment by r-peschke** [comment]
>If the `forwarding_user_id` in the committee was not empty, I would add this user to the default group of the meeting, which the forwarding was to.

if the user is not already in a group of the meeting.

**Comment by reiterl** [comment]
ah, okay.

**Comment by reiterl** [comment]
I think, that I must update the `user.create` and the `user.update` function to set the `forwarding_committee_id`.

**Comment by r-peschke** [comment]
> What restriction mode should the forwarding_user_id and the forwarding_committee_id have?

committee.forwarding_user_id restriction_mode B
user.forwarding_committee_**ids** restriction mode F

**Comment by reiterl** [comment]
> > What restriction mode should the forwarding_user_id and the forwarding_committee_id have?
> 
> committee.forwarding_user_id restriction_mode B user.forwarding_committee_**ids** restriction mode F

What? Why **ids**? There should be one user per committee and a committee can just have one forwarding user.

**Comment by reiterl** [comment]
I discussed this issue with @r-peschke . We want user.forwarding_committee_ids for future extensions. We want to update the
`user.create` action and add the forwarding_committee_ids there only for internal action. In external case usable of the field should lead to a `ActionException`.

**Comment by r-peschke** [comment]
> > > What restriction mode should the forwarding_user_id and the forwarding_committee_id have?
> > 
> > 
> > committee.forwarding_user_id restriction_mode B user.forwarding_committee_**ids** restriction mode F
> 
> What? Why **ids**? There should be one user per committee and a committee can just have one forwarding user.

At the moment you are right, but it cost nothing and is easier to expand later

**Comment by jsangmeister** [comment]
The dummy user should have `is_physical_person` set to `False` and should be put into the `submitter_ids` in the newly created (forwarded) motion.
