### ISSUE TITLE
Implement the field `start_line_number` for the collection `motion`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1292]
This should be from type `number` and should have the restriction mode `A`.

**Comment by jsangmeister** [comment]
What's the meaning of it?

**Comment by reiterl** [comment]
In which actions this field should be set?

**Comment by reiterl** [comment]
I assume it is a field the client needed. What permissions does the user need to set this field?

**Comment by GabrielInTheWorld** [comment]
> I assume it is a field the client needed. What permissions does the user need to set this field?

Yes. It should be configurable by the action `motion.update` and a user needs at least the permission `motion.can_manage_metadata`.

**Comment by reiterl** [comment]
Discussed and not needed.

**Comment by reiterl** [comment]
We need a default and a migration to set the default, too.
The default should be 1.
