### ISSUE TITLE
Implement the option to add users as admin or participant of a meeting when cloning one

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1306]
Similar to the action `meeting.create` there should be the option to pass `admin_ids` and `user_ids` for the action `meeting.clone`.

**Comment by reiterl** [comment]
Mmh, a raw plan for this:

0. update the action description
1. Add the two fields to the payload as additional optional fields.
2. pop them in the beginning of the update_instance method (so no problem with the checker.)
3. Validate the user_ids of both. (I ain't sure how exact.)
4. Get the default/admin group of the cloned meeting at the end of the updated_instance methods and add the ids. (extra wr and calculated fields should then be handled automatic)
5. Write a lot of tests, to check it (relations, calculated fields,...)
