### ISSUE TITLE
Update the export_meeting presenter

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1320]
We want to update the `export_meeting` presenter. See below comments.

Here the errors:
<details>
meeting/1/present_user_ids: Relation Error:  points to user/1/is_present_in_meeting_ids, but the reverse relation for it is corrupt

meeting/1/organization_tag_ids: Relation Error:  points to organization_tag/foreign_id, which is not allowed in an external import.

meeting/1/default_meeting_for_committee_id: Relation Error:  points to committee/1, which is not allowed in an external import.

assignment_candidate/1/user_id: Relation Error:  points to user/1/assignment_candidate_$1_ids, but the reverse relation for it is corrupt

assignment_candidate/2/user_id: Relation Error:  points to user/3/assignment_candidate_$1_ids, but the reverse relation for it is corrupt

assignment_candidate/3/user_id: Relation Error:  points to user/2/assignment_candidate_$1_ids, but the reverse relation for it is corrupt

assignment_candidate/4/user_id: Relation Error:  points to user/3/assignment_candidate_$1_ids, but the reverse relation for it is corrupt

assignment_candidate/5/user_id: Relation Error:  points to user/2/assignment_candidate_$1_ids, but the reverse relation for it is corrupt

group/2/user_ids: Relation Error:  points to user/1/group_$1_ids, but the reverse relation for it is corrupt

group/5/user_ids: Relation Error:  points to user/2/group_$1_ids, but the reverse relation for it is corrupt

group/5/user_ids: Relation Error:  points to user/3/group_$1_ids, but the reverse relation for it is corrupt

motion/3/supporter_ids: Relation Error:  points to user/3/supported_motion_$1_ids, but the reverse relation for it is corrupt

motion_submitter/1/user_id: Relation Error:  points to user/1/submitted_motion_$1_ids, but the reverse relation for it is corrupt

motion_submitter/2/user_id: Relation Error:  points to user/1/submitted_motion_$1_ids, but the reverse relation for it is corrupt

motion_submitter/3/user_id: Relation Error:  points to user/1/submitted_motion_$1_ids, but the reverse relation for it is corrupt

motion_submitter/4/user_id: Relation Error:  points to user/1/submitted_motion_$1_ids, but the reverse relation for it is corrupt

option/5/content_object_id: Relation Error:  points to user/1/option_$1_ids, but the reverse relation for it is corrupt

option/7/content_object_id: Relation Error:  points to user/1/option_$1_ids, but the reverse relation for it is corrupt

option/8/content_object_id: Relation Error:  points to user/3/option_$1_ids, but the reverse relation for it is corrupt

option/9/content_object_id: Relation Error:  points to user/2/option_$1_ids, but the reverse relation for it is corrupt

option/11/content_object_id: Relation Error:  points to user/3/option_$1_ids, but the reverse relation for it is corrupt

option/12/content_object_id: Relation Error:  points to user/2/option_$1_ids, but the reverse relation for it is corrupt

personal_note/1/user_id: Relation Error:  points to user/1/personal_note_$1_ids, but the reverse relation for it is corrupt

poll/5/voted_ids: Relation Error:  points to user/1/poll_voted_$1_ids, but the reverse relation for it is corrupt

speaker/1/user_id: Relation Error:  points to user/1/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/2/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/3/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/4/user_id: Relation Error:  points to user/3/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/5/user_id: Relation Error:  points to user/1/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/6/user_id: Relation Error:  points to user/1/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/7/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/8/user_id: Relation Error:  points to user/3/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/9/user_id: Relation Error:  points to user/3/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/10/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/11/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/12/user_id: Relation Error:  points to user/1/speaker_$1_ids, but the reverse relation for it is corrupt

speaker/13/user_id: Relation Error:  points to user/2/speaker_$1_ids, but the reverse relation for it is corrupt

vote/9/user_id: Relation Error:  points to user/1/vote_$1_ids, but the reverse relation for it is corrupt

vote/9/delegated_user_id: Relation Error:  points to user/1/vote_delegated_vote_$1_ids, but the reverse relation for it is corrupt
</details>

**Comment by reiterl** [comment]
I think the reason of the most errors is missing **users** in the export_meeting presenter.

**Comment by reiterl** [comment]
We want to update the `export_meeting` presenter. 

* It should include **users**.
* It should exclude **organization_tags**.

**Comment by jsangmeister** [comment]
Keep in mind that the `export_meeting` function is also used by `meeting.clone` if you adjust this.
