### ISSUE TITLE
define replacement_enum for field meeting.font_$_id

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1333]
This fields contains the `place`, where to use a font, identified by a mediafile_id, in a meeting. `place` is an enumeration, containing places like `bold`,`h1`, `h2` etc.. This enumeration is only defined in the client, we want to implement a validation on backend side.

To implement this feature, we need the currently available places from client 
Talked with @m-schieder for client-side

**Comment by reiterl** [comment]
@m-schieder We need a complete list of places, which could be part of the `meeting.font_$_id` field.

I will update the tests. Use `bold`.

**Comment by reiterl** [comment]
We could then define a `replacement_enum` like in the `committee__management_level` field.

**Comment by reiterl** [comment]
We need to configure a replacement enum and then use it to check the place.
We can get replacement_enum with `Meeting().get_field("font_$_id").replacement_enum` then.
I have build a mechanism, which checks for this.

**Comment by r-peschke** [comment]
> @m-schieder We need a complete list of places, which could be part of the `meeting.font_$_id` field.


@m-schieder @luisa-beerboom  Could one of you confirm this link to the places in client: https://github.com/OpenSlides/openslides-client/blob/176e58f55472145a917bf606616b19adf48cd11c/client/src/app/domain/models/mediafiles/mediafile.constants.ts#L21

Shouldn't we also use the type LogoPlace in the same file to check?

**Comment by luisa-beerboom** [comment]
@m-schieder I have not really worked with the fonts yet, so can you say something about this?

**Comment by m-schieder** [comment]
> > @m-schieder We need a complete list of places, which could be part of the `meeting.font_$_id` field.
> 
> @m-schieder @luisa-beerboom Could one of you confirm this link to the places in client: https://github.com/OpenSlides/openslides-client/blob/176e58f55472145a917bf606616b19adf48cd11c/client/src/app/domain/models/mediafiles/mediafile.constants.ts#L21

Yes these are the places from the client.
