### ISSUE TITLE
The recommendation collides with an existing one

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1340]
In some cases I run into a collision where no collision should exist:

Try to reproduce with a motion:
* create cr for line 1-2
* create cr for line 6
* create cr for line 11 => `Error: The recommendation collides with an existing one (line 11 - 11).`

**Comment by reiterl** [comment]
For the datastore is `2 >= 11` true as it transfers int into text and does a string compare for integers.

**Comment by reiterl** [comment]
This problem should will be fixed, if the https://github.com/OpenSlides/openslides-datastore-service/pull/198 pr is merged.

**Comment by reiterl** [comment]
After merging the datastore, this problem is fixed.
