### ISSUE TITLE
Remove `publish_immediately` from datastore payload

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1353]
On `poll.{create|update}` and `option.{create|update}`, the key `publish_immediately` is not removed from the instance before sending it to the datastore. This has to be changed. Additionally, the field has to be removed from existing models via migration to enable cloning of the corrupted meetings again.

Since we've had a few of these issues now, I propose to check the content of events in the backend before sending it to the datastore. We already do that in the tests to assert that the data for the tests is valid: https://github.com/OpenSlides/openslides-backend/blob/1ed1197d524f5c6f03db7fb7e6ca7ab14ec6f8cb/tests/system/base.py#L187 I propose to also run this test for the actual events sent to the datastore to prevent such errors (especially the resulting migrations) in the future.

**Comment by r-peschke** [comment]
I agree we should test the write_requests, whether they contain fields not included in models.py. My proposal is to extend the method **Action.validate_required_fields** in actions.py (and perhaps rename the method) for this check. It is called after constructing a single write_request.

**Comment by jsangmeister** [comment]
I would not only check if the write request contains invalid fields, but also check the content of the fields like in the method linked above. I don't think it will cost much speed-wise and we would be much safer regarding invalid datastore content.
