### ISSUE TITLE
Do not send internal error messages to the client

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1387]
I got the following error by the client.
![error](https://user-images.githubusercontent.com/977937/176936375-8255c908-7964-428c-9e19-14cb4a368be9.png)

It is an internal error from the vote service to the backend. It should not be shown to the client. Please only send errors to the client, that they are supposed to see. 

This is related with https://github.com/OpenSlides/openslides-backend/issues/1262

**Comment by jsangmeister** [comment]
Are these kind of errors logged in the vote service (with an appropriate, i.e. high enough, log level)? If not, this needs to be implemented first.
