### ISSUE TITLE
Add history information for users

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1409]
Users should also get a history view for specific informations, analogous to the way done in #1356 for motions. The specific informations should be:
- "User updated" when the following fields are changed:
  - titel
  - first_name
  - last_name
  - email
  - username
  - default_structure_level
  - default_number
  - default_vote_weight
- "User updated in meeting x" when the following structured fields change for meeting x:
  - structure_level_$
  - number_$
  - vote_weight_$
- "Group x added/removed"
- "Set (not) present in meeting x"
- "OML/CML changed"
- "Set (in)active"

**Comment by reiterl** [comment]
I assume that the action `user.update` should get a `get_history_information` method. For some of this info I need to diff instance values and datastore values, or am I wrong?

**Comment by jsangmeister** [comment]
Yes. We should additionally think about diffing the values provided by the client with the current state by default and removing unchanged values to reduce history information and events in general. But this is an issue for another time.

**Comment by reiterl** [comment]
The "Group x added/removed" doesn't make sense. @jsangmeister can you explain it more.

**Comment by jsangmeister** [comment]
> The "Group x added/removed" doesn't make sense. @jsangmeister can you explain it more.

For a meeting y, the field `group_$y_ids` controls the groups of the user in that meeting. If groups are added/removed from that array, it should be reflected in the history.

**Comment by reiterl** [comment]
You have instance x for user a and instance y for user b and its Groups should be mixed?

**Comment by reiterl** [comment]
@jsangmeister Which user? In two instances are two users.

**Comment by jsangmeister** [comment]
No. Suppose `user/1` looks like this:
```
{
  ...
  "group_$_ids": 1,
  "group_$1_ids": [42],
  ...
}
```
Now, a `user.update` comes with the following payload: 
```
{
  "group_$_ids": {
    "1": [42, 43]
  }
}
```
meaning user 1 was added to group 43 in meeting 1. This should be reflected in the history entry in the form of "Added to group {group_name}". Analogous behaviour should be implemented if a group is removed. If multiple groups were added or removed, the message should just say "Groups changed".
