### ISSUE TITLE
Motion manager should be able to set every state to a motion

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-backend#1411]
The status of motions cannot be changed by multiple selection if they have different statuses.

Reproduction: 

1. Open https://testintern.openslides.com/70/motions
2. Open Three-Dot-Menu, choose Multiselect and select all motions
3. Open Three-Dot-Menu again and choose Set Status.  
4. Change Status to accepted.
5. An error occurs.

What should happen: Changing several motion statuses at a different level at once should be possible. 

Example image with error:
![Screenshot_20220718_144354](https://user-images.githubusercontent.com/105491030/179521404-5e7f8e36-925d-43c4-a4e6-9b5cc8160f18.png)

**Comment by jsangmeister** [comment]
Intended behaviour: Normal users (e.g. submitters of motions) are still prohibited by the workflow order. Users with `motions.can_manage` should, however, not be prohibited by that and should instead be able to set every state of the workflow they like.

**Comment by reiterl** [comment]
Added a pr.
