### ISSUE TITLE
Update check_database presenter for the whole database

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1419]
A version of the check_database presenter is merged. It uses the checker and the export_meeting function to check all meetings.
We want the check_database to check the whole database. We cannot get the database in one chunk, because the database could be too big.

**Comment by reiterl** [comment]
If I want to check the database, I need to get everything from the db. How does the cache handle this? I think, that the cache is per presenter and getting the database as whole or parts perhaps doesn't make a difference.

**Comment by reiterl** [comment]
How do I get the whole database as JSON? `get_all()` doesn't help here, I suppose, because I need to fill mapped_fields.

**Comment by reiterl** [comment]
Add a PR. This version gets the whole database and checks it with a all-mode checker.

**Comment by r-peschke** [comment]
Implement it as 2nd check for whole database besides the first check of meeting. See https://github.com/OpenSlides/openslides-client/issues/1566 for client issue implementing a start button.
