### ISSUE TITLE
Implement Cascade deletion

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#142]
E.g. when deleting a workflow, all its states should be deleted, too.

**Comment by jsangmeister** [comment]
@normanjaeckel I looked into it and noticed that we currently have 2 fields for this: `on_delete` and `delete_protection`. Can you explain to me the purpose of these and we there are 2? Also, we need to define which possibilities we need for the on_delete case. 

My suggestion: We have to variables for each field, `on_delete` and `on_reverse_delete`, which can be defined as `SET_NULL`, `PROTECT` and `CASCADE`. In the `DeleteAction`, we iterate over the fields like we currently do and validate everything. In the cascade case, we execute the delete action of the target. We need the reverse case e.g. for `motion_comment`, which has a foreign key to `motion_comment_section`, but the section can't be deleted if it holds any comments.

What do you think? I already started implementing some of this before I noticed the double variable usage, so don't also implement it...

**Comment by normanjaeckel** [comment]
I have to look at this.

**Comment by normanjaeckel** [comment]
Hm. What about using a cascade deletion for all cases with required relation fields and "set_null" with non-required fields? So we do not need a second property. The `delete_protection` property looks like the wrong way so we can remove it.

So if `model_a` has a relation to `model_b` via the field `model_a/field_to_model_b_id` and this field has a required flag in `models.yml` we can handle as follows: If you delete the instance of model b the instance of model a is deleted too.

If you delete the instance of model a you have to look at the reverse field `model_b/field_to_model_a_id`.

A relation-list field should never have this `required=True´ flag.

Generic OneToOne relation is more difficult but I think we can solve it.

Maybe we should have a short phone call if you like.
