### ISSUE TITLE
Migration for setting projection.content_object_id to required

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1425]
In https://github.com/OpenSlides/openslides-backend/issues/1357 is stated, that we don't need a migration.
But we have got a customer database with a projections with content_object_id == None in a large number.
There are different ways to handle this. One is to write the missing migration. Or "improve" the clone method or the checker.

I'm not sure how to continue here.

**Comment by r-peschke** [comment]
The projections with content_object_id should be set to deleted and the projection should be removed from it's usage, i.e. projector.current_projection_ids.
Where is this case from? Is it a customers database to import?

**Comment by jsangmeister** [comment]
Handled via a datastore script so we don't need a migration. Closing this
