### ISSUE TITLE
Backend with multiple workers can have problems with database inconsistencies

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1431]
Gunicorn workers are processes with own memory. One worker works on one request in parallel as far as I know.
So if two concurring requests with similar changes came in, the locked fields don't help and both workers send stuff to the datastore. That could lead to database inconsistencies.

**Comment by reiterl** [comment]
I tried to understand the sync workers. I found this page:
https://www.joelsleppy.com/blog/gunicorn-sync-workers/

**Comment by r-peschke** [comment]
Let's talk about it!

**Comment by jsangmeister** [comment]
Why shouldn't the locked fields help? They are exactly designed for this use case

**Comment by reiterl** [comment]
I talked to @r-peschke  about this issue. As far as I understand it, that the locked fields can handle multiple backend processes.
So I close this issue.
