### ISSUE TITLE
Not possible to upload organization level mediafile without token

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1433]
On the mediafiles page of the wiki it is implied that the token field can be empty, even for organization mediafiles, but reality doesn't seem to comply with that

payload: 

```
[
  {
    "action": "mediafile.upload",
    "data": [
      {
        "owner_id": "organization/1",
        "file": "<...>",
        "filename": "How_to_git.txt",
        "title": "How_to_git.txt",
        "parent_id": null,
        "token": undefined
      }
    ]
  }
]
```
(file data cut out to shorten it)

Sending this will return an `Internal Server Error` without a proper message.
Sending a token will work, even if it is `null`. (But I managed to corrupt my database by uploading two different files with null as a token (which is to be expected as token is apparently supposed to be unique, even then it is strange that the file was accepted))

**Comment by luisa-beerboom** [comment]
This is a bit of a problem, since it affects OpenSlides/openslides-client#1509

**Comment by reiterl** [comment]
undefined is not a valid JSON value, even though it is valid in javascript. 
quote from https://stackoverflow.com/questions/13796751/json-undefined-value-type

**Comment by luisa-beerboom** [comment]
Yeah, sorry that was the client-internal payload.
As it it sent those values are left out, so it is shortened to:

```
[
    {
        "action" : "mediafile.upload",
        "data": [
            {
                "owner_id" : "organization/1",
                "file": "<...>",
                "filename": "How_to_git.txt",
                "title": "How_to_git.txt",
                "parent_id": null
            }
        ]
    }
]
```

By the way, the response is this:

```
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

**Comment by reiterl** [comment]
Okay, I will look at the problem.

**Comment by reiterl** [comment]
I can reproduce it, it is KeyError in the orga mediafile upload action. I added a pr for that. @luisa-beerboom can you test the pullrequest? Then I can merge it, else set Joshua or Ralf as reviewer.
