### ISSUE TITLE
Discussion: Implement the anonymous user feature in the backend

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1435]
The allow anonymous user feature currently doesn't work in the client and will be very hard to implement in a stable manner, because this needs to be considered in all kinds of different places in the client which are nigh impossible to keep track of.

That is why we should think about handling it, at least partially in other services:

The idea:
1. Create a special user "Guest", which implicitly exists in every instance and may not be manually changed by other users.
2. Dynamically add/remove this user to/from a (hidden?) guest group in any meeting where the setting "Allow anonymous users" is toggled. This group should not be allowed to have permissions aside from viewing perms.
3. Change the auth service so that token-less users get the anonymous users token (would probably be taken care of by client devs)

Open Questions:

- How would this be implemented?
- What needs to be considered?
- Is this feasible in terms of workload or should we just remove the anonymous user feature entirely, since it is apparently not used that often?

**Comment by jsangmeister** [comment]
I don't like this solution, it is kind of hacky and (I think) basically what was done manually by users before this function was implemented - create a guest user and publicly share the access data.

Previously (at least in OS3, and I think at the start of OS4 too) it worked with no issues with the anonymous. What's the problem why this cannot be reimplemented easily? I would think that the `OperatorService` is the place of abstraction where this is handled.

**Comment by luisa-beerboom** [comment]
Our current solution is also hacky: In the client we're basically just saying "If anonymous is enabled we'll just pretend that the unauthenticated operator is actually authenticated as a user with extremely limited rights"

The problem is that over time there have been quite a few occasions where people built in functions in the frontend that handled actions like "throwing unauthorized users out of meetings", "throwing unauthenticated users to login", "opening login page on startup", "hiding certain pages from users without the permission" (not all of them in the operator service btw), many of which don't consider the possibility of a user being a guest.
The result of which being that anonymous users were consistently thrown to the login page. 

I tried to fix this for hours on end by trying to find and fix all of these places in the code, but no success.

Since this feature is rarely used there is the danger that it will continue to be destroyed by such changes, without it being noticed for longer periods of time. Having the anonymous user as an actual user account, and simply assigning that to anyone who isn't authenticated may be hacky, but it's simply much more maintainable

**Comment by jsangmeister** [comment]
I don't think it is much more maintainable. You will have to filter it out of every list and detail view as well as all search selectors, just for example (e.g. anonymous should not be the candidate of a poll). We can talk about the necessary changes or you can push them and I'll have a look, but moving this behaviour into the other services does not make it easier at all.

**Comment by luisa-beerboom** [comment]
Most of the search selectors involving users are already one of `account-search-selector` and `participant-search-selector`, changing just these two will already take care of most of them. Since we wouldn't allow for this user to be added to anything, he should theoretically not show up in any detail views except his own (which is probably ok) and the meeting/committee ones (where we can filter him out). That only leaves the account and participant list.

Since we're already hacking, we could also look into just overriding the controllers' getViewModelList(-Observable) functions to automatically filter him out.

The reason why I think this will be more maintainable is, because the potential bugs that could arise would generally all be of the same (relatively mild) nature i.e. we may sometimes discover that some list shows the guest user when it shouldn't (probably a pretty quick fix), as opposed to getting complaints that a whole feature (the anonymous function) is straight out not working every half year.
The latter would then cause us to go on a massive headache-inducing detectives journey trying to find all the code that was changed over the last 6 months that may have possibly, maybe broken this feature, all for a feature that isn't even that frequently used.

**Comment by luisa-beerboom** [comment]
According to what @rrenkert just wrote in OpenSlides/openslides-client#1381, it's been decided that the anonymous user feature will be removed, therefore there is no real point in discussing this further.

I'll close this issue.
