### ISSUE TITLE
Translate group names, workflows etc. upon meeting creation

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1437]
When a meeting is created, currently all default names like groups, workflows, states, etc. are created in english and translated in the client to display it to the user in their preferred language. This is cumbersome and error prone since the client always has to bridge between the english backend and the german (or otherwise translated) client. After #1430 is merged, the backend is able to translate these strings upon creation, which would ease up the whole process a lot in my opinion. Any opinions?

Only potential problem might be the migrations. We will have to discuss how we progress there.

**Comment by jsangmeister** [comment]
Talked with @emanuelschuetze and this looks like a good idea. Following points to do:
- introduce a setting `organization/default_language` which can be changed by orga admins
  - the manage service should force the user to select a language upon instance creation since e.g. the orga email invitation body will be translated upon instance creation and is not easily translatable later. I will create an issue for this once this is finalized
- `meeting.create` gets an additional payload item `language` which is the organization's default language by default. All group/state/projector/countdown names etc. will be translated into this language upon creation. They should no longer be translated in the client.
  - TODO: maybe we need to save the language in the meeting as well

**Comment by reiterl** [comment]
Translation is a huge topic and a can of bugs. I talked to @r-peschke about this issue.
I see problems here:

- how to handle the migration? A process with two migrations with a delay is difficult.
- Do we want a meeting.set_language action then?  How would that work, if s.o. switchs from German to Swedish as example?
- Some code is based on the group names. We would need to change that.

Anyway, how does the search service handle group names?

**Comment by reiterl** [comment]
In `meeting.create` the following collections are created too:

- Groups
- Projector Countdown
- Workflow
- Projector
- and in Simple/Complex Workflows: some States

**Comment by reiterl** [comment]
What kind of fields should that be (restriction_mode, read_only)?

**Comment by jsangmeister** [comment]
Both read-only and both restriction mode A (does not really matter, but it is not critical information, so A is the easiest to implement/execute).

**Comment by reiterl** [comment]
Why do we need a migration for default language? Migrations are expensive and the Translator takes en_US if it is None.

**Comment by reiterl** [comment]
Yes, we need a simple migration, because else check_database_all will show an error.

**Comment by reiterl** [comment]
Updated the action wiki.

**Comment by jsangmeister** [comment]
@normanjaeckel @luisa-beerboom manage service and client have to be adjusted for this

**Comment by jsangmeister** [comment]
see https://github.com/OpenSlides/openslides-backend/pull/1502#issuecomment-1427728151 for migration discussion
