### ISSUE TITLE
Create enable delegation of vote setting

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1440]
See OpenSlides/openslides-client#1512

Meetings should have an `enable_vote_delegations` setting that should work analogously to how the `enable_vote_weight` setting works, just for delegations. 

This field should probably be set to `true` by default, as that would be the option that preserves the current functionality.

**Comment by reiterl** [comment]
Do you mean the `users_enable_vote_weight`? There is no field `enable_vote_weight` in meetings.

**Comment by reiterl** [comment]
The field `users_enable_vote_weight` does not do anything in the actions. So you want to have the field `users_enable_vote_delegations`just in the meeting, like `users_enable_vote_weight`?

**Comment by reiterl** [comment]
@luisa-beerboom  Please answer the questings.

**Comment by reiterl** [comment]
Do you want a migration, which set the true default?

**Comment by r-peschke** [comment]
We have to discuss the impact of this setting in the backend. IMO with user_forwarding set to false, we should prevent user from setting vote forwarding or from forwarded voting or (minimum) just from latter

**Comment by luisa-beerboom** [comment]
> Do you mean the `users_enable_vote_weight`? There is no field `enable_vote_weight` in meetings.
Yes,

> The field `users_enable_vote_weight` does not do anything in the actions. So you want to have the field `users_enable_vote_delegations`just in the meeting, like `users_enable_vote_weight`?
yes,

> Do you want a migration, which set the true default?
and yes.

**Comment by reiterl** [comment]
@emanuelschuetze  said in the pr: The field should be `false`, because this is a optional feature and we don't want a migration.

So no migration is needed.
