### ISSUE TITLE
`poll.update`: Should be able to send null for Y, N or A

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1448]
When editing an analog poll, `option.update` allows for the changing of vote values.
It is possible to set both, fields that were left empty upon creation and those that already had a value, to any number one pleases.

It would be expected that setting one of the fields `Y`, `N` or `A` to null would delete the contents of that field in the backend, making it as if it had never been set in the first place. That is currently not happening, instead the client receives error messages like `data.Y must be string`.

Please change the action so that `Y`, `N` and `A` can be set to null, at least for the properties that apply to the corresponding polls pollmethod

**Comment by r-peschke** [comment]
Everything works as expected. Don't transmit null/None values, like you do, and the value is set back, "as if it had never been set in the first place", i.e. with the internal value "-2.000000".

**Comment by luisa-beerboom** [comment]
> mit null/None values

What do I send then?

**Comment by r-peschke** [comment]
> > mit null/None values
> 
> What do I send then?

Leave it, as it is. Send nothing and the backend will change the "nothing send" internally to a decimal "-2.00000", which stand for "nothing send".
