### ISSUE TITLE
Remove value `user.can_see_extra_data` from `group/permissions`

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1452]
In https://github.com/OpenSlides/openslides-backend/issues/1116, the permission `user.can_see_extra_data` was removed, but we seem to have forgotten to write a migration removing it from existing fields. We are currently getting errors because groups cannot be updated because they still contain the old permission. We should write a migration to fix this.

Another approach would be to update the `group.set_permission` code to filter out any invalid permissions. This might also be more future proof, in case something similar happens again, but may not be as clean. What do y'all think?

**Comment by jsangmeister** [comment]
talked with @r-peschke and the migration is the way to go.

**Comment by reiterl** [comment]
Add a migration which remove the user.can_see_extra_data from the group.permissions field.
