### ISSUE TITLE
Remove template fields for users

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1454]
Remove all template-fields from models.yml and fix the occuring errors.
Also see draft in https://github.com/OpenSlides/openslides-backend/pull/1352 for UserMeeting-collection.

**Comment by reiterl** [comment]
I think we should not use the pr #1352, but start from scratch with creating of an  *empty* user_meeting collection. And then move one field after another.

**Comment by reiterl** [comment]
What restriction_mode should the user_meeting fields have? (eg. `user_meeting/user_id, user_meeting/meeting_id, meeting/user_meeting_id, user/user_meeting_id`?)

**Comment by reiterl** [comment]
The first todo is the creation of an empty user_collection, add the internal actions user_meeting.{create|update|delete} and some basic tests.

**Comment by reiterl** [comment]
Next step: I will add the action documentation for the user_meeting actions.
