### ISSUE TITLE
Fix race condition test in motion/test_create_sequential_number.py

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1473]
This test is marked with pytest.skip and can't be used anymore, because it constructs a race condition using thread, lock and sync_event objects. With the thread watching, implemented by #1137, this doesn't work this simple way, because the action is processed in a new worker thread.

**Comment by reiterl** [comment]
The test `test_create_sequential_numbers_race_condition` is not skipped and seems to be complicated. Do you mean it *will* be skipped and needs rework?

**Comment by r-peschke** [comment]
This test is a little bit complicated, because it enforces a race condition by monkey patching. With the thread watching it doesn't work anymore, because the work on an action was moved to an other thread.
It  need's some knowledge of thread-behavior and monkey-patching to  resurrect the test, but we should do.
