### ISSUE TITLE
Protect against deleting one self

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-backend#1474]
As a superadmin I accidentally deleted the myself.

I think we had a protection against this in OS 3. Should we add one in OS4?

If it should be allowed to delete one self, you should at least get logged out, because the current behavior  is strange

**Comment by r-peschke** [comment]
@emanuelschuetze @ostcar @rrenkert @reiterl 
We should discuss first, what we want.
IMO we should prevent a superadmin,to delete himself, eventually only if he is the only superadmin.
