### ISSUE TITLE
Agenda Item Creation (not always)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#156]
See https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/agenda_item/agenda_creation.py#L58

When creating motion, assignment or motion_block the client sometimes want to create an agenda item and sometimes not.

So this method should get some logic according to the value of `agenda_create` property in payload and according to meeting settings `agenda_item_create`.

An exception is topic: Here we always want to create an agenda item.

@reiterl: Sorry. Some of my last remarks in former pull request were missunderstanding. This feature was not even implemente for motion block. It is still missing for all the three collections. Are you interested in implementing this now?

**Comment by reiterl** [comment]
Working on it.

**Comment by jsangmeister** [comment]
The `check_dependant_action_execution` function can just be overridden in the actions if it needs extra logic. If the logic is the same for all classes, we can just create another intermediate base class.
