### ISSUE TITLE
Speed up GitHub actions.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#157]
Maybe we can speed up the actions by caching the docker images, esp. the images for datastore ...

See https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

**Comment by jsangmeister** [comment]
Closed in favor of https://github.com/OpenSlides/openslides-backend/issues/184. You could have just used this issue... :D
