### ISSUE TITLE
Multi motion forwarding bug involving the committee user

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1572]
Reproduction:
Version 1: From a origin meeting in a committee from which nothing was ever forwarded (i.e. no pre-existing committee user), forward a motion to multiple other meetings at once using motion.create_forwarded.
=> Error: {'fqid': 'user':number} (where number is the next non-existant user id)

Example:
```
//Request
[
	{
		"action": "motion.create_forwarded",
		"data": [
			{
				"meeting_id": 15,
				"origin_id": 393,
				"reason": "",
				"text": "<p>Text</p>",
				"title": "Title"
			},
			{
				"meeting_id": 16,
				"origin_id": 393,
				"reason": "",
				"text": "<p>Text</p>",
				"title": "Title"
			}
		]
	}
]

// Answer
{
	"success": false,
	"message": " {'fqid': 'user/38'}"
}
```

Version 2: If a committee user already exists for the origin committee, try forwarding another motion to multiple meetings, at leastone of which has not yet been forwarded to from this committee (i.e. one of them doesn't yet have the committee user added to the participants)
=> Error: "User does not exist on meeting" (user being the origin committee user)

If just one meeting (or two if the committee user is already a participant in them) is targeted, it works.

**Comment by r-peschke** [comment]
You can send the payload in the following manner on the **handle_separately**-Route to the backend. This way, the 2 forwardings are treated as separate **transactions** and handled correctly. It is necessary, to send each of them separate with the action name. 


```
        response = self.client.post(
            ACTION_URL_SEPARATELY,
            json=[
                {
                    "action": "motion.create_forwarded",
                    "data": [
                        {
                            "meeting_id": 2,
                            "origin_id": 12,
                            "reason": "",
                            "text": "<p>Text 2</p>",
                            "title": "Title 2",
                        },
                    ],
                },
                {
                    "action": "motion.create_forwarded",
                    "data": [
                        {
                            "meeting_id": 3,
                            "origin_id": 12,
                            "reason": "",
                            "text": "<p>Text 3</p>",
                            "title": "Title 3",
                        },
                    ],
                }

            ],
        )
``

**Comment by r-peschke** [comment]
Remembering: This should work! But I hope to remember well, that there is no adequate response, i.e the client doesn't know, what happened on backend-side after receiving the response.

**Comment by reiterl** [comment]
@luisa-beerboom Can you verify that sending the actions this way works? Can we close this issue?

**Comment by r-peschke** [comment]
> @luisa-beerboom Can you verify that sending the actions this way works? Can we close this issue?

I think this is a bug the backend should take care, because there is no adequate response for the client.

**Comment by r-peschke** [comment]
Meeting com @jsangmeister : History problem with 2 forwardings in 1 transaction: 2nd forwarding with same created forwarding-user will have no history-data, because user still isn't in database. As a special edge-case we will not implement a solution for this.
