### ISSUE TITLE
remove field presence from user.update

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1573]
We want to use the existing action[ user.set_present](https://github.com/OpenSlides/OpenSlides/wiki/user.set_present) to set or unset the presence of a user.

The documentation in the wiki on user.update and DE:OS4-User-API is updated.

**Comment by jsangmeister** [comment]
Why the sudden change of mind? That is exactly what I suggested in https://github.com/OpenSlides/openslides-backend/issues/1505 when we implemented this feature, which was less then 3 months ago... @emanuelschuetze is the compatibility to external software not needed anymore? Implementing feature to de-implement them 3 months later seems like a waste of time.
