### ISSUE TITLE
Initial attributes of workflow-states

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#158]
Creating a new workflow-state, there are three attributes, that should have an initial value. Omitting that will run into errors (in the client).
1. merge_amendment_into_final
2. restrictions
3. css_colors

**Comment by FinnStutzenstein** [comment]
> restrictions

The default is `[]`, isn't it? Maybe we should wix the client to treat `null` as `[]` here.

**Comment by jsangmeister** [comment]
> > restrictions
> 
> The default is `[]`, isn't it? Maybe we should fix the client to treat `null` as `[]` here.

We should probably do both: Fix the client to handle `null` and set a default in the backend (we need the ability to set defaults anyway, so this will be done anyway).

**Comment by jsangmeister** [comment]
> 3\. css_colors

@GabrielInTheWorld the field `css_colors` doesn't exist, do you mean `css_class`? Since that's a string I would suggest to just handle `null` the same as `""` in the client and not set a default value here.

**Comment by FinnStutzenstein** [comment]
Just a little remainder: Some field names changed from OS3->OS4 and maybe I missed some renaming in the client (@GabrielInTheWorld please just rename the property if you find wrongly named properties). `css_class` is correct: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L529

**Comment by jsangmeister** [comment]
Added defaults for `merge_amendment_into_final` and `restrictions`. This should suffice for now
