### ISSUE TITLE
Convert default projectors to list

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1580]
The field `default_projector_$_id` sets for each defined type the projector which is selected by default in the client if a matching object is projected. This should be converted to a list to be able to select multiple projectors by default.

TODOs:
- convert field to list
- adjust code which relies upon it being a single field
- adjust tests
- write migration to convert all existing default projectors to a list

**Comment by jsangmeister** [comment]
And yes, I'm aware that this clashes a little with the effort to remove template fields completely - but not much, and this is a relatively easy feature which can be implemented quickly, in contrast to the template field removal.

**Comment by reiterl** [comment]
@jsangmeister  How should I update the `meeting.replace_projector_id` internal action?

**Comment by reiterl** [comment]
idea: replace the projector_id in the lists with the reference_projector_id.

**Comment by jsangmeister** [comment]
> idea: replace the projector_id in the lists with the reference_projector_id.

Yes, and maybe enhance the action to be able to handle multiple projectors.
