### ISSUE TITLE
Fix commented-out xtests

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#161]
The tests are `xtest_O2O_replace` and `xtest_generic_O2O_replace`. Please look into this @normanjaeckel

**Comment by normanjaeckel** [comment]
I enhanced the error message with #173.

The behavior seems correct. If you have an existing one to one relation between A and B you can not just try to update C and establish a relation to B. First you have to get B (and A) free.

The RelationHandler was not build to provide such cascading effects (try to update B; if it is not empty, unbound also A). Of course we can implement this but we should first think if this feature is necessary.

**Comment by normanjaeckel** [comment]
Here we have all one to one relations:

```
organisation/superadmin_role_id    <----->    role/superadmin_role_for_organisation_id
role/superadmin_role_for_organisation_id    <----->    organisation/superadmin_role_id
committee/template_meeting_id    <----->    meeting/template_for_committee_id
committee/default_meeting_id    <----->    meeting/default_meeting_for_committee_id
meeting/template_for_committee_id    <----->    committee/template_meeting_id
meeting/motions_default_workflow_id    <----->    motion_workflow/default_workflow_meeting_id
meeting/motions_default_amendment_workflow_id    <----->    motion_workflow/default_amendment_workflow_meeting_id
meeting/motions_default_statute_amendment_workflow_id    <----->    motion_workflow/default_statute_amendment_workflow_meeting_id
meeting/default_meeting_for_committee_id    <----->    committee/default_meeting_id
meeting/reference_projector_id    <----->    projector/used_as_reference_projector_meeting_id
meeting/default_group_id    <----->    group/default_group_for_meeting_id
meeting/superadmin_group_id    <----->    group/superadmin_group_for_meeting_id
group/default_group_for_meeting_id    <----->    meeting/default_group_id
group/superadmin_group_for_meeting_id    <----->    meeting/superadmin_group_id
motion_state/first_state_of_workflow_id    <----->    motion_workflow/first_state_id
motion_workflow/first_state_id    <----->    motion_state/first_state_of_workflow_id
motion_workflow/default_workflow_meeting_id    <----->    meeting/motions_default_workflow_id
motion_workflow/default_amendment_workflow_meeting_id    <----->    meeting/motions_default_amendment_workflow_id
motion_workflow/default_statute_amendment_workflow_meeting_id    <----->    meeting/motions_default_statute_amendment_workflow_id
projector/used_as_reference_projector_meeting_id    <----->    meeting/reference_projector_id
```

**Comment by normanjaeckel** [comment]
Hm. I think we need a short and easy way to unbound an old an set a new one to one relation in cases where at least the field which is set to `None` is not a required field.

**Comment by jsangmeister** [comment]
I looked into this again. We would need a specific `1:1` relation for this to become a problem. Currently, I found the following `1:1` relations in the models:
- agenda_item, LOS
- workflow.first_state_id <-> state.first_state_of_workflow_id
- default workflow ids
- projector.used_as_reference_projector_meeting_id <-> meeting.reference_projector_id
- organisation.superadmin_role_id <-> role.superadmin_role_for_organisation_id
- committee.template_meeting_id <-> meeting.template_for_committee_id
- committee.default_meeting_id <-> meeting.default_meeting_for_committee_id
- group.default_group_for_meeting_id <-> meeting.default_group_id
- group.superadmin_group_for_meeting_id <-> meeting.superadmin_group_id
They all have in common that there is one "parent" item, which handles all updates. To run into a problem, there would need to be a situation where a "child" item is updated to a parent, which already has a child assigned, e.g. setting the `first_workflow_id` from the `state`-side. Since this is currently not the case, I think we can close this for now and keep it in mind in case such a case ever comes up (which I doubt if it did not appear yet).
