### ISSUE TITLE
Validate `{organization|meeting}.users_email_sender`

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1621]
In https://github.com/OpenSlides/openslides-backend/blob/d2006f6432a68af1d5d90d567903b68343c68d53/openslides_backend/action/actions/user/send_invitation_email.py#L169, we have a blacklist for the allowed sender names. These should be enforced in the related update actions.

**Comment by reiterl** [comment]
Should that blacklist code be in `EmailCheckMixin`? Or is that independent of the valid email check?

**Comment by jsangmeister** [comment]
> Should that blacklist code be in `EmailCheckMixin`? Or is that independent of the valid email check?

It is independent of the email validity check since this is about the sender name instead of an email address, but it can still be moved to the mixin.
