### ISSUE TITLE
remove template fields: update `user.create` and `user.update`

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#1631]
The actions `user.create` and `user.update` should be improved. The payload of these actions should include the template fields without `$` and a meeting_id. The content of these fields should be the plain flat content. The meeting id sets the meeting for the field. E.g. `"number_$": {"1": "bla"}` becomes `"number": "bla", "meeting_id": 1`.

There should be an internal action `meeting_user.create_or_update`, which should be called from the user actions and which calls the meeting_user actions, depending on the existence of the meeting_user.

Development of this feature should be in the feature/remove_template_fields branch.

**Comment by reiterl** [comment]
I think, we should start this issue, after the merging of the remove template fields feature branch and after the group_ids template field removal.

**Comment by reiterl** [comment]
The internal action should be a `create_or_update_or_delete` action. It should remove an existing meeting_user, if the group_ids are empty.

**Comment by jsangmeister** [comment]
Maybe use another name, like `set_data` or `manage`? `create_or_update_or_delete` is really verbose...

**Comment by reiterl** [comment]
Okay, I will use `set_data`.
