### ISSUE TITLE
Migration: Remove user default projector

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1642]
The replacement `user` was removed from `default_projector_$_ids`, but we still need a migration for this (only relevant for imports, which are currently failing since they detect an invalid replacement). A simple `DeleteFieldMigration` should suffice which removes `default_projector_$user_ids`.

**Comment by reiterl** [comment]
I will use a `RemoveFieldsMigration` and ignore the reverse field.
