### ISSUE TITLE
Allow iframe in topic items

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-backend#1646]
There is a request https://github.com/OpenSlides/openslides-client/issues/1927 to allow iframes in topic items. This would give the user the ability to add videos for example. Currently iframe tags are filtered. 
Instead of filtering them for topic items the attribute `sandbox="allow-scripts allow-same-origin"` could be added if it is not too much of a hassle.

**Comment by jsangmeister** [comment]
We have multiple options, as I see it:
- We could enhance the `HTMLPermissiveField` to allow iframes and insert the required attributes. Its only other use is for `meeting/welcome_text`.  Someone has to determine if it's okay to insert iframes there as well or if that should only be the case for `topic/text`.
- We could introduce a new field type, like `HTMLIframeField`, and implement the functionality there. This, however, would require also introducing this field in the `models.yml`, which I don't particularily like - this is backend-internal functionality and does not need to be reflected in the `models.yml`.
- We could introduce the functionality to add custom code for specific fields during model generation (which we already do for specific models) and add an attribute there indicating that iframes are allowed. I think this would be my favourite approach.

Regarding the adding of the attributes: I found no bleach-inherent way to do this, but I think that after the sanitation you can just use string replacement to replace `<iframe` with `<iframe sandbox="allow-scripts allow-same-origin"` - after the sanitation, every `<...>` should represent an actual html tag.

**Comment by reiterl** [comment]
@rrenkert I think, we should go point 1. . Can you discuss, if `iframe` should be allowed in the welcome text of a meeting ,too?

**Comment by rrenkert** [comment]
@reiterl Yes, I agree to go with option 1. You already implemented it this way in the linked PR, thanks!
