### ISSUE TITLE
Error when creating models with structured relations

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#165]
Example in https://github.com/reiterl/openslides-backend/blob/d4aa3a041c08dec7594397179fc31b5af40a8698/tests/system/action/motion_submitter/test_create.py#L11 (checkout @reiterl's branch to test). When searching the structured relation, the model is fetched from the DB. In a create action, this obviously fails.

**Comment by normanjaeckel** [comment]
Ok I understood the problem. @reiterl Please rebase your branch on top of current master (and adopt to new models.py). Then I can try to provide a patch for the RelationsHandler that in create case the structured relation has to be searched inside the payload first.

**Comment by reiterl** [comment]
Rebased the dev_motion_submitter branch on top of master.

**Comment by jsangmeister** [comment]
Fixed in #179
