### ISSUE TITLE
[imports] Relocate csv imports to the backend: topic

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1661]
The steps to go:
1. Client reads the import csv-file and converts it to json format
2. New backend-action topic.json_upload will be called with file content
3. The backend creates data for preview and send the preview data with the response and an action-worker number for starting the import or abort it. The data will be stored in these action-worker instance. Preview data format will be defined by the client, but should be sufficient to do the import. For existing preview-format we need additionally fields per line check-result (ok or not ok) and in case of not ok need an errortext. There also remarks for the whole import and the number of lines. Error checks see above.
4. The client presents the preview and calls the 2nd new action topic.json_import. The payload needs the action_number, where the data is stored and the command "import" or "abort".
5. The backend will import or delete the json-data from specified action-worker instance.

Special themes:
1. we want to use the action worker, because there is no need to create events and other stuff with file content on an extra route.
2. Converting from csv to json in the client should be made without knowing specified formats just from a standard lib. Json format is the standard format of all backend-payloads we will keep.
3. We should think about dangling "import"-action-workers with content to delete.

Error checks:
- Title has to be unique in one agenda
-  Hint: Missing columns will be reported as missing and imported as empty column
-  required fields are define in import
-  @luisa-beerboom : Are there more checks?

Existing import can be seen in meeting under agenda, menu button .

**Comment by luisa-beerboom** [comment]
>     Preview data format will be defined by the client, but should be sufficient to do the import.

I've taken a vague look over the clients `ImportListComponent`, I'm not quite sure on the exact form of the data that the client uses to generate the preview list (although that exact format would of course be the most helpful): But I believe it would look vaguely like this: We need to know:

- per column
    - What type of data is saved here (boolean, number, string, ...)
    - What is the column property
    - What is the column label
- per row
    - What will happen with this row? will it be...
        - imported
        - skipped because it is a duplicate
        - referenced
        - skipped because of an error
- per entry
    - what is the content
    - is there an error/warning with this fields content? Which one?
    - if the column is a reference to another model, will it be generated anew from this field

The client data seems to be mainly made up of two interfaces:
```
interface HeaderDefinition<ToCreate> {
    label: string;
    property: key of ToCreate;
    type?: `boolean` | `string` | `number`;
    isRequired?: boolean;         // Probably not necessary
    isTableColumn?: boolean;  // Probably not necessary
    width?: number;                   // This is the css column width, should maybe be done by the backend
}
```
and an Array of the clients `ImportModel` class (`import-model.ts`), with the basic build: 
```
class ImportModel<ToCreate>{
   status: 'new' | 'error' | 'done' | string
   errors: string[]
   model: ToCreate // The model that is to be created, i.e. a dictionary of all the data from the csv
   importTrackId: number // Pretty sure it just assigns a number to each row, maybe unnecessary
   ...
}
```

We may want to send a preview in a form such as:
```
{
   action_worker_id: number
   header_definition: HeaderDefinition<Topic>[]
   rows: ImportModel<Topic>[]
}
```


Don't know how to incorporate field errors into that

>     * @luisa-beerboom : Are there more checks?

- is an entry for a field the correct type/can it be converted to the correct type?
   - f.e in the original csv 0 and 1 may be interpreted as false and true in boolean fields

**Comment by jsangmeister** [comment]
I'm not sure I'm a fan of misusing the action worker for this. Would it really be that bad to just send the data twice, once for the preview action and once for the actual import action?

**Comment by jsangmeister** [comment]
Talked with @r-peschke and we agreed that the action worker is the best solution for now.

**Comment by reiterl** [comment]
Some questions:

* What does the client in the convert csv to json step do? Json is a lot, we need a clear interface here.
* How can I access the action_worker via the normal action code?
* Does the action worker have actions to save the data into it?
* What is a *preview*? I don't know the user interface of the client here. What kind of information does the client need?

**Comment by reiterl** [comment]
Talked with @r-peschke  about these 4 questions.
For question 1. and 4. I will look at a client demo. And for question 2.+3. I will look at the action/action_worker.py and the code there.

**Comment by r-peschke** [comment]
@jsangmeister Is there a datastore.command to remove a row from models? We'll need for action_workers with import-data.

**Comment by luisa-beerboom** [comment]
**JSON_UPLOAD:
For statistics: How about the following?**
```
statistics: {
   total: number
   <name-of-model>: {
      created: number
      updated: number
   }
}
```
Should be more reusable for other imports that may import multiple different models

**Example:**
```
statistics: {
   total: 5
   topic: {
      created: 3
      updated: 2
   }
}
```

**Comment by jsangmeister** [comment]
Why do we keep it this generic? We know which fields a topic import can have, so I think the whole `headers` and `rows` spiel is unnecessary. I would suggest to just return the import data with additional fields `status` and `error` (could maybe even be merged into one) and the client can have a mapping from field names to types, if necessary, or can just just the model definitions. What do you think @luisa-beerboom?

Also, I think the `statistics are unnecessary. While processing each entry to display it to the user, the client can just count how many creates, errors and merges there are.

**Comment by jsangmeister** [comment]
> @jsangmeister Is there a datastore.command to remove a row from models? We'll need for action_workers with import-data.

There is no such command, but I think we don't need it. The `abort` command will not be used very often, I think - if a user tries an import and then changes his mind, he will most likely just navigate away or reload. I think an automatic regular cleanup of all action workers which are older than a fixed time interval (e.g. 1-2 weeks) is more suitable and reliable.

**Comment by r-peschke** [comment]
> Why do we keep it this generic? We know which fields a topic import can have, so I think the whole `headers` and `rows` spiel is unnecessary. I would suggest to just return the import data with additional fields `status` and `error` (could maybe even be merged into one) and the client can have a mapping from field names to types, if necessary, or can just just the model definitions. What do you think @luisa-beerboom?
> 
The client should be only responsible for the layout and the backend for the implementation logic.
 
> Also, I think the `statistics are unnecessary. While processing each entry to display it to the user, the client can just count how many creates, errors and merges there are.
If the client doesn't know the logic, it isn't able to do the summary

**Comment by r-peschke** [comment]
> **JSON_UPLOAD: For statistics: How about the following?**
> 
> ```
> statistics: {
>    total: number
>    <name-of-model>: {
>       created: number
>       updated: number
>    }
> }
> ```
> 
> Should be more reusable for other imports that may import multiple different models
> 
> **Example:**
> 
> ```
> statistics: {
>    total: 5
>    topic: {
>       created: 3
>       updated: 2
>    }
> }
> ```

In such cases we could also use 
```
statistics: {
  total: 5
  topics created: 3
  topics updated: 2
}
```
it's simpler without nesting

**Comment by jsangmeister** [comment]
> The client should be only responsible for the layout and the backend for the implementation logic.

Yes, but the client can deduce the layout from the model without knowing the implementation logic. If the return value is e.g.
```
[{
  "title": "xy",
  "agenda_duration": 30,
  "status": "new"
  ...
}, ...]
```
for a topic import, then the client can deduce all information from the existing model code, without any need for the generic output currently described in the wiki.

> If the client doesn't know the logic, it isn't able to do the summary.

Well, the client has to know _some_ logic, at least the meaning of the stati, because it has to interpret and display them differently. And then, the statistic can be done in the client.
