### ISSUE TITLE
Expand theme model with poll colors and global headbar color

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1671]
Backend pendant to OpenSlides/openslides-client#279

The `theme` model should get 4 new color fields that one should optionally be able to set via the `theme.create` and `theme.update`:
- `headbar`: The color for the global headbar
- `yes`, `no`, `abstain`: The colors for the poll vote options

It should be possible to leave all of these empty, in which case the client would have to substitute whatever it currently already uses as a default value

**Comment by jsangmeister** [comment]
Setting these via the poll actions seems very critical to me: This means that anyone with the right to create polls in __any__ meeting can change the colors of __every__ poll in __every__ other meeting. Do we really want that? 

My suggestion would be to either only make the fields editable by orga managers (like the other fields) or to additionally add `{yes|no|abstain}_color` fields to the poll model, which can then be used to overwrite the global ones on a per-poll basis without affecting all other polls.

**Comment by luisa-beerboom** [comment]
> Setting these via the poll actions seems very critical to me: This means that anyone with the right to create polls in **any** meeting can change the colors of **every** poll in **every** other meeting. Do we really want that?

No we don't want that, I seem to have accidentally written `poll.create` and `poll.update` instead of the correct theme action names which I intended to write. Ofc the permissions needed should also be the same ones as are already used for `theme.create` and -`update`.

I have corrected the original description, sorry about that!

**Comment by jsangmeister** [comment]
@rrenkert you wanted to talk to @emanuelschuetze about this and seem to have forgotten to write here and now it is organisation-wide instead of meeting wide. Please decide if we still want the colors to be set per meeting, then @reiterl has to change his PR.

**Comment by jsangmeister** [comment]
Discussed and we will need a orga-wide default. It can be decided later if we additionally want to have a meeting-level override.
