### ISSUE TITLE
Actions for SSO: user.create_saml_account and update.saml_account

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1694]
Actions for creating and updating users for single-sign-on.
See action description https://github.com/OpenSlides/OpenSlides/wiki/user.create_saml_account and https://github.com/OpenSlides/OpenSlides/wiki/user.update_saml_account

**Comment by reiterl** [comment]
The new user update action seems to be: https://github.com/OpenSlides/OpenSlides/wiki/user.update_saml_account

**Comment by reiterl** [comment]
The fields `saml_id` and `single_sign_on_only` don't exist in the model. What kind of fields are they? What restriction mode should they have? etc.

**Comment by jsangmeister** [comment]
Do we want to have two fields for that? I would argue that either the combination of ("SAML ID as username" + boolean flag like `is_saml_user`) or only the `saml_id` as an additional field should suffice - `single_sign_on_only` will be only true iff a `saml_id` is set.

Should the user groups also be managed via SAML? At least in OS3 this was a requirement.

**Comment by r-peschke** [comment]
> The new user update action seems to be: https://github.com/OpenSlides/OpenSlides/wiki/user.update_saml_account

yes, changed in first comment

**Comment by r-peschke** [comment]
> Do we want to have two fields for that? I would argue that either the combination of ("SAML ID as username" + boolean flag like `is_saml_user`) or only the `saml_id` as an additional field should suffice - `single_sign_on_only` will be only true iff a `saml_id` is set.
>
Usually all users are SSO-Users, single_sign_on_only = True is the default. SUPERADMIN as Intevation user will never be a SSO-User. SSO and local user may be the exception, if for instance a user has to be add to a meeting.  
> Should the user groups also be managed via SAML? At least in OS3 this was a requirement.

**Comment by jsangmeister** [comment]
> Usually all users are SSO-Users, single_sign_on_only = True is the default. SUPERADMIN as Intevation user will never be a SSO-User. SSO and local user may be the exception, if for instance a user has to be add to a meeting.

I'm not sure I understand you comment or how that answers mine. I was under the assumption that the differentation between "SSO" and "normal" user is primarily for the auth method used and has no limitations on the actual behaviour of the user (except maybe for changing the fields which are synced from the IDP). So, a SSO user can be added to meetings just like a normal user.

> Usually all users are SSO-Users, single_sign_on_only = True is the default.

I'm assuming you mean that if an instance uses SSO, then almost all users will be SSO users? But what does that have to do with the modelling? We will still have both types of users and the question is how we can effectively model the functionality.

**Comment by r-peschke** [comment]
> The fields `saml_id` and `single_sign_on_only` don't exist in the model. What kind of fields are they? What restriction mode should they have? etc.

string and bool, Mode A

**Comment by jsangmeister** [comment]
Updated https://github.com/OpenSlides/OpenSlides/wiki/user.create_saml_account
