### ISSUE TITLE
Write into template fields

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#170]
Does the client wants to write into template fields directly? At the moment the backend does not support e. g. adding a new motion to `user/42/supported_motion_123_ids` via the user model. This operation is possible via the motion model of course (to add an new supporter which is then correctly related by the backend, see #169.

If yes: Are there just a handful of cases like logo and font files?
If yes: I propose NOT to implement a generic solution for all structured fields at the moment because this is kind of hard work we do not need now.

**Comment by jsangmeister** [comment]
At least for users: We need to write `group_$<meeting_id>_ids` in a `user.update`. This is especially tricky since we do not have a meeting id for the user (at least if it's not a temporary user).

I guess there are more of these cases so we should find a generic solution.

**Comment by FinnStutzenstein** [comment]
Mostly not. For logos/fonts there are the `set_as_logo`/`set_as_font` actions. All structured relations for users are written from the other side, except for the relations to groups (and vote delegation will also be structured, this is a new feature). The amendment paragraphs are structured, but no relation is assigned.

**Comment by normanjaeckel** [comment]
So we will NOT provide a generic solution at the moment and will see in the future.

**Comment by normanjaeckel** [comment]
With #195 I think we are in a good way to implement all special cases if required. No more work here at the moment.
