### ISSUE TITLE
Pronoun field needs a shorter character limit

### ISSUE THREAD

**Issue by colinmahns** [OpenSlides/openslides-backend#1701]
Our user-base discovered there's a 256 character length limit for the pronoun field, causing issues where names clip off screen on the speaker list and in the participants page. This is much more disruptive when it's unicode or emojis which can take over the screen. 

I'm not sure what the "right" length for this is but maybe shortening this to be in the ~32 character range would allow for several combos of pronouns without full names being clipped off the screen. 

Example below:

![Screenshot from 2023-04-15 15-51-52-edited](https://user-images.githubusercontent.com/1781677/232324789-f8616e28-9310-4f2e-bca3-09148030fd9d.png)

**Comment by jsangmeister** [comment]
We need to implement a new field type in the `models.yml`, maybe something like `short_string`? I'm open for suggestions. This needs to also be implemented in the backend with a character limit of 32. The pronoun field should be of the new type.
