### ISSUE TITLE
Fill calculated fields of sortable objects

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#171]
We have a lot of calculated fields that have to be filled in some actions. E. g. some sortable have the field `level` which has to be calculated.

@reiterl Do you like to try this?

**Comment by jsangmeister** [comment]
I guess we should gather a concrete list here, or else we'll miss something. Maybe with links to the corresponding OS3 parts?

**Comment by reiterl** [comment]
We need a way to update children of a modified instance. So we can calculate the fields. An example would be  `level`.
I'm not sure how this way should look like and where to add it. I think update_instance is not the right place.

**Comment by jsangmeister** [comment]
Added this way in https://github.com/OpenSlides/openslides-backend/pull/238: with `get_updated_instances` you can add all children to the updated instances with the updated calculated field.

**Comment by jsangmeister** [comment]
@FinnStutzenstein or @normanjaeckel: can you provide a list of fields which have to be calculated and when that happens?

**Comment by FinnStutzenstein** [comment]
- `is_hidden`, `is_internal`, `weight`, `level` for angeda_item
- `sort_weight` for motion (sorting via `sort_parent_id`)
- `weight`, `level` for motion_category
- `has_inherited_access_groups` for mediafiles (the name has still to be changed in the models.yml)

**Comment by jsangmeister** [comment]
> * `is_hidden`, `is_internal`, `weight`, `level` for angeda_item

See https://github.com/OpenSlides/openslides-backend/issues/172 for the first 2. `weight` and `level` are done.

> * `sort_weight` for motion (sorting via `sort_parent_id`)

Should be done, has a default value and ist set in `motion.sort`.

> * `weight`, `level` for motion_category

Should be done, `weight` has a default value and ist set in `motion_category.sort`. `level` handling is still missing -> @reiterl can you implement this? Should be analogous to `agenda_item`.

> * `has_inherited_access_groups` for mediafiles (the name has still to be changed in the models.yml)

Will not be renamed and is done. (Almost, except `mediafile.move`, see https://github.com/OpenSlides/openslides-backend/pull/322

So, only thing missing is `level` for `motion_category`, or am I wrong?

**Comment by normanjaeckel** [comment]
Maybe ...

**Comment by reiterl** [comment]
agenda_item sort doesn't set level. Is this missing too?

**Comment by jsangmeister** [comment]
> agenda_item sort doesn't set level. Is this missing too?

Yes; I thought it did.

**Comment by jsangmeister** [comment]
#333 (level handling) is merged, so everything should be done now, if i didn't miss something.
