### ISSUE TITLE
[imports] Relocate csv imports to the backend: Participants (users in meetings)

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1714]
- First todo: create the wiki doku for participants json upload and import in feature/rtf branch;-)
- columns from client import: title, first_name, last_name, email,pronoun, gender, username, default_password, is_active, is_physical_person and in meeting_user: structure_level, number, vote_weight
- Matching username, [first_name, last_name, email must all match]. On match done, else create
- permissions analogue to the user.create and user.update actions. In case of user update, remove fields from payload, that don't change the content compared to database for avoiding unnecessary permission errors. Don't forget the special permissions for default_passwort on user.update.
- Return row  `error` on missing permission **from or like** user.create or user.update.

**Comment by jsangmeister** [comment]
In the client, the `presence` status is currently ignored. This should be kept in mind when implementing this and should tested. Also see https://github.com/OpenSlides/openslides-backend/issues/1710

**Comment by reiterl** [comment]
This doesn't seem to be the final saying to this issue. I miss the handling of the meeting and the groups.
The permission description seems boggus. We need to clearly define which permissions are needed.
What is this saml_id?
I dont understand the matching user conditions. Which fields should be used for the matching? I would say username.

**Comment by jsangmeister** [comment]
Wiki pages updated:
- https://github.com/OpenSlides/OpenSlides/wiki/without_templ.participant.json_upload
- https://github.com/OpenSlides/OpenSlides/wiki/without_templ.participant.import
