### ISSUE TITLE
Uploading PDFs is failing silently

### ISSUE THREAD

**Issue by markusblogde** [OpenSlides/openslides-backend#1717]
docker logs openslides-backendAction-1 shows the following:

File "/usr/local/lib/python3.10/site-packages/pypdf/_encryption.py", line 147, in decrypt
    raise DependencyError("PyCryptodome is required for AES algorithm")

OpenSlides Version: 4.0.1-main-20230424-19b6cce

**Comment by jsangmeister** [comment]
Can you provide an example file where that happens? I tried it with an encrypted and a normal pdf and could not replicate the error.

**Comment by jsangmeister** [comment]
seems like https://github.com/OpenSlides/openslides-backend/pull/1720 should fix your problem!
