### ISSUE TITLE
Fill calculated fields for agenda item

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#172]
Agenda items have the fields `is_internal` and `is_hidden`. The OpenSlides 3 logic has to be implemented here to fill these calculated fields on create and update action.

https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/agenda/models.py#L311

When sorting the agenda these fields have to be recalculated. The same if any agenda item is updated in the type field.

**Comment by jsangmeister** [comment]
@reiterl This should be suited for you

**Comment by jsangmeister** [comment]
Care to not make too many requests, e.g. when the type is changed in an `agenda_item.update`, you only have to recalculate the fields for all children of it.

**Comment by reiterl** [comment]
I don't have a solution for the way to update children.

**Comment by jsangmeister** [comment]
You should be able to work on this now

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/pull/276 for the agenda_item.create action.

**Comment by FinnStutzenstein** [comment]
I just saw this issue: `level` is also calculated and must be updated.

**Comment by reiterl** [comment]
Add `level` calculation in the create Action of agenda_item.

**Comment by jsangmeister** [comment]
create case is fine, update case is still missing

**Comment by jsangmeister** [comment]
Done with #320
