### ISSUE TITLE
[feature/remove-template-fields] Some field renames

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1737]
While writing the migration, I have noticed a few fields which are named confusingly or irregularly (I'm always referring to the new names in the `feature/remove-template-fields` branch):
- The fields `logo_pdf_{header|footer}_{l|r}_id` should be more verbose: `logo_pdf_{header|footer}_{left|right}_id`. These are the only instance I'm aware of where we use abbreviations in field names.
- The `default_projector_*_ids` should be name `default_*_projector_ids`, since otherwise it looks like the `ids` suffix pluralizes the replacement instead of the projectors, although this might just be personal preference.
- `default_projector_projector_countdowns_ids` has a plural replacement ("countdown**s**"), while all others have a singular one (except `default_projector_agenda_all_items_ids`, which has to be plural).
- `default_projector_projector_{message|countdowns}_ids` unnecessarily duplicate the word `projector`, probably because the collections are named like that. Since we do not have other messages or countdowns in OS4, this information is redundant and looks confusing, so we should remove it.
- I'm not sure why `default_projector_agenda_all_items_ids` is named like that, where does the `all` come from and does it have any meaning? If not, we should just remove it and call the field `default_projector_agenda_item_ids`.
- `motion/amendment_paragraph` should be pluralized, since it contains all paragraphs and not only one: `motion/amendment_paragraphs`

**Comment by r-peschke** [comment]
Remark: Postgres has a limit of 63 bytes for column names, we want to use in a relational system. This could be increased by recompiling Postgres, but IMO we shouldn't even think about it.
Therefore we may have to shorten names like  `used_as_default_projector_for_current_list_of_speakers_in_meeting_id`.
IMO we should use shorter names with obvious abbreviations, I don't like long names about 30 or 40 bytes. In this case we could use explanations/description or something similar to explain the meaning of the field, what we IMO need in some cases.

> * The fields `logo_pdf_{header|footer}_{l|r}_id` should be more verbose: `logo_pdf_{header|footer}_{left|right}_id`. These are the only instance I'm aware of where we use abbreviations in field names.
> 
IMO no need to change.

> * The `default_projector_*_ids` should be name `default_*_projector_ids`, since otherwise it looks like the `ids` suffix pluralizes the replacement instead of the projectors, although this might just be personal preference.
> 
All the default projector-fields begin with `default_projector`  and we should keep it.

> * `default_projector_projector_countdowns_ids` has a plural replacement ("countdown**s**"), while all others have a singular one (except `default_projector_agenda_all_items_ids`, which has to be plural).
> 
lets remove the `s` from countdowns

> * `default_projector_projector_{message|countdowns}_ids` unnecessarily duplicate the word `projector`, probably because the collections are named like that. Since we do not have other messages or countdowns in OS4, this information is redundant and looks confusing, so we should remove it.
> 
okay

> * I'm not sure why `default_projector_agenda_all_items_ids` is named like that, where does the `all` come from and does it have any meaning? If not, we should just remove it and call the field `default_projector_agenda_item_ids`.
>
I meant to remember that there was another default_projector_agenda_items ..., but couldn't find it. Then let's remove the all.
 
> * `motion/amendment_paragraph` should be pluralized, since it contains all paragraphs and not only one: `motion/amendment_paragraphs`
okay
