### ISSUE TITLE
Presenter for external_id's to get the id and user.create change

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1776]
4 new presenters, each with one field for look up and returning the`id` or None, if not found with a message. Needed permission: organization "can_manage_organization". 
- committee.external_id
- meeting.external_id
- group.external_id
- user.saml_id

Action change
-  Action user.create: add field saml_id, backend permission group E with OML.can_manage_users, Analogue to user.update: If saml_id is set in payload, there may be no password or default_password set or generated and the set_change_own_password will be set to False.

First todo: Update action description and create presenter docs

**Comment by jsangmeister** [comment]
We could combine them into on presenter `get_external_id` which takes an FQID as the parameter to unify the handling. Only internal differentation between the cases is whether to fetch `saml_id` or `external_id`, which can easily be decided based on the collection.

**Comment by r-peschke** [comment]
> We could combine them into on presenter `get_external_id` which takes an FQID as the parameter to unify the handling. Only internal differentation between the cases is whether to fetch `saml_id` or `external_id`, which can easily be decided based on the collection.

good idea for technical realization :-)

**Comment by reiterl** [comment]
What permission check should the `search_for_id_by_external_id`  logic include?

**Comment by reiterl** [comment]
Added wiki entry for saml_id and user.create
