### ISSUE TITLE
Fix presenter get_user_related_models

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1795]
The doc of this presenter and the realization differ a lot:
- manager in organization is never mentioned
- beeing member in a meeting is only shown, if the user was active as speaker, submitter or candidate. On all other participations like voting, group-member, ... not even the membership in a meeting is shown

To take a decision (automatically/manually) whether a user could/should be deleted at all, this behavior is not useful.

see also #1792

**Comment by rrenkert** [comment]
For the decision if a user should be deleted or removed from a meeting the only information necessary for the client is if the user is member of a group in _any_ meeting (archived or not). Participation is like voting, or activity as speaker, submitter and so on is nice to have.
The deletion of an orga admin should be avoided via user scope, should it?

**Comment by jsangmeister** [comment]
Updated https://github.com/OpenSlides/OpenSlides/wiki/get_user_related_models. OML was already mentioned beforehand and there is now no remark that meetings should be excluded.
