### ISSUE TITLE
Add setting to close LOS for point of orders

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1826]
Currently, if a LOS is closed, point of orders can still be created. We now need a setting to control this behaviour, since some organizations want to keep this behaviour and some want a closed LOS to be closed completely, even for POOS. A suggestion for the name would be `meeting/list_of_speakers_restrict_point_of_order_submissions_to_open_lists`. If we formulate the setting negated like this, the default value will be `false` and we save ourselves the migration. But I'm open for other suggestions.

Things to do:
- add the new setting to `meeting.update`
- check the new setting in `speaker.create` and prevent the creation of new point of orders speakers, if it is enabled
- add tests for this

**Comment by jsangmeister** [comment]
> * `meeting/list_of_speakers_restrict_point_of_order_submissions_to_open_lists` <- I personally like this one

Sounds good, then let's go with that one. I'll change the description above

**Comment by jsangmeister** [comment]
We have to choose a shorter name. From the [postgres manual](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS):

> The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

So unless we want to compile postgres ourselves, we are restricted to 63 characters. Interestingly enough, the limit is only enforced in syntax identifiers, meaning a JSONB object with a field name that's too long will get saved to the DB without problems since the field name is only inside the blob and no syntax identifer. When fetching the object from the datastore and NOT providing mapped fields, again everything works without problems: The full JSON blob gets returned with the full field name. Unfortunately, most of the time, models fields are accessed _with_ mapped fields. This is where the truncation happens because now the field name is used as a syntax identifier in the query in the `AS` part: https://github.com/OpenSlides/openslides-datastore-service/blob/069b5b27df09f0b4965539c81c75c276507d08e6/datastore/shared/postgresql_backend/sql_query_helper.py#L55

@reiterl this is also why the error did not show up in the tests when accessing the model via `get_model()`.

So, from your other suggestions, I think I would favor `list_of_speakers_closing_disables_point_of_order`. What do you think?

**Comment by peb-adr** [comment]
Wouldn't we need a migration for this too - to add the new field to all relevant events?
@jsangmeister @reiterl

**Comment by reiterl** [comment]
No, we wont need a migration here, the field is a default False field.
