### ISSUE TITLE
New default for users_pdf_wlan_encryption

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1862]
The default for the meeting field `users_pdf_wlan_encryption` should be set to `WPA`

This requirement was defined in [this comment](https://github.com/OpenSlides/openslides-client/pull/2444#pullrequestreview-1571619279)

**Comment by reiterl** [comment]
Do we need a migration for this?

**Comment by reiterl** [comment]
Talked with @rrenkert in the daily about the migration: We don't need a migration, because we don't want to modify existing meetings.
