### ISSUE TITLE
Support readding point of order speakers

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-backend#1892]
It should be possible to readd the last speaker even if it is a point of order speaker. 

Corresponding client issue: [#2715](https://github.com/OpenSlides/openslides-client/issues/2715)

**Comment by jsangmeister** [comment]
Should it be readded as a PoOS, with the same category etc.?

**Comment by reiterl** [comment]
The action is `list_of_speakers/re_add_last`. It has a check for point of order in it, which leads to the `ActionException`.

**Comment by Elblinator** [comment]
It should be readded as normal contribution, not as a PoO.

**Comment by jsangmeister** [comment]
> The action is `list_of_speakers/re_add_last`. It has a check for point of order in it, which leads to the `ActionException`.

Yes, that should be changed so the speaker is readded as a normal speaker.

**Comment by jsangmeister** [comment]
The behaviour should be the same for PoO and non-PoO speakers: They are moved to the first position of the queue, as normal speakers. This means that for PoOS the PoO related fields must be removed.
