### ISSUE TITLE
Replace get_all by filter in migrations

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#1906]

**Comment by rrenkert** [comment]
As seen in #1910 that's not always a good idea. Filter also returns deleted models which causes problems in update events.

**Comment by jsangmeister** [comment]
This can be prevented by using `And(FilterOperator("meta_deleted", "=", False), ...)`. Missed this during the review.

**Comment by rrenkert** [comment]
This is implemented in #1910.
