### ISSUE TITLE
Automatize "same-meeting" check

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#191]
We have to do the check whether another model is in the same meeting as the current object for almost all foreign keys (e.g. `agenda_item.parent_id`, `motion.parent_id`, `motion.lead_motion_id`, ....). I suggest we automate this by passing a flag a lá `same_meeting=True` to a relation field and then automate the check. I would further suggest for easier access and implementation that we should make the `meeting_id` a required field on all meeting-based models (as discussed previously in https://github.com/OpenSlides/OpenSlides/issues/5588). This way, we don't need to implement `through` fields here also and we can get rid of the ones we already have, if we want.

What do you think? I can implement this if nobody has objections.

**Comment by normanjaeckel** [comment]
The `through` way is cleaner but I am not against any change to get rid of it if you like.

Using such a flag to check the same meeting id sounds good.

**Comment by FinnStutzenstein** [comment]
> we should make the meeting_id a required field on all meeting-based models

I would prefer that regarding unity: Going this way, the logic is always the same.
