### ISSUE TITLE
Add enum to `import_preview/name`

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1920]
As suggested in https://github.com/OpenSlides/openslides-autoupdate-service/pull/781, we should constrain the values of this field with an enum to ensure only valid import names are entered. Also, I think that `type` would be more fitting as a field name.

**Comment by r-peschke** [comment]
The backend json-uploads and imports are each individual actions and each one uses and tests the name field-content individually. Therefore an enum doesn't help. It just let us extend the enum for each new import.
The fieldname `name` was choosen with the idea to differentiate the imports. I would suggest to improve the name-field content by a more specific name, i.e. "import motions for summer-event ...".
Written this, I see 2 fields, `name` and `type`. But do we need this now?

**Comment by jsangmeister** [comment]
As discusssed: We will add an enum for the field.
