### ISSUE TITLE
State changing behavior

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#199]
https://github.com/OpenSlides/openslides-backend/pull/192#issuecomment-706237972

If we set a new state of the motion sometimes we have to change some fields of the motion e. g. the number if the [set_number](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/models/models.py#L987) flag is true.

Edit (Finn): `identifier` -> `number`

**Comment by normanjaeckel** [comment]
Please check OS3 set state and reset state logic for this.

**Comment by reiterl** [comment]
Looked at the OS3 code.
in set_identifier() which is called in set_state, is a **config** used. Is there also a config in OS4, or where do I get the values from?
Following config values are needed:
"motions_identifier"
"motions_identifier_with_blank"
'motions_amendments_prefix'
"motions_amendments_enabled"
as far as I see them.

**Comment by jsangmeister** [comment]
Yes, the previous "config" was renamed to "settings". They are simply fields of the underlying meeting (see `models.yml`)

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/336 for this.
The _identifier_ was renamed into _number_. The PR added the set_number to motion.create, motion.set_state and
motion.reset_state.
