### ISSUE TITLE
Emptying `genders` field in `organization.update` causes genders to not be deleted from the users

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#2070]
See [this comment in the client](https://github.com/OpenSlides/openslides-client/pull/3101#pullrequestreview-1779842540)

If the genders field is set to [] in the payload the users will not have their genders removed.

There are also lock break errors that sometimes occur, idk how to trigger them though

**Comment by jsangmeister** [comment]
It looks like the broken locks were a bug in the datastore: https://github.com/OpenSlides/openslides-datastore-service/pull/295.

The truncation of the gender list is added in https://github.com/OpenSlides/openslides-backend/pull/2073, although I'm not sure if we even want to support this. But I suppose it doesn't hurt, like if someone wants to disable the gender feature completely...
