### ISSUE TITLE
Cannot create motion_submitter, meeting id of motion and user don't match.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#208]
The error is not correct since user 2 is in meeting 1 (see example data: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/example-data.json#L328) and motion 2 is also in this meeting.

action payload: `[{action: "motion_submitter.create", data: [{user_id: 2, motion_id: 2}]}]`

**Comment by normanjaeckel** [comment]
Example data are invalid: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/example-data.json#L91

**Comment by FinnStutzenstein** [comment]
No. The meeting id from a user indicates, that he is a temporary user. Non temporary users can also be submitters. The user_ids of a meeting determinates, who can participate in the meeting. A note to this field: it is calculated and the union from all group users and all temporary users
