### ISSUE TITLE
Automatically check motions for equality

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2121]
Upon saving a motion (either via `motion.create` or `motion.update`), if the `motion/text` changed, all other motions of the meeting should be checked if they have the same text [1] [2]. If that's the case, the new relation `identical_motion_ids` should point to the motion(s) with the same text.

[1] "same text" is defined as having the same textual content, ignoring all html markup. All spaces, line breaks, hyphenation etc. is kept and may lead to two motions not being identified as identical.

[2] The check is implemented via hashes: Upon save, the hash for the pure text of the motion is calculated and saved in the new field `text_hash`. Then, it can be checked via a simple `filter()` if any other motion has the same hash.

**Comment by jsangmeister** [comment]
It seems like the task itself is relatively easy to implement using `BeautifulSoup4`s `get_text()` method: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text. However, iterating and parsing all motions of the meeting might be very time-consuming, especially if there are many and/or long motions. We should do some testing beforehand to make sure that motion updates do not suddenly take multiple seconds. If that would be the case, an alternative would be to run this task asynchronously, but that would require more implementation work.

**Comment by jsangmeister** [comment]
> [2] Open question: What should happen if multiple motions have the same text?

For now, I assumed that all identical motions will be linked and therefore modelled it as a reflexive n:m relation. From my perspective, this solution makes the most sense. But it would be no problem to change again.

**Comment by jsangmeister** [comment]
Updated the description as discussed.

**Comment by jsangmeister** [comment]
As stated in https://github.com/OpenSlides/openslides-client/pull/3205#issuecomment-1911800427, old motions will not be directly included in equality checks. We could write a migration to fix this so motions do not have to be explicitly saved before the relation appears. What do you think @rrenkert?

**Comment by rrenkert** [comment]
Since we have to generate the hash for all motions (including the old ones) it should be easily possible to perform the equality checks. So I think we should include this step.
