### ISSUE TITLE
Add presence to list of entitled users

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#2156]
Updated description:

The presence should be added as a field `is_present` analogously to the "has voted" status so that the client can display and filter by that.

Additionally, a new 100%-base should be added: "All present entitled users".

**Comment by jsangmeister** [comment]
First, this is a backend issue as the list is calculated in the backend. Secondly, this was changed just two years ago after you wished to have __all__ users present in the list, not only present ones: https://github.com/OpenSlides/openslides-backend/issues/1220. It is not productive to change behaviours back and forth every few months...

**Comment by ostcar** [comment]
24 is not few 😉
