### ISSUE TITLE
Remove SLLOS if all speakers with the structure level are interventions or interposed questions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2163]
Upon `speaker.update`, if a speaker is updated from anything other than `intervention` or `interposed_question` to one of them and no other speaker for the structure level remains with another `speech_state`, the related SLLOS should be deleted.

**Comment by luisa-beerboom** [comment]
Does this also apply for speaker creation/deletion?

i.e. if a speaker is created as an intervention, a SLLoS should not be created and in a normal speaker is deleted, as per #2151 , the structure level should also be deleted if no one has spoken yet and all speakers remaining after that are either interventions or interposed questions

**Comment by luisa-beerboom** [comment]
Not having a `structure_level_list_of_speakers` for these speakers would effectively mean that they can't have a `structure_level` associated with them, so no fraction membership shown in the client for the interposed question. 
Do we really want this?
If yes, I think the `speaker.create` and `-update` should throw an error if the `structure_level_id` is set.

What do you think about this @jsangmeister ?

**Comment by luisa-beerboom** [comment]
Closing because this will be done in the client
