### ISSUE TITLE
Don't use structure level timer for interposed questions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2165]
The time is currently subtracted from the structure level when a structure level is selected for an interposed question. This needs to be changed in the backend.

_Originally posted by @bastianjoel in https://github.com/OpenSlides/openslides-client/issues/3221#issuecomment-1916535428_

**Comment by jsangmeister** [comment]
@bastianjoel can you tell me how to replicate this? For me, it works like intended.

**Comment by bastianjoel** [comment]
Does not happen with current version anymore.
