### ISSUE TITLE
Participant JsonUpload/Import with group to be created

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#2180]
Not existing groups were created without any rights
user.update: Don't include field username in update action, because of existing usernames with spaces, which should not be changed
user.create: im json upload Prüfung auf Leerstellen im Username

**Comment by jsangmeister** [comment]
Please follow https://github.com/OpenSlides/OpenSlides/wiki/Development-organization#pull-request-titles-and-commit-messages and set appropriate meta data.
