### ISSUE TITLE
Structured fields

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#219]
New syntax for structured fieds: The dollar `$` is not replaced - the value is appended behind it.

Another thing: What should the client write into these fields in the actions. E.g. for `group_$_ids` or `amendment_paragraph_$`?

**Comment by jsangmeister** [comment]
> Another thing: Whe shoudl the client write into these fields in the actions. E.g. for `group_$_ids` or `amendment_paragraph_$`?

In #195 it looks like @normanjaeckel assumes that the client writes with the replaced dollar sign, e.g. `group_7_ids=[1]`. Since the backend does not know the replacement (it could be the meeting id or a fixed string) I think this is the only possible way to do it (or now, `group_$7_ids=[1]`). Unfortunately, we can no longer validate this with jsonschema (I think?) and would have to do that manually, but that's okay.

@normanjaeckel any more thoughts?

**Comment by FinnStutzenstein** [comment]
I mean the backend do not handle structures relations generically, so we can do a special thing for every relation. e.g. for temporary users, we can just give `group_ids`, since we know, that they have to be associated with the meeting of the user. Or for `amendment_paragraphs` we can give an dict with number<->HTML. But we can also write plain into these fields - the client hasn't decided yet.

**Comment by normanjaeckel** [comment]
If we have a special action the client can send special values like `"foo": 42` and this cation transforms it to the interpolated structured field `"groups_3_ids": [42]`. The question is what the client wants to send.

See #170 where we decided NOT to implement a generic solution at the moment.

**Comment by FinnStutzenstein** [comment]
> Another thing: What should the client write into these fields in the actions. E.g. for group_$_ids or amendment_paragraph_$?

Still not answered

**Comment by normanjaeckel** [comment]
What is the operation a client user wants to do. Therefor we should provide the respective action. In my opinion it is not about sending more stuff with generic create or update action. E. g. the paragraph number can be send within an motion.create or better amendment.create as explicit property `paragraph_number`.

**Comment by jsangmeister** [comment]
So I guess the consens is that we make it action specific since we agreed earlier to not implement a generic solution. So we have to discuss this in the respective actions. Closing this then.
