### ISSUE TITLE
Participant csv import: Import of existing users with space in username not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-backend#2204]
**Description:** If a user wants to import existing users with usernames that contain a space between surname and name, an error appears. Import ist not possible. 

**Reproduction:**
A reproduction in a new meeting instance is not possible. An old instance with an existing user data base and usernames with spaces must be used. - For reproduction simply try to import an existing user with space in username via csv file in a meeting. 

**What should happen:**
It should be possible to import old, existing usernames that contain a space between surname and name. The import should check if the username still exists and reference it with the space. Additionally it should not be possible to generate new users with usernames that contain spaces.

**Comment by luisa-beerboom** [comment]
i.e. if an import row is identified via a username that includes a space, cut this username out of the user.update payload (we aren't changing it anyway)
