### ISSUE TITLE
Committee admin cannot appoint themselves as meeting admins

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2205]
**Current behaviour:**
if an committee admin tried to appoint themselves as a meeting admin the following error is thrown: 
```
Error: You are not allowed to perform action meeting.update. Missing Permission: meeting.can_manage_settings
```

**Wanted behaviour:**
If a user is a committee admin then they need to be able to appoint themselves as meeting admin in every meeting from their committee

**Comment by jsangmeister** [comment]
Also cannot replicate it, even though @Elblinator showed it to me...

**Comment by Elblinator** [comment]
I cannot replicate it anymore
I tried it with different combinations
We can revisit this if it happens again
