### ISSUE TITLE
Change backend for enhance time edit menu

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#2219]
Make appropriate changes for OpenSlides/openslides-client#3296

**Comment by luisa-beerboom** [comment]
From what I see, the client issue states the following additional requirements that need to be addressed with new backend functionality:
>     1. Reset timer: The timer should be resetable to the start time of the set structure level timer. NOT the general default time value for structure levels.
> 
>     2. Add time option: It should be possible to manually add time to the structure level timer.
> 
>     3. Remove time option: It should be possible to manually remove time from the structure level timer.

I propose:
Add `remaining_time` as a possible option for the `structure_level_list_of_speakers.update` action client can then set the time to whatever point they like, including "resetting" it by setting it to the `initial_time`

Other options would be to create extra actions for adding/removing to/from and resetting timers, however I don't believe they make much sense, unless maybe if the client change functionality is difference-based instead of result-based

What do you guys think?

**Comment by jsangmeister** [comment]
Yes, seems good. The advantage of the "difference-based" approach would be that in general, the backend should be responsible for as much business logic as possible, since the client might have incorrect data. But I don't believe this is that relevant here.
