### ISSUE TITLE
motion_statute_paragraph.create: make text required

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#230]
@normanjaeckel in https://github.com/OpenSlides/openslides-backend/pull/228 you forgot to make `text` required which it should be according to https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/43. @reiterl maybe you can take care of this?

**Comment by reiterl** [comment]
add https://github.com/OpenSlides/openslides-backend/pull/231 for this.
