### ISSUE TITLE
Change permission for user-related actions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2307]
- [x] All user-related actions except `user.create` and `user.delete` should be changed to be callable with the permission `user.can_update` instead of `user.can_manage`.
- [x] Updating the field `present_user_ids` via `meeting.update` should be allowed with `user.can_update`
- [x] The method `check_permissions_for_scope` in the `UserScopeMixin` must be updated to take the required permission (`user.can_manage` or `user.can_update`) into account for the meeting scope. Currently, when updating a user while only having `user.can_update`, it fails with a permission error because the user does not have `user.can_manage` permissions.
- [ ] The action descriptions need to be updated.

**Comment by jsangmeister** [comment]
specifications need to be discussed

**Comment by jsangmeister** [comment]
Discussion finished, specs are final™

**Comment by luisa-beerboom** [comment]
>     * [ ]  The method `check_permissions_for_scope` in the `UserScopeMixin` must be updated to take the required permission (`user.can_manage` or `user.can_update`) into account for the meeting scope. Currently, when updating a user while only having `user.can_update`, it fails with a permission error because the user does not have `user.can_manage` permissions.

@jsangmeister does that just mean that the scope should be `meeting` regardless of if the permission is `can_manage` or `can_update`, or should there be a distinction between a meeting scope gained through `can_manage` or one "only" gained through `can_update`?

**Comment by jsangmeister** [comment]
> @jsangmeister does that just mean that the scope should be `meeting` regardless of if the permission is `can_manage` or `can_update`, or should there be a distinction between a meeting scope gained through `can_manage` or one "only" gained through `can_update`?

Currently, the permission `can_manage` is hardcoded to be required to change a user with scope `meeting`. This should be changed so that it is configurable via a parameter which permission is needed. Then, `user.update` can call this method with `can_update` and `user.create` with `can_manage`. I hope this makes it clear.
