### ISSUE TITLE
New settings for restricting delegator rights

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#2348]
Make backend changes for OpenSlides/openslides-client#3477

We need new settings for the proposed functionality, I propose the following names and functions:
- `participants_forbid_delegator_in_list_of_speakers`: Users who have delegated their votes in this meeting may not add themselves to the meetings LoS's
- `participants_forbid_delegator_as_submitter`: Users who have delegated their votes in this meeting may not create motions
- `participants_forbid_delegator_as_supporter`: Users who have delegated their votes in this meeting may not support motions

All of these will be off by default to preserve current functionality, so there's no migration necessary.

Predictably this will require changes in `motion.create`, `motion.set_support_self`, `speaker.create`, `speaker.delete` and `meeting.update`, so please don't forget to update the documentation

**Comment by rrenkert** [comment]
Please remember (as stated in the client issue) that these settings only apply for _not present_ users in the actions.

**Comment by luisa-beerboom** [comment]
- Relevant `can_manage` rights should always defeat these new restrictions
- If self-adding is not permitted, self-removal should not be possible either
