### ISSUE TITLE
Can't change direction of delegation in one transaction

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#2365]
Something like
```
{
  "action": "user.update",
  "data": [
    {
      "id": 4,
      "meeting_id": 2,
      "vote_delegated_to_id": null,
      "vote_delegations_from_ids": [
        6
      ],
    }
  ]
}
```

Will throw error `User(s) [5] can't delegate their votes because they receive vote delegations.` if there was already a delegation between these users (pointing in the other direction) before the call.
Since that very delegation is supposed to be deleted through this action, there is no reason why this should raise an error.
This should be fixed.

It may also be worthwhile to look into whether this also happens if the same transaction is started from the other direction (from-delegation deleted, to delegation opened)

**Comment by jsangmeister** [comment]
I _think_ this might be related to https://github.com/OpenSlides/openslides-backend/issues/1801, but I don't think either of those is worth investigating now as this will be resolved with the relational db sometime in the undeterminate future

**Comment by luisa-beerboom** [comment]
To me it seems more like a calculation error in the `check_vote_delegations_from_ids` method of the `MeetingUserMixin`.
That's where the error is thrown.
