### ISSUE TITLE
New setting for restricting delegator rights part 2

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2370]
Make backend changes for OpenSlides/openslides-client#3518

We need one new setting for the proposed functionality, I propose the following names and functions:
- `participants_forbid_delegator_to_vote`: Users who have delegated their votes in this meeting may not vote for themselves 

This will be off by default to preserve current functionality, so there's no migration necessary.

Predictably this will require changes in `poll.vote`, so please don't forget to update the documentation

**Comment by jsangmeister** [comment]
> Predictably this will require changes in `poll.vote`, so please don't forget to update the documentation

Moreover, this will require changes in the vote service (@ostcar)

**Comment by ostcar** [comment]
When I remember correctly, the feature was slightly different. When this setting is set, then at all time, there can be only one user, that can vote for a user. This means, that when the setting is set, then the vote can only be delegated to one user. When the setting is not set, then the vote can be delegated to many users.

**Comment by jsangmeister** [comment]
Related issues:
- https://github.com/OpenSlides/openslides-vote-service/issues/225
- https://github.com/OpenSlides/openslides-backend/issues/1883

**Comment by jsangmeister** [comment]
As discussed: The solutions described in the related issues will be split into two independent settings, one as described above and one to enable multi-mode.
