### ISSUE TITLE
Fix exception handling

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#239]
Currently, if a database exception happens, we catch it in the `views.py` and throw a `ViewException` instead. Therefore, if that happens in a test, we have no debug output to see where or why the exception happened. Example output:

    tests/system/action/motion/test_reset_state.py F                                                                 [100%]

    ======================================================= FAILURES =======================================================
    _________________________________ MotionResetStateActionTest.test_reset_state_correct __________________________________

    self = <tests.system.action.motion.test_reset_state.MotionResetStateActionTest testMethod=test_reset_state_correct>

        def test_reset_state_correct(self) -> None:
            self.create_model("meeting/222", {"name": "name_SNLGsvIV"})
            self.create_model(
                "motion_workflow/1",
                {"name": "test1", "state_ids": [76, 77], "first_state_id": 76},
            )
            self.create_model(
                "motion_state/76",
                {
                    "name": "test0",
                    "motion_ids": [],
                    "workflow_id": 1,
                    "first_state_of_workflow_id": 1,
                },
            )
            self.create_model(
                "motion_state/77", {"name": "test1", "motion_ids": [22], "workflow_id": 2},
            )
            self.create_model(
                "motion/22", {"meeting_id": 222, "title": "test1", "state_id": 77}
            )
            response = self.client.post(
                "/", json=[{"action": "motion.reset_state", "data": [{"id": 22}]}]
            )
    >       self.assert_status_code(response, 200)

    tests/system/action/motion/test_reset_state.py:29: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    tests/system/base.py:33: in assert_status_code
        self.assertEqual(response.status_code, code)
    E   AssertionError: 400 != 200
    ------------------------------------------------- Captured stdout call -------------------------------------------------
    b'{"success": false, "message": "Datastore service sends HTTP 400. {\'fqid\': \'motion_workflow/2\', \'type\': 3, \'type_verbose\': \'MODEL_DOES_NOT_EXIST\'}"}'
    =============================================== short test summary info ================================================
    FAILED tests/system/action/motion/test_reset_state.py::MotionResetStateActionTest::test_reset_state_correct - Asserti...
    ========================================== 1 failed, 317 deselected in 1.33s ===========================================

What I currently do to debug these errors is remove the `DatabaseException` from the list in `views.py`, which is tedious and hacky. In the datastore, we use flask for route and exception management, which handles these cases automatically. I think the easiest solution would be to smartly adjust the exception hierarchy so that the information from the `DatabaseException` doesn't get lost. Will you look into this @normanjaeckel?

**Comment by normanjaeckel** [comment]
I propose to add the logging module to the tests (e. g. [here](https://github.com/OpenSlides/openslides-backend/blob/master/tests/system/util.py#L37)). Then you can enable pytest logging with `--log-level=DEBUG`, see https://docs.pytest.org/en/stable/reference.html#confval-log_level.

Maybe we have to remove or silence some unnecessary logs.

**Comment by jsangmeister** [comment]
This does not help with the problem: I want to know at which point the `DatabaseException` occurs and why. With enabled logging, the only message for is
```
DEBUG    openslides_backend.services.datastore.adapter:adapter.py:47 Get repsonse with status code 400: {'error': {'fqid': 'motion_state/190', 'type': 3, 'type_verbose': 'MODEL_DOES_NOT_EXIST'}}
```
which does not help at all for this.

**Comment by normanjaeckel** [comment]
Do I understand you correctly: You want a flag or option that some or all exceptions are not transformed to regular HTTP 400 results but be thrown with full traceback?

**Comment by jsangmeister** [comment]
No. We have two cases when a datastore exception gets thrown: It is intended because it is a negative test. So we need a 400 status code. The other case is if it's not intended and stems from an error in our tests. Then, we need to have the traceback available. There must be a way to combine these two, hence the suggestion to subclass from one another: The 400er is kept, but also the traceback doesn't get lost.

**Comment by normanjaeckel** [comment]
See #252

**Comment by normanjaeckel** [comment]
You may also use this environment variable inside a test where you assume HTTP 200.

**Comment by jsangmeister** [comment]
I guess we will not find a suitable solution here.
