### ISSUE TITLE
Set `users_forbid_delegator_to_vote` default to true

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2433]
**Explanation:**
The new field from this PR (https://github.com/OpenSlides/openslides-backend/issues/2370) added a new setting for delegations and a more refined behaviour. 

*Wanted behaviour:**
The new default is not the same as the old default to prevent this new unintended behaviour the setting (`users_forbid_delegator_to_vote`) should be set to true per default

**Comment by rrenkert** [comment]
This one is obsolete. We want to keep the default "false" (no value set).
