### ISSUE TITLE
Change presenter ```get_user_related_models```

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2449]
**Current behaviour:**
The presenter currently gives back meeting ids even if the User is only in there as a remnant and not as a informational important User:
Example response if the User is not ANYMORE in the meeting (but was in there before) and has no other connections to the meeting: 
```
id: 5
is_active_in_organization_id: 1
name: "Meetings Name ABC"
```
Example response from the presenter if the User is a candidate, a submitter, a speaker and a manager in the same meeting:
```
{
  "id": 6,
  "name": "Meeting name",
  "is_active_in_organization_id": 1,
  "speaker_ids": [ 20 ],
  "motion_submitter_ids": [ 40 ],
  "assignment_candidate_ids": [ 7 ]
}
```

**Reproduction to get the first response:**
It is important that you add User C to (at least) two meetings before removing/deleting them from any
1. Create User C 
2. Create two meetings
3. Add C to both meetings 
4. In Meeting A delete User C
5. In meeting B delete User C
6. Navigate to the account list
7. C has no assigned Meetings
8. Delete User C from the account list
9. In the deletion dialog both meetings will be listed 

**Wanted behaviour:**
If a User only has a meeting_user_id but is not assigned to any group, or is in one of the other groups (candidate, submitter, speaker) then this meeting Id should not be returned by the presenter

**Comment by MSoeb** [comment]
Issue is reopened again, because the fix doesn't work well. The old meetings of the user, in which he isn't participant anymore, are still visible.

**Comment by luisa-beerboom** [comment]
And what did you do to get that result?

**Comment by MSoeb** [comment]
The reproduction steps which are listed above.
