### ISSUE TITLE
Revert #235

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#246]
Please explain usecase for productive container and maybe revert #235

**Comment by FinnStutzenstein** [comment]
It is some form of management script. The backend should later become  some management capabilities - until then, a curl is enough to manipulate the datastore in a productive environment.

**Comment by normanjaeckel** [comment]
As discussed today we keep this issue open and will see some times later.

**Comment by jsangmeister** [comment]
> will see some times later.

It is some time later, can we close this? I don't see any harm in having curl available inside the container, it can be a useful debugging/testing tool even with management scripts.

**Comment by FinnStutzenstein** [comment]
It is ok for me.
