### ISSUE TITLE
Handling of actions which have nothing to do

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#247]
Came across this question in https://github.com/OpenSlides/openslides-backend/pull/245/ as well as #229. In case the actions finds out it has nothing to do, both @reiterl and @normanjaeckel throw an exception. I think we should just ignore it. Especially in case of #245, one might just click the button to be sure everyone is deleted without actually checking it, and it might be confusing to present an error then. What do you think?

**Comment by normanjaeckel** [comment]
Backend should throw an error and answer with HTTP 400 (and not HTTP 200). It is up to the client to decide whether the user in the concrete use case wants to see this error or not.

**Comment by FinnStutzenstein** [comment]
If a task was done since there is nothing to do, it is done. There should not be an error.We always show errors to our users - we even cannot distinguish between non-important and important errors, so we are just going to confuse users...

**Comment by jsangmeister** [comment]
Ok, I can change it accordingly.
