### ISSUE TITLE
Meeting.create: make duplicate from (optionally) mandatory

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2507]
Context: The new setting from the Meta-Issue https://github.com/OpenSlides/openslides-meta/issues/125

If the new setting is active then the action meeting.create requires values from „duplicate from“

**Comment by reiterl** [comment]
If in the client the duplicate-from field is set, the meeting.clone action will be called. The meeting clone action already has a required meeting id to clone/duplicate from.
