### ISSUE TITLE
Prevent the removal of the last admin per meeting

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2528]
**Current behaviour:**
It is possible to have a meeting without any user as it's admin (specifically the **admin** group here)

This can lead to problems for the users and after the feature to lock a meeting from the inside, it can even lead to inaccessible meetings  

**Known ways to remove the last admin:**
- As superadmin/orgaadmin: remove/delete the last admin (possible from orga- and meeting-level)
- As accountadmin/committeadmin: delete the last admin (possible from orga-level)
- As "meeting" admin: remove the admin group from everyone (including yourself)

**Wanted behaviour:**
If someone tries to remove the last admin from a meeting this action should be blocked and thrown an error

Any meeting which already has no user in the admin group should stay like that. -> meaning no migration is needed

**Comment by luisa-beerboom** [comment]
It should still be possible to remove the last admin from template meetings, it should not be possible to remove template status from a template meeting without admins
