### ISSUE TITLE
User cannot be deleted if he ever chatted

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-backend#2566]
Reproduce:
1. Enable Chat
1. Create user A and add to meeting
1. Login as A and send a chat message
1. Login as superadmin and try to delete A

Trying to delete a user who has sent a chat message before will return 500.
The following ERROR is logged:

    ERROR:openslides_backend.shared.handlers.base_handler:Error occured on index 0: Update of chat_message/X: You try to set following required fields to an empty value: ['meeting_user_id']

I think this speaks for itself..

IMO we have to find a way of how to handle this, as seemingly it's currently not allowed to remove the `meeting_user` reference from the message.\
Maybe the solution here can be to not try to remove the `meeting_user` reference from the message, but instead remove the `user` from the `meeting_user` object, although this probably runs into a similar issue as `user_id` is also required in `meeting_user`.

So I am not sure what the correct approach is..

**Comment by peb-adr** [comment]
If chat messages continue to exist but the (meeting_)user reference is removed, this probably also needs a change in the client, to display something like 'unknown/deleted user' next to the message and not smth like 'undefined'

**Comment by r-peschke** [comment]
@peb-adr @rrenkert @r-peschke:
The chat message should be kept, but the (meeting-)user should be set to NULL. This implies that the meeting_user is not required anymore in chat-instance
