### ISSUE TITLE
User import: 'is_active' should have the default true

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-backend#2579]
**Current behaviour:**
If a user is created via the import and the cell in the is_active row was empty then the backend saved the value "null"

**Wanted behaviour:**
the new default should be true (every user who is created via the import should have is_active:true, if not explicitly stated otherwise

For the needed migration: 
If a user was imported like described, then this user cannot login and they get the snackbar Error 
```
Error: The account is deactivated.
```

**Comment by Elblinator** [comment]
waiting for 
https://github.com/OpenSlides/openslides-client/issues/4011

**Comment by luisa-beerboom** [comment]
So... should the migration just set every user with `is_active==None` to True?

**Comment by rrenkert** [comment]
Yes, every user that has is_active==None should be set to true.

**Comment by rrenkert** [comment]
> **Wanted behaviour:** the new default should be true (every user who is created via the import should have is_active:true, if not explicitly stated otherwise

The default should always be used not only in the import.
