### ISSUE TITLE
Return Array in error case

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#261]
See https://github.com/OpenSlides-action-crew/openslides-backend-coordination/issues/44#issuecomment-718486353

Like we return an array of objects in the success case, we should return an array in the error case. Also, in the mixed case, we need to:

1. make sure to return an error with success and error responses
2. document how the following actions are handled in case of an error and add a test for that. Example: An array with actions `[A, B]` is sent. `A` throws an error. Does `B` still get executed?

**Comment by normanjaeckel** [comment]
We do not have a mixed case so it would be useless to provide an array in error case. If an array of actions is send and one of them causes an error, the result of all of them is error.

This handling is still a point of discussing: https://github.com/OpenSlides/openslides-backend/issues/27

**Comment by FinnStutzenstein** [comment]
> If an array of actions is send and one of them causes an error, the result of all of them is error.

Please provide an index in this case, so the client knows, which action was the one that failed.

**Comment by jsangmeister** [comment]
Also, I would suggest to then not return an array in the success case, since it's not uniform. Especially since we just multiply the default success message as many times as actions are sent ;)

**Comment by normanjaeckel** [comment]
Index in error case is ok for me.

In success case I would like to stay with an array because sometimes the client likes to get extra information (like a new id in create case).

**Comment by jsangmeister** [comment]
This should be solved then

**Comment by normanjaeckel** [comment]
It is not. We do not send an index in any error case at the moment.

**Comment by jsangmeister** [comment]
I thought it was done with https://github.com/OpenSlides/openslides-backend/pull/286 as well, my bad. As far as I understood it, the index should be returned whenever an ActionException is thrown inside an action to know which action failed.

**Comment by FinnStutzenstein** [comment]
Yes, the interface in https://github.com/OpenSlides/OpenSlides/pull/5696 must be implemented.

**Comment by r-peschke** [comment]
What is to be done in client, backend and in the response?
What is action and payload? With #397 we send actions with events to the datastore-service, but even this actions could consist of more than one backend-action like motion.create.

**Comment by r-peschke** [comment]
See the definition of the interface for ActionService: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/action-service.txt. It defines, how to call the ActionService in backend and it's respond format and isn't yet implemented as described, especially missing the atomic-parameter in calling handle_request method and the resulting actions of this parameter. But it defines the names of the different entities, that we should follow in general.

The issue [Restructure action handling and implement transaction models](https://github.com/OpenSlides/openslides-backend/issues/325), following it's related PullRequest [Restructure Action handling & fix relation handling with multiple actions
](https://github.com/OpenSlides/openslides-backend/pull/337), just resolved the first part, but didn't implemented the atomic/transaction feature.

On implementing the backend we should see/modify the interfaces of other services to get the position of an error. Errors found in the backend may be located directly, errors from datastore-service, permission-service(?), ...  for instance should report error positions for action-index and data-object (the data-list in action) in a similar interface format to the backend-action-service.

Let us talk about the interface action-service.txt: 
payload is used as first parameter of method handle_request and defined as Action[]. That's also the definition used in the backend. In the text of the interface payload is also used for the elements of _data: object[]_ . Maybe we could choose another for it like _data: action_data[]_, spoken as list of action_data?

**Comment by FinnStutzenstein** [comment]
> but didn't implemented the atomic/transaction feature.

@jsangmeister Can you check this - I thought, that the atomic key was implemented

**Comment by FinnStutzenstein** [comment]
> Maybe we could choose another for it like data: action_data[], spoken as list of action_data?

I like this proposal: So we have this interface
```
handle_request(payload: Action[], user_id: Id, atomic?: boolean): ActionsResponse

interface Action {
    action: string;
    action_data: object[]; <-- note the change here
}
```
We have the following terminology than:
- payload: The data the client sends (contains many actions).
- action_data: The many datasets for one action

This must be renamed in the backend though. @jsangmeister If this is OK for you, please create a final issue for this task, so someone can do it. Maybe during the renaming the one should try to replace every occasion of `instance` etc. with more meaningful names.

**Comment by FinnStutzenstein** [comment]
> On implementing the backend we should see/modify the interfaces of other services to get the position of an error. Errors found in the backend may be located directly, errors from datastore-service, permission-service(?), ... for instance should report error positions for action-index and data-object (the data-list in action) in a similar interface format to the backend-action-service.

Yes, this would be nice. But for now: If the backend has the **possibility** of accepting specific meesages would is needed -> The backend should now follow the interface as good as possible.

**Comment by jsangmeister** [comment]
> @jsangmeister If this is OK for you, please create a final issue for this task, so someone can do it

Yes, sounds good. We can just use this issue, I can implement it.

**Comment by FinnStutzenstein** [comment]
> We can just use this issue, I can implement it.

I've create a new one, becuase this issue is another thing.

**Comment by FinnStutzenstein** [comment]
Whats about the atomic flag?

**Comment by jsangmeister** [comment]
> Whats about the atomic flag?

I would have just implemented everything at once.

**Comment by FinnStutzenstein** [comment]
Ah ok, if you want to do this, ok!

**Comment by jsangmeister** [comment]
>     action_data: object[]; <-- note the change here

Ah, I must've missed that you also want to rename the field in the payload. I don't like this idea - `action` and `data` is nice and verbose. For verbal clarification and use in the submethods of the backend I like the wording of `action_data`, but I would suggest to leave the interface as-is.
