### ISSUE TITLE
Invitation E-Mail: Add more placeholders

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-backend#2634]
**Current behavior**
The invitation mail misses some placeholders to cover various formulation requirements. 

**Wanted behavior**
Please add placeholders for:
- [ ] Title (of account)
- [ ] Given name
- [ ] Surname
- [ ] Structure level (if possible to add as placeholder)
- [ ] Groups (analogous to structure_level)

--> Admins should have the possibility to add these placeholders to the invitation mail.

Additionally the gray help text in settings > participants > Email > Email Subject should be rewritten to include the new placeholders. 
New text: You can use {event_name}, {username}, {title}, {given_name}, {surname} and {structure_level} as placeholder.

**Comment by peb-adr** [comment]
In https://github.com/OpenSlides/OpenSlides/issues/6022 it was also called for `groups` to be added to the list of placeholders.\
I'll edit the original comment of this issue to include this.\
We discussed that if `groups` can be included it should be doable analogous to `structure_level`.
