### ISSUE TITLE
Public Access: Add a new setting for global activation

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-backend#2656]
As stated in https://github.com/OpenSlides/openslides-client/issues/4204 we need a new setting for the superadmin to activate/deactivate the public access globally on orga level.
The setting should prevent publishing a meeting if this option is set to false.
The default should be `false` and if toggled from true to false all published meetings should be unpublished.

**Comment by luisa-beerboom** [comment]
Discussed with @rrenkert that the setting should not automatically unpublicise public meetings, but that their public status should instead be hidden in the same way as delegations do if they are turned off.

**Comment by luisa-beerboom** [comment]
The field should be used to hide the guest button in the login mask if it is not true.

@bastianjoel @m-schieder I cannot evaluate what changes would be needed in the auth service, if any, but I can imagine that we may want all anonymous users to be thrown out if the setting is turned off.
