### ISSUE TITLE
Let actions run independently

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#27]

**Comment by normanjaeckel** [comment]
Or perhaps not?

**Comment by normanjaeckel** [comment]
@FinnStutzenstein Please let us discuss this: I recommend that the actions do not run independently so the client can decide: Independently: Send different requests. Dependently: Send one request with different actions. Because we use HTTP2 this might not be a network problem.

The advantage is that I do not have to implement extra logic to decide whether some actions belong together or not.

**Comment by FinnStutzenstein** [comment]
What is the dependent behavior: If some actions fail, do all actions fail and nothing is written to the datastore? Or do all actions prior to the first fail succeed?

**Comment by normanjaeckel** [comment]
If some actions fail, nothing should be written to the datastore. Even in import case.

If the client wants to import indepentently it should send extra "requests".

Only sending emails is a special case: "Failing" here means that we can not validate data correctly. But if all data are valid and then the backend tries to handle the email to the mail transfer agent then the action was successful even if we can not guarantee that the email will go out or come in.

**Comment by FinnStutzenstein** [comment]
Ok

**Comment by FinnStutzenstein** [comment]
Ah not ok, we should discuss this in a telco with @ThomasJunk

**Comment by normanjaeckel** [comment]
Actions can not and should not run independently. Client should send independent request if he wants independent actions.

**Comment by FinnStutzenstein** [comment]
> can not
Well they can, if someone would implemented it

> should not
Why should a creation of a topic and a motion update should depend on each other?

Ok for now since I cannot think of a case where it is strongly needed. But: If there is such a case, I will never send multiple requests (Learned from OS3...) and it should be implemented.

**Comment by normanjaeckel** [comment]
We can keep this issue open and let the service as is at the moment. Please let us discuss when such a case came up.
