### ISSUE TITLE
Motion create with specific group permissions not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-backend#2723]
**Describe the bug**
If a participant has the group permissions 'can see agenda, 'Can see internal items and time scheduling of agenda, 'Can manage agenda', 'can see motions', 'Can create motions' and 'Can manage motion metadata' motion creation is not possible. By saving it an error appears.

Error message: Fehler: You are not allowed to perform action motion.create. Forbidden fields: agenda_type, agenda_create

**How to Reproduce**
1. open a meeting
2. open participants > groups > grant the delegate group the above mentioned permissions
3. open participants > create a user as delegate
4. login as the user > open motions > create a new motion > enter title and text > try to save

**Expected behavior**
The motion creation with the specific set of permissions should work. 

Please check, if agenda_type, agenda_create would have other negative impacts on creating motions. 

It could be possible, that there is a relation to the issue OpenSlides/openslides-client#4290

**Comment by luisa-beerboom** [comment]
If the agenda properties are set it breaks, if they aren't set it works. I assume you got this error while trying to create a motion that was supposed to go straight into the agenda. If not, we may have to look into why the client is uselessly sending agenda properties.

Regardless the fact that these fields just do not work, this requires a fix in the backend. On that note: I would need to know what permissions one should have to be able to add motions to the agenda in this sense. I also would need to know what effect the setting `agenda_item_creation` would have on this. I looked through the docs, but have not yet found anything.

**Comment by Elblinator** [comment]
The client wanted behaviour is documented here: 
https://github.com/OpenSlides/openslides-client/issues/4359
