### ISSUE TITLE
Parse recommendation_extension

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#275]
The recommendation extension has to be parsed for `\[(?P<fqid>\w+/\d+)\]`, e.g. `[motion/42]`. It must be checked, that these models exists and finally put into `recommendation_extension_reference_ids`.

So if the text is `The motion [motion/3] is accepted if [motion/59] is, too`, the recommendation_extension_reference_ids must be `['motion/3', 'motion/59']`. Currently, only the collection `motion` is accepted and every motion must be of the same meeting.

**Comment by reiterl** [comment]
In which actions belong the recommendation extension parsing?

**Comment by jsangmeister** [comment]
It is currently set only in the `update_metadata` action. I assume it is correct that you can't give this field on creation @FinnStutzenstein?

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/332 for this.
I didn't include meeting_id check, as it is done by the equals_fields setting.

**Comment by FinnStutzenstein** [comment]
> It is currently set only in the update_metadata action. I assume it is correct that you can't give this field on creation @FinnStutzenstein?

Right.
