### ISSUE TITLE
Refactoring handlers to a base class

### ISSUE THREAD

**Issue by ThomasJunk** [OpenSlides/openslides-backend#31]
Hi there, 
I am one coworker of @tsiegleauq.
 
While skimming through the codebase I noticed the following:

We have 

* `ActionsHandler`
* `PresenterHandler`
* `RestrictionsHandler`

each with  with methods `handle_request()` and `validate()`. Whereas `validate` itself doing the same steps:

* logging what is going on
* validating the payload

So I came up with the idea of refactoring to a base class e.g. `Handler`.
The according log message could be an instance variable as well as `payload_schema` - which in itself could be a constructor parameter (if wanted).

Besides:  

* `ActionsHandler`
* `PresenterHandler`
* `RestrictionsHandler`

each have an `Interface`. How does the interface relate to the implementing classes?

If I wrote Java, I would end up with something like `implements $Interface`.
Having Python, I supposed to find something like `ActionsHandler(Actions)` (read: "implements the actions interface") or after the suggested refactoring `ActionsHandler(Handler)` where handler would itself be a class implementing the `handler` interface.

**Comment by normanjaeckel** [comment]
@ThomasJunk: Are you still in office for a short phone call?

**Comment by normanjaeckel** [comment]
Using a abstract Handler class is possible, but I think this has no priority because we only have these three handlers (maybe 4, but not 10).

I am not sure but I think for implement an interface which is build with the `Protocol` class you do not have to subclass from this interface. The magic is done in the view classes where Mypy can check that `ActionsHandler` is an implementation of `Actions`. But as I wrote I am not sure what is Pythonic best practice.

**Comment by ThomasJunk** [comment]
@normanjaeckel On fridays I leave office at 13:30 / 14:00. 

> because we only have these three handlers (maybe 4, but not 10)
ACK. Valid point.

> But as I wrote I am not sure what is Pythonic best practice.
Neither am I.

Up till last week I haven't encountered active usage of interfaces in Python. I saw something similar used in the context of [zodb](http://www.zodb.org/en/latest/reference/storages.html) which was used in the `Pylons` framework which found partially its way into `Pyramid`. But there it was used internally.

Interfaces in Python feel strange from my POV.

So I am leaving it at that and close the issue.
