### ISSUE TITLE
Someone has to look at the "required" case again (using on_delete flag or required flag in update cases).

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#319]
see https://github.com/OpenSlides/openslides-backend/pull/300#discussion_r522984749

**Comment by jsangmeister** [comment]
What's the status here? Can this be closed?

**Comment by normanjaeckel** [comment]
Not yet.

**Comment by normanjaeckel** [comment]
To describe, what has to be done here:

We have the on_delete flag in models.yml to prevent deleting models where we do not want the respective relations set to an empty value (I think this is only relevant for m:1 and 1:1 relations but I am not completely sure).

The question is whether we also have a working protection in update cases. If someone updates object A and sets a relationla field to another value we have to care that the related field in object B is not set to None (or empty list?), if the field should to be empty according to the business logic.

Someone has to check if we have a working protection either by using the on_delete flag or by using the required flag. For example it should not be possible to change a value where the related field is required and would be made empty.

Do you understand what I mean?
