### ISSUE TITLE
Restructure action handling and implement transaction models

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#325]
I would like to restructure the general workflow of an action to make it more clear what is happening at each point in the code. The split in `prepare_dataset` and `create_write_request` is unintuitive and not necessary, IMO. Also, it is not clear what a `dataset` even is or what fields it must/should have, since the type declaration contains an `Any` and every time I tried to explain it to someone (@reiterl, @r-peschke), I failed to formulate the point of it.

Also, the second point: I talked with Finn and as previously (loosly) discussed in #27, we need some kind of transaction flag for our actions. In case of an import, we want to execute as many payloads as possible and return errors for the rest. In most other cases, it might be fine to raise an error if anything failed and execute nothing. The easiest way to handle this is to include this in the restructure and make the action code independent from the chosen model. Then, this can easily be done in the base action and transmitted via a simple flag in the payload.

So, here is my suggestion of the workflow in the base action (to be more precise, the `perform` function in `openslides_backend/action/base.py`). The current code looks like this:
```
self.user_id = user_id
self.validate(payload)
self.check_permissions(payload)
dataset = self.prepare_dataset(payload)
yield from self.create_write_request_elements(dataset)
```
My suggestion would be something among the lines of:
```
self.user_id = user_id
self.check_permissions(payload)
# validate now only checks the general form of the payload: that it is an array of objects.
self.validate(payload)
instances = self.get_updated_instances(payload)
for instance in instances:
    self.validate_instance(instance)
    self.update_instance(instance)  # can be overwritten by CreateAction etc. to set defaults, validate relations etc.
    yield self.create_write_request_element(instance)
```
Since we use `update_instance` etc. everywhere, it should be better to just include it in the base action. We get rid of the ominous `DataSet` and the code becomes more cleaner, readable and understandable and it becomes easier to implement the two different transaction methods.

It may become necessary for the actions to be state aware and save previous results in some field. Example: When importing users, the successful imports (which are not yet written to the datastore) have to be checked to make sure a username is not added more than once. The schema could easily be amended for this.

What do you think, whom it may concern?

**Comment by normanjaeckel** [comment]
This approach is ok for me. At the beginning of the life of this code I thought we should differenciate between two phases: first get all stuff from db which is necessary to calculate the new model, second the method to create the events that should be send out. At this point the `DataSet` was born. We can let it die now if you like ... ;-)

**Comment by FinnStutzenstein** [comment]
We also schould think about the handling of locked fields and positions. Maybe not in this restructure, but we should not block this feature. Maybe just have it in your mind. For me, this sounds reasonable.
