### ISSUE TITLE
Prevent replacement beginning with underscore

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#330]
When using a structured field with structured tag it is invalid to use a tag that starts with an underscore.

Find out all places where the client may set such an invalid tag and add checks that prevent this case.

**Comment by jsangmeister** [comment]
Can't we just add this check in the `get_replacement` method which you added in #328? This should be the go-to place to fetch the replacement.

**Comment by jsangmeister** [comment]
Also, we should document that this is forbidden. @FinnStutzenstein is the pattern for the replacement already documented somewhere and can you add this there?

**Comment by jsangmeister** [comment]
(Btw, if we would have gone the route of using `...$<replacement>$...` instead of `$<replacement>...` this would not be an issue... ;))

**Comment by FinnStutzenstein** [comment]
Hab den ursprünglichen Emailinhalt mal in die Wiki gekippt: https://github.com/OpenSlides/OpenSlides/wiki/DE:-Templatefelder
