### ISSUE TITLE
`motion/last_modified` has to be updated on every change

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#344]
Currently, this is only done on update. This has to be extended to every changing request. Missing actions:
- verify: `update` and `update_metadata`.
- verify: `create`
- `set_state`/`reset_state`
- `set_recommendation`/`reset_recommendation`/`follow_recommendation`
- `motion_category.number_motions` (Since motion numbers are updates -> may be done in the set number mixin.)

This is not done on sorting (`motion.sort`, `motion_category.sort_motions_in_category`) since this field should only be updated, if something relevant (content, matadata like category, block, ... or state) changes.

**Comment by reiterl** [comment]
`motion_category.number_motions` is still missing.

**Comment by reiterl** [comment]
Opened PR https://github.com/OpenSlides/openslides-backend/pull/357 for this.
