### ISSUE TITLE
Add check_resource_id presenter

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#346]
The presenter is called with this payload: `{resource_id: <id>;}` and returns

- `{"ok": True, "filename": <filename>}`, if the resource exists. `filename` is concatinated from the resources `token` and the file extension given by the resources mimetype (e.g. `image/jpg` -> `.jpg`).
- `{"ok": False}`, if the resource does not exist

Note, that no permission cheks are done. It is only checked, if the resource exists.

**Comment by reiterl** [comment]
Opend PR https://github.com/OpenSlides/openslides-backend/pull/369 for this.
