### ISSUE TITLE
Check actions for locked_fields/race-conditions with relations and parallel actions in payloads

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#351]
Im Prinzip geht es um das Überprüfen des Field-Lockings, das bisher weitgehend nicht benutzt wurde.
Konkret geht es 

1. um das Verhalten bei Relationen und
1. bei mehreren parallelen Aktionen innerhalb eines Payloads

Ziel des Issues ist es dabei, auszuloten, welche Logik und welche Tests fehlen und die, je nach Aufwand, möglichst generisch zu erstellen.

### Bei jedem Create muss ein collection/max als Feld gelocked werden
So könnte über das Retry eine neue, gültige id vergeben werden. >Checken, wie die id-Vergabe jetzt aussieht bei mehreren Creates in einer Action oder mehreren Paralleln Actions

## Done
- Retry im Action_Handler für DatastoreModelLockedException
- In einem Testthread aufgetretene Assertions können mit spezifischen thread-Assert-Methoden behandelt werden. Grundsätzliches Raisen im thread.join nicht möglich, da dann laufende Threads unerreichbar sind 
- Adapter filter-Methode: Zusätzliches locked_field auf Collection/max, um neu hinzugefügte Werte zuerkennen
- Adapter-Methode get_lock_position_for_collection_id liest per max-Command den Position Wert einer Collection/id. Übergangsweise beim Filter eingesetzt.
 
### Tests
- Test für motion.sequence_number mit Race Condition
- Test für motion_category Sortierung Motion innerhalb einer Kategorie
- Test für motion_category Baumsortierung motion-Kategorien
- ListOfSpeakersReAddLastActionTest.test_correct
Test läuft durch mit modifizierter Ermittlung des position-Wertes für das Kollektionfeld speaker/id mittels der Methode get_lock_position_for_collection_id.
- Generische Test von RelationField und RelationListField

**Comment by r-peschke** [comment]
I stop this issue for the moment, because we have to resolve some problems.
The handling of relations, using more than 1 action in a payload ist not working as expexted, see failing tests:
The pattern of failing is the following:
- Action 1 change an object 1
- Action 2 changes in any way data of object 1 again, but without knowing and respecting the changes of action 1. As a result there are remaining field values of the backward relation.

Some possible solutions (without deep knowledge of datastore):

1. We could use the existing **SingularActionMixin** on all models with relations. It's easy and rapidly done. Drawback: We are loosing the ability of speed up by combining actions in 1 payload
2. The backend could check the payload for reusing objects and related objects in other actions and stops further processing only in such cases. Maybe not that simple
3. The datastore could reread the locked_fields positions after each action and check again the locked fields.
4. Following the 3 it could also reread the data and buil the write_request_elements for following actions. Drawback: Slow, complicated and duplicated code, because this logic, including business logic, is implemented in the backend.

I hope there are better ideas from people that better know the existing concepts :-)

**Comment by normanjaeckel** [comment]
@ostcar Please help.

**Comment by normanjaeckel** [comment]
Maybe the solution is to use something like the `additional_relational_models` (https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/action.py#L85). If an action has to perform multiple elements results of previous calculations regarding relational models have to be injected in the following calculations. The same if multiple actions are given in one request.

**Comment by r-peschke** [comment]
>>  If an action has to perform multiple elements results of previous calculations regarding relational models have to be injected in the following calculations.
This is done by the business logic in the backend and results in a write_request_element, that includes a set of necessary "atomic" database instructions.
>> The same if multiple actions are given in one request.
This is really difficult on the backend, because it has to calculate the results of the preceding actions without processing them, including the changed metaset-positions for locked_fields. The logic of the latter is blackboxed in the datastore.

To do it the other way round the datastore needed to know the business logic of building the "atomic" database instructions.

**Comment by jsangmeister** [comment]
The question is, do we need this feature? I can't imagine a situation where one would want to send a single request with 2 actions which both change the same model. In almost all cases the actions are send seperately, anyway. Maybe someone else has more imagination than me, but I'd suggest to just forbid this kind of double update until we need it. This should be simple to check by iterating over the WREs at the end of each request.

__If__ we do need this feature, I would agree with @normanjaeckel that the  `additional_relation_models` would be the way to go.

Btw, this error does only apply for fields which are changed directly by an action. Reverse relation fields which change as a result of an action should be handled automatically and correctly by the `RelationManager`.

**Comment by r-peschke** [comment]
Proposal for solution:  We should group the resulting `WriteRequestElements` and it's `locked_fields` on a per `Action`-base. Then the `DataStore` should check the `locked_fields` also on a per `Action`-base after processing the predecessor-`Action`. That is exactly what happens, if we post only 1 Action per request.

**Comment by normanjaeckel** [comment]
Please discuss this topic on code sprint tomorrow.

**Comment by jsangmeister** [comment]
Just talked with @FinnStutzenstein about this and we came to the conclusion that we don't need this feature at the moment. I'll open an issue for this.

**Comment by FinnStutzenstein** [comment]
> I'll open an issue for this.
Still open ;)

**Comment by jsangmeister** [comment]
Whoops, my bad

**Comment by FinnStutzenstein** [comment]
I'll close this for the sake of an overview
