### ISSUE TITLE
Implement the "point of order" feature from OS3

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#352]
(Documentation follows...)

**Comment by jsangmeister** [comment]
@FinnStutzenstein ping ;)

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/openslides-backend-coordination/issues/84 together with https://github.com/OpenSlides/openslides-backend-coordination/wiki/List-of-speakers#point-of-order should be ok. There might be a lack of context since all other parts of LOS are not documented...

**Comment by r-peschke** [comment]
Proposal: We should remove the meeting_id from Speaker-model. 
Motivation: It's redundant (List_of_speakers with meeting_id is required for speaker and immutable) and error-prone (redundant information always has to be kept synchronous). 
As a side-effect we will win 
- velocity (lot of updates for relation speaker<->meeting)
- easier model understanding (less relations)

**Comment by r-peschke** [comment]
Question:
The new **point-of-order** -speaker get's the lowest weight, but datastore add it on last position. Where/when is the sorting done?

**Comment by FinnStutzenstein** [comment]
> Where/when is the sorting done?

The sorting is done in the client. The client does not know about positions (if you mean the DS positions for locking) and they are not part of the actual model data. (Analog: The new poo speaker gets the highest id, but is sorted on top)

**Comment by FinnStutzenstein** [comment]
> Proposal: We should remove the meeting_id from Speaker-model.

Please open a new issue for these discussions ;)

**Comment by ostcar** [comment]
> Proposal: We should remove the meeting_id from Speaker-model.
> Motivation: It's redundant (List_of_speakers with meeting_id is required for speaker and immutable) and error-prone (redundant information always has to be kept synchronous).
> As a side-effect we will win
> 
>     * velocity (lot of updates for relation speaker<->meeting)
> 
>     * easier model understanding (less relations)

The permission-service uses speaker/meeting_id. It would be easy to change it to use speaker/list_of_speakers_id -> list_of_speakers/meeting_id. Please inform me, if you chang eit

**Comment by r-peschke** [comment]
> > Proposal: We should remove the meeting_id from Speaker-model.
> > Motivation: It's redundant (List_of_speakers with meeting_id is required for speaker and immutable) and error-prone (redundant information always has to be kept synchronous).
> > As a side-effect we will win
> > ```
> > * velocity (lot of updates for relation speaker<->meeting)
> > 
> > * easier model understanding (less relations)
> > ```
> 
> The permission-service uses speaker/meeting_id. It would be easy to change it to use speaker/list_of_speakers_id -> list_of_speakers/meeting_id. Please inform me, if you chang eit

The idea now is to keep with speaker/meeting_id, but remove meeting/speaker_ids. For further discussion/action see #417

**Comment by GabrielInTheWorld** [comment]
What is the status here?

**Comment by jsangmeister** [comment]
Almost done - see linked PR.
