### ISSUE TITLE
Assert equal fields for users

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#365]
Since we can't use the default `equal_fields` setting in the `models.yml` for user related fields since they might not have a `meeting_id`, we have to check this manually. So we should write a mixin which can be called in every action which edits such user related fields and checks that the user is in the meeting's `user_ids`. (not directly, this would be too inefficient, but instead through the reverse relations on user).

**Comment by FinnStutzenstein** [comment]
@jsangmeister Are you working on this? It seems that this issue becomes more urgent

**Comment by jsangmeister** [comment]
Yes, I've noticed ;) I started last week, will continue today.
