### ISSUE TITLE
Automatic removal of supporters

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#366]
See https://github.com/OpenSlides/openslides-backend-coordination/wiki/Motions#updating-a-motion-motionupdate-and-motionupdate_metadata

@FinnStutzenstein: Does the backend have to check these things (especially the permission) or is this done by the permission service and returned in its response?

**Comment by FinnStutzenstein** [comment]
All checks are done in the backend except for the permission check. There is an additional infomration returned by the permission service (https://github.com/OpenSlides/openslides-permission-service/issues/39) that indicates, whether clearing supportes may be done.

**Comment by jsangmeister** [comment]
We do not need this feature anymore.
