### ISSUE TITLE
Use read_only in schema

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#383]

**Comment by reiterl** [comment]
I need more description here, in which schema should that be used. As far as I know is, that the fields use the read_only flag.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Please provide a better explaination, so others can work on this issue

**Comment by normanjaeckel** [comment]
The idea is to check in schema creation if a field has the read_only flag. If yes it should be prohibited to use such a field e. g. via default_schema or update_schema. It is just a helper for developers.

**Comment by jsangmeister** [comment]
To be more precise: Currently, the field lists given to the default schemas are just inserted into the schema without any checks. We want to make it such that for update schemas, every field is checked if it is marked as `read_only`. If it is, an internal programming error happened, since such fields can't be updated from the client side.

**Comment by normanjaeckel** [comment]
> We want to make it such that for update schemas

I think this check is useful for all schemas, also create and default schemas.

**Comment by jsangmeister** [comment]
> > We want to make it such that for update schemas
> 
> I think this check is useful for all schemas, also create and default schemas.

You're right.

**Comment by r-peschke** [comment]
What does read_only mean? Usually I think, it should prevent the user from setting a field. In consequence it should be read_only in the UI. The system itself has to be able to set the field, including the client.

**Comment by jsangmeister** [comment]
> What does read_only mean? Usually I think, it should prevent the user from setting a field. In consequence it should be read_only in the UI. The system itself has to be able to set the field, including the client.

You're partly right: `read_only` means in this context that the client must not be able to write to this field. So we need a check in the `default_schema.py` that prevents inserting `read_only` fields into any payload schema.
