### ISSUE TITLE
Adjust WriteRequest handling to a per-action basis

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#397]
see https://github.com/OpenSlides/openslides-backend/issues/351#issuecomment-756017945

We need a way to prevent the possibility of inconsistent data. The problem description can be found here: https://github.com/OpenSlides/openslides-backend/issues/351#issuecomment-749629456. We should save all fields that are changed directly by an action in each request (not relation field which are updated indirectly, since the handling of these works). If a second action in the same request tries to
- get the field
- call any aggregate function (min/max/exists/filter) with this field
- (...anything else?)
the whole request has to be cancelled. This should probably be added to the datastore adapter to direct interfere in the corresponding methods.

**Comment by FinnStutzenstein** [comment]
> This should probably be added to the datastore adapter

Note: I would prefer some wrapping class, maybe not even extending the adapter, but like onion-wrapping. At least as the code for the adapter grows, the functionallity should be devided into multiple files/classes.

**Comment by r-peschke** [comment]
## Fall1: Ohne Thread 2 Aktionen in einem Request
### Wenn beim Lesen noch nicht da, dann wird das vom Relation Handler auch nicht bemerkt: Test test_create_rel_1_to_n_AB_error1
Daten einrichten:
ID: fake_model_rrc_a/1 Type:create Fields: {'id': 1}
ID: fake_model_rrc_b/1 Type:create Fields: {'id': 1}
ID: fake_model_rrc_b/2 Type:create Fields: {'id': 2}

Update:
ID: fake_model_rrc_a/1 Type:update Fields: {'rn_b_ids': [1, 2]}  action1
ID: fake_model_rrc_b/1 Type:update Fields: {'r1n_a_id': 1}        relation handler
ID: fake_model_rrc_b/2 Type:update Fields: {'r1n_a_id': 1}        relation handler
ID: fake_model_rrc_a/1 Type:update Fields: {'rn_b_ids': [2]}      action2
ID: fake_model_rrc_b/2 Type:update Fields: {'r1n_a_id': 1}        relation handler
Fehler: b/1 enthält noch den Verweis auf a/1, aber nicht umgekehrt, da der RelationHandler im Auflösen von Aktion2 nichts von der Beziehung A1->B1 weiß

### Wenn vorher alle Daten bekannt sind, funktioniert es. Test: test_create_rel_1_to_n_AB_error2
Daten einrichten:
ID: fake_model_rrc_a/1 Type:create Fields: {'rn_b_ids': [1, 2, 3], 'id': 1}
ID: fake_model_rrc_b/1 Type:create Fields: {'r1n_a_id': 1, 'id': 1}
ID: fake_model_rrc_b/2 Type:create Fields: {'r1n_a_id': 1, 'id': 2}
ID: fake_model_rrc_b/3 Type:create Fields: {'r1n_a_id': 1, 'id': 3}

Update:
ID: fake_model_rrc_a/1 Type:update Fields: {'rn_b_ids': [1, 2]}    action1
ID: fake_model_rrc_b/3 Type:update Fields: {'r1n_a_id': None}   relation handler
ID: fake_model_rrc_a/1 Type:update Fields: {'rn_b_ids': [2]}        action2
ID: fake_model_rrc_b/1 Type:update Fields: {'r1n_a_id': None}   relation handler
ID: fake_model_rrc_b/3 Type:update Fields: {'r1n_a_id': None}   relation handler
Jetzt funktioniert es, sogar mehrfach, da der RelationHandler die Beziehungen A1->B1 und A1->B3 kennt.

## Fall2 Ohne Thread, n:m-Beziehung
Daten einrichten:
ID: fake_model_rrc_a/1 Type:create Fields: {'id': 1}
ID: fake_model_rrc_a/2 Type:create Fields: {'id': 2}
ID: fake_model_rrc_a/3 Type:create Fields: {'rnn_b_ids': [1], 'id': 3}
ID: fake_model_rrc_b/1 Type:create Fields: {'rnn_a_ids': [3], 'id': 1}
ID: fake_model_rrc_b/2 Type:create Fields: {'id': 2}
Stand: a1->-; a2->-; a3->b1  b1->a3; b2->-
Update:
ID: fake_model_rrc_a/1 Type:update Fields: {'rnn_b_ids': [1, 2]} Aktion1
ID: fake_model_rrc_b/1 Type:update Fields: {'rnn_a_ids': [3, 1]} RelationHandler, okay, die bestehende 3 wird erkannt
ID: fake_model_rrc_b/2 Type:update Fields: {'rnn_a_ids': [1]}     RelationHandler
ID: fake_model_rrc_b/1 Type:update Fields: {'rnn_a_ids': [1, 2]} Aktion2
ID: fake_model_rrc_a/3 Type:update Fields: {'rnn_b_ids': []}       RelationHandler, okay, Rel a3->b1 wird entfernt
ID: fake_model_rrc_a/2 Type:update Fields: {'rnn_b_ids': [1]}     RelationHandler
ID: fake_model_rrc_a/1 Type:update Fields: {'rnn_b_ids': [1]}     RelationHandler, falsch,  da a1->b2 aus Aktion1 entfernt wird
Stand: a1->b1, a2->b1, a3->-   b1->a1, a2; b2->a1
Die in Aktion1 hinzugefügte Relation a1->b2 ist dem RelationHandler in Aktion2 nicht bekannt,weshalb a1->b2 entfernt wird, b2->a1 jedoch bestehen bleibt.

**Comment by jsangmeister** [comment]
Update: will move this change to the datastore. Changes needed in the backend:
- Send exactly one `WriteRequest` per action
- Send `locked_fields` per action with each write request
