### ISSUE TITLE
Proposal: Switch merge method to "Squash and merge"

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#404]
@ostcar mentioned during the code sprint that the autoupdate service uses this method and the more I look at it the more convinced I am. There are a few advantages:
- The biggest: We don't have to manually squash, force push and wait for github actions to run again
- PRs with multiple authors (albeit seldom in this repo) are easier to manage
- No informations are lost because in the original branch, all commits still retain in the unsquashed form

The only drawback I see is that we no longer have merge commits, but I don't really see that as a drawback; it would only make the commit history cleaner.
Any thoughts?

**Comment by normanjaeckel** [comment]
Ok, for me if the single commit messages contain useful information. Sometimes we code with messages like "Step" or "Fix" which is not useful to have inside the big commit message of the squashed commit.

**Comment by ostcar** [comment]
When you click on "smash and merge" on github, you get the possibility to alter the commit message of the new commit.

**Comment by FinnStutzenstein** [comment]
ok for me

**Comment by jsangmeister** [comment]
Nice, I disabled the other options for now. If anyone needs another merging method, we could enable them again, but I think to prevent everyone from forgetting it's better to leave it disabled :)
