### ISSUE TITLE
Fix typo and update models.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#408]
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/actions/meeting/create_update_delete.py#L93

After https://github.com/OpenSlides/OpenSlides/pull/5802 is merged we have to update models and fix this typo.

**Comment by reiterl** [comment]
The OS4 PR #5802  is merged. Try to fix the typo.

**Comment by FinnStutzenstein** [comment]
Whats the status here?
