### ISSUE TITLE
Do not send exception messages from permission service to client.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#409]

**Comment by reiterl** [comment]
I think this is a permission service issue, because it is the sender and should be fixed.

**Comment by FinnStutzenstein** [comment]
No, the error should be logged, but not forwarded to the client.

**Comment by reiterl** [comment]
I think the code is in `PermissionHTTPAdapter`. Here the `PermissionException` gets to much information.
I added error logging and striped the `PermissionEexception` messages.
Add PR https://github.com/OpenSlides/openslides-backend/pull/426 for this.
