### ISSUE TITLE
Datastore adapter

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#41]
The datastore adapter has to be written.

**Comment by FinnStutzenstein** [comment]
Clarification: In the business logic it can be the `DatabaseInterface` but it is definitly the `DatatoreAdapter`.

**Comment by ThomasJunk** [comment]
I assume 
[this specification](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/datastore-service.txt) as the basis, right?

And [this](https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/services/database.py) as the target of the implementation?

What is the expectation here? 
Replication of the interface contract as an actual `interface` and implementation via the concrete class? 

As far as I can see
`exists`, `filter`, `get`, `getId`, `getMany` are existant.
`count`, `min` `max` are missing in the actual implementation.

Is the specification up to date?

**Comment by FinnStutzenstein** [comment]
The sepc is nearly up to date, see https://github.com/OpenSlides/OpenSlides/pull/5342 for small changes

**Comment by normanjaeckel** [comment]
Be aware that the existent implementation does contain only some dummy values or just raise errors ...

**Comment by ThomasJunk** [comment]
> Be aware that the existent implementation does contain only some dummy values or just raise errors
Yes. I chose to write »existant« instead of »implemented« to reflect that ;)

**Comment by ThomasJunk** [comment]
This issue has #27 as a prerequisite.
So I am deferring this to the point when the discussion on #27 settled

**Comment by FinnStutzenstein** [comment]
@ThomasJunk is this the wrong issue? Did you mean the action result issue?

**Comment by ThomasJunk** [comment]
I made a pull request for this [over here](https://github.com/OpenSlides/openslides-backend/pull/44).
I added for a first draft subs. The concrete implementation will follow.

**Comment by ThomasJunk** [comment]
I started decoupling the database layer from its HTTP part, such that it is possible to

a) unit test database stuff independently from doing actual requests

b) separation of concerns: database layer doing database things and throwing database errors instead of dealing with HTTP errors

When separation is complete we could unit test it as a single unit and integration test it with its HTTP-Engine active.

**Comment by normanjaeckel** [comment]
The adapter exists now. Maybe it is buggy but this is part of separate issues.
