### ISSUE TITLE
Add action to update organisation

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#411]
This might be one of the last missing actions.

**Comment by normanjaeckel** [comment]
Who wants to do this?

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Please specify a playload as done with all other actions and maybe point out additional things this action should do.

**Comment by normanjaeckel** [comment]
Payload:
```
{
  id: number
  name: string
  description: HTMLStrict

  # Settings (configurable by the client)
  legal_notice: string
  privacy_policy: string
  login_text: string
  theme: string
  custom_translations: JSON
  reset_password_verbose_errors: boolean
}
```

**Comment by normanjaeckel** [comment]
Id is required (but only for unification because id is always 1)

**Comment by jsangmeister** [comment]
Also, please don't assign people randomly (related to the email from @FinnStutzenstein). The backend people see all issues tagged as `backend` and will assign them themselves.

**Comment by reiterl** [comment]
Add pull request https://github.com/OpenSlides/openslides-backend/pull/425 for this.
