### ISSUE TITLE
Remove backward-relations to meeting from models listed in https://github.com/OpenSlides/OpenSlides/pull/5620

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#417]
We have a lot of relations between a model an meeting, which are not useful and necessary, for instance speaker.
The speaker belongs to a list-of-speakers, which belongs to a specific meeting. 
See the proposal of removing the speaker-meeting-relation: https://github.com/OpenSlides/openslides-backend/issues/352#issuecomment-765479036

We want to remove the backward relation from meeting to the models from https://github.com/OpenSlides/OpenSlides/pull/5620, where they aren't necessary and keep only with the relation from the given model to meeting. This way we are still consistent with meeting_id in each dependent model, for instance for user/speaker_$_ids with replacement meeting_id.

**Comment by ostcar** [comment]
Could you create a diff (or pr) which fields would be removed? I won't to check which field are necessary for the permission-service

**Comment by FinnStutzenstein** [comment]
Oskar: 

> The permission-service uses speaker/meeting_id. It would be easy to change it to use speaker/list_of_speakers_id -> list_of_speakers/meeting_id. Please inform me, if you chang eit

**Comment by normanjaeckel** [comment]
Hm. I think this would again a new inconsitency and a lot of work. I do not see the advantage of not having some backwards relations. Either we have all or none I think.

**Comment by jsangmeister** [comment]
> Hm. I think this would again a new inconsitency and a lot of work. I do not see the advantage of not having some backwards relations. Either we have all or none I think.

The advantage would be that we have a lot less updates on the meeting which have to be resolved and could make the requests a little faster and less error prone. But I'm not totally sold on it, either. We could keep it as-is for now and keep this in the backlog if we run into problems regarding this.

**Comment by FinnStutzenstein** [comment]
With the concept of OCC in the datastore, this allows for concurrent speaker creations of different LOS

**Comment by normanjaeckel** [comment]
If it is only about concurrency and speed I would prefer to let things as is for the moment because I think we wont get problems with action speed.

**Comment by jsangmeister** [comment]
> If it is only about concurrency and speed I would prefer to let things as is for the moment because I think we wont get problems with action speed.

I agree, this is low priority currently. We can move this to the back of the backlog ;)

**Comment by jsangmeister** [comment]
I will close this for now because I don't think it brings any real advantage and messes with the existing relation handling. Regarding the OCC argument: We could change the relation handling to use the new list updates, so this can be made possible. If we want, we can create a new issue for this.
