### ISSUE TITLE
Check motion number update code

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#418]
`motion.set_state`, `motion.reset_state` and `motion.follow_recommendation`: The number updating code has to executed: https://github.com/OpenSlides/openslides-backend-coordination/wiki/Motions#updating-the-number Check, if this is done

**Comment by jsangmeister** [comment]
@r-peschke Did you do this with #415? Or just for `motion.set_state`? If the latter, can you do that for the rest as well?

**Comment by r-peschke** [comment]
Next week! With #415 I solved only https://github.com/OpenSlides/openslides-backend-coordination/issues/105

**Comment by r-peschke** [comment]
Action follow_recommendation doesn't execute the set_number-method
