### ISSUE TITLE
Refactoring of handlers to a common base class

### ISSUE THREAD

**Issue by ThomasJunk** [OpenSlides/openslides-backend#43]
I took the hint from @FinnStutzenstein and @normanjaeckel to improve the situation of the `handlers`.
In order to leverage (constructor based dependency injection), I created a common base class with a constructor taking the dependencies so far. See:

https://github.com/OpenSlides/openslides-backend/pull/40/commits/37d88fca9da06527257d44eea8bebf66562f94a0

**Comment by normanjaeckel** [comment]
Done by #40
