### ISSUE TITLE
Problem with retry in the handle_request

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#440]
We should pass the retry-counter to the ActionClass.
For instance we should avoid to upload a file, which is successfully loaded, in each retry, because of locked fields.
See in resource/test_upload.py on TODO-comment .
Maybe there are more parts, which shouldn't be retried.

**Comment by jsangmeister** [comment]
This goes in the same direction as the other issue where a mediafile whose request fails at a later time is not deleted. I think these kind of orphans are ok for now since it should happen that often. When we run into storage/runtime problems because of this, we can think about solutions for this.

**Comment by FinnStutzenstein** [comment]
Another solution: One can flag an action as not idempotent -> retries should not be done, if this flag is set.

**Comment by jsangmeister** [comment]
> Another solution: One can flag an action as not idempotent -> retries should not be done, if this flag is set.

Seems like unnecessary user interaction: If we don't retry the action, the user will see an error and (probably) manually resend the action. So the file is uploaded again in either case.

**Comment by FinnStutzenstein** [comment]
ok

**Comment by jsangmeister** [comment]
closing this as it does not seem to be a problem which needs fixing
