### ISSUE TITLE
Transfer voting tests from OS3

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#444]
Voting is currently only tested rudimentarily. OS3 has a multitude of tests for this (https://github.com/OpenSlides/OpenSlides/blob/master/server/tests/integration/assignments/test_polls.py). A few are also in https://github.com/OpenSlides/OpenSlides/blob/master/server/tests/integration/motions/test_polls.py but these are not as relevant since we only have polls now (= old assignment polls).

These tests have to be reimplemented in OS4 to detect and fix possible errors in the voting code. Maybe one can create a small script (or maybe even a list of regexes?) to automatically transform all tests - this would probably the easiest way.

**Comment by reiterl** [comment]
Okay, I'm looking at this for 3 hours. I cannot transfer the tests. The OS3 code is to different from OS4.

**Comment by reiterl** [comment]
The OS3 is different then the OS4 code. I don't think full automated transfer is possible. I count ~180 tests. So manual transfer them, would cost a lot of time.

**Comment by FinnStutzenstein** [comment]
> The OS3 is different then the OS4 code

This was my feeling, too. So yes - manual work is required.

**Comment by reiterl** [comment]
I continued to transfer the tests from OS3. I have following questions:
* How do `votesvalid`, `votesinvalid`, `votescast `work?
* Is poll.anonymize only allowed in State Finished?
* Is not poll.anonymize allowed in type Analog?

**Comment by FinnStutzenstein** [comment]
> How do votesvalid, votesinvalid, votescast work?

https://github.com/OpenSlides/openslides-backend-coordination/wiki/Voting#poll-results

> Is poll.anonymize only allowed in State Finished?

yes

> Is not poll.anonymize allowed in type Analog?

yes, only for electronic voting methods

> Should a vote object be created for a "1":0 entry in value?

No

> What should happen with negative numbers in value ("1":-1)?

Error, they must be >=0 (with ignoring 0)
