### ISSUE TITLE
Validate vote delegations

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#445]
The vote delegations are subject to a few rules, e.g. that one cannot delegate a vote to himself, not build circles etc. The main parts of the OS3 implementation can be found [here](https://github.com/OpenSlides/OpenSlides/blob/09bc7f093a8b628ef87653d626fdc8597df71501/server/openslides/users/views.py#L179) (and ff). Also, there are quite a few tests for this (e.g. https://github.com/OpenSlides/OpenSlides/blob/09bc7f093a8b628ef87653d626fdc8597df71501/server/tests/integration/users/test_viewset.py#L236, just search for `vote_delegation`) which should all be working in OS4, too.
See also [wiki:user in vote objects](https://github.com/OpenSlides/OpenSlides/wiki/Voting#user-in-vote-objects)

**Comment by r-peschke** [comment]
There are 4 actions involved: `user.create`, `user.update`, `user.create_temporary` and  `user.update_temporary`. The existing one's in the wiki neither have a `vote_delegations_$_from_ids` nor a `vote_delegated__to_id` defined in payload.
In source code we have `vote_delegations_$_from_ids` in user.create and user.update, `vote_delegations_from_ids` as additional_optional_fields in the temporary_user variants.
For now I use the `vote_delegations_$_from_ids`, the other way around will not be possible to set. Is this sufficient and shall we add this to the wiki-description of payload?

**Comment by r-peschke** [comment]
In OS3 you can replace a delegation to an other user with one request (autoupdate). In OS4 this is usually not allowed (message: You can not set user/3/vote_delegated_$222_to_id to a new value because this field is not empty.). Should we implement this kind of change or should the client reset and set in 2 actions as in other places?

**Comment by FinnStutzenstein** [comment]
The `user.create` and `user.create_temporary` (same for update) should behave equally, so I'll only refer to `create`/`update`.[1]

The client **needs** to set both, so `vote_delegations_$_from_ids` and `vote_delegated_$_to_ids` must be settable in some way, but in one request.

> Should we implement this kind of change

The message sounds generic - I assume you cannot set a O2O relation to a model with this relation set? E.g.:

```
A/foreign_id=null
A/foreign_reverse_id=null
B/foreign_id=C
B/foreign_reverse_id=null
C/foreign_id=null
C/foreign_reverse_id=B
```
Set `A/foreign_id=B` is currently not allowed, but this result may be acceptable (if allowed):
```
A/foreign_id=B
A/foreign_reverse_id=null
B/foreign_id=null
B/foreign_reverse_id=B
C/foreign_id=null
C/foreign_reverse_id=null
```

Maybe @jsangmeister Can have a look at it.

[1]: Only difference: The replacement (meeting_id) for temporary users can only be the meeting of the user.

**Comment by jsangmeister** [comment]
> The client **needs** to set both

Well, this is a new one. It was missing in every description of all the actions yet, so we didn't implement it...

> Maybe @jsangmeister Can have a look at it.

Ah yes, this is an old issue, see https://github.com/OpenSlides/openslides-backend/issues/161. We determined there that we did not have a situation yet were this would become necessary. **If** we really need to get automatic relation updates from both sides of this relation, this would be such a situation. So we have to ways to go here:

1. Implement this kind of automatic update. If the reverse field is set in such an update, we would need to set the related model of the old value to None. Sounds easy to to in theory, but without looking too much into it, this could mean a lot of work, because let's be honest, the relation handling code is kind of a mess ;)
2. Probably the easier way: Since we only need this feature in this specific use case, we could just catch this situation during validation and for all cases where `vote_delegated_$_to_id` is set in the action data instead set `vote_delegated_$_from_ids` on the related model (via `execute_other_action` for `create` or by returning another instance from `get_updated_instances`)

As you've probably noticed, I'm in favor of the second approach, but if someone wants to try to implement the first approach, it is probably he cleaner solution.

PS: Please note that this is an `1:m` relation (since @FinnStutzenstein wrote `vote_delegated_$_to_ids`). I just noticed that what I wrote [here](https://github.com/OpenSlides/openslides-backend/issues/161#issuecomment-734841375) is wrong - the same problem arises not only for `1:1`, but for any `1:*` relation if the `*` side gets updated. So I __think__ that we could also run into this problem with our current payload. But this can easily be fixed if you exchange each  `vote_delegated_$_to_id` with `vote_delegated_$_from_ids` and vice-versa in the second approach, since we only update the `1` side then.

**Comment by FinnStutzenstein** [comment]
> Well, this is a new one. It was missing in every description of all the actions yet, so we didn't implement it...

This was not a accusation, but a hint that is is needed in the way, that both sides of the relations must be settable. I think we postponed it due to it being a template relation and voting in general

> since @FinnStutzenstein wrote vote_delegated_$_to_ids

Yes, my mistake. I changes my comment

For me both ways are ok.

**Comment by jsangmeister** [comment]
> This was not a accusation

Yes, I know :D I just didn't hear of it until now
