### ISSUE TITLE
Move some fields from motion.update_metadata to motion.update

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#446]
see https://github.com/OpenSlides/openslides-backend-coordination/issues/65#issuecomment-773999739 and https://github.com/OpenSlides/openslides-backend-coordination/issues/25#issuecomment-773998888. @normanjaeckel has to clarify where the supporters belong.

**Comment by normanjaeckel** [comment]
Supporters are in both actions.

**Comment by reiterl** [comment]
As far as I understand: the supporter_ids should be updateable thru both actions.

**Comment by jsangmeister** [comment]
> Supporters are in both actions.

Why? It doesn't seem necessary, the client can just call the right action when the supporters are updated.

**Comment by FinnStutzenstein** [comment]
Ah I didn't see this issue. I stated something in https://github.com/OpenSlides/openslides-backend-coordination/issues/25

**Comment by jsangmeister** [comment]
see https://github.com/OpenSlides/openslides-backend/issues/487
