### ISSUE TITLE
Enhance action interface for permissions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#459]
Discussion thread for the integration of the permissions in the backend.

We can probably build it similarily to OS3: The base case is easy. Each action can define a class variable `permission`. The `check_permissions` function, instead of calling the permission service, can be enhanced to do a general check if the permission is granted and the action can be executed. For more complex/additional permission checks, the method can be overridden.

Thoughts?

**Comment by FinnStutzenstein** [comment]
Note: The `permission.yml` needs to be parsed and evaluated

**Comment by FinnStutzenstein** [comment]
Another thing for tests: https://github.com/OpenSlides/openslides-backend/issues/476 is important, the test setup needs to be more flexible in logging in users other than 1 - some util-methods may be helpful to quick-create users and assign groups and so on. This will be important testing permissions.

**Comment by normanjaeckel** [comment]
As discussed: I prefer generating some Python objects from permission.yml using a script (like we use generate_models.py). These Permission objects can be bundle together in something like a Permission service object that holds methods like "has_perm" and thelike.
