### ISSUE TITLE
Implement projector.delete

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#465]
https://github.com/OpenSlides/OpenSlides/wiki/Projection#projectordelete

**Comment by reiterl** [comment]
The field: `meeting/default_projector_$_id` is not in the model. Skip this code then.

**Comment by jsangmeister** [comment]
> The field: `meeting/default_projector_$_id` is not in the model. Skip this code then.

see #462: some fields were added/renamed

**Comment by reiterl** [comment]
Why is the `meeting/default_projector_$_id` a `TemplateRelationField`? What is the id I have to add behind the $?

**Comment by FinnStutzenstein** [comment]
the replacement is not an id, but a string (like the `meeting/logo_$_id` fields). These are the available replacements: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.yml#L844
