### ISSUE TITLE
What should be imported in __init__.py

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#47]
In actions module the https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/actions/__init__.py imports only the interface. The advantage is that one can import the module without "loading" all the stuff. The disadvantage is that we need an extra registry function which lives in https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/actions/actions.py#L14 at the moment.

In presenters module we go the other way https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/presenter/__init__.py and import everything in the init.

@FinnStutzenstein I remember that we talked about this and I choose the first way. @ThomasJunk choosed the second way.

Can we come to one way here?

**Comment by ThomasJunk** [comment]
> Can we come to one way here?

Yes. We should handle both cases consistent.

Currently I am in favour of neither solution. Yes you couldn't import the presenter module without subsequently filling the registry. But so far I do not expect downsides to this at the moment. Perhaps I am overlooking something here.

**Comment by FinnStutzenstein** [comment]
From an architectual sight the second approach is cleaner: https://moderatemisbehaviour.github.io/clean-code-smells-and-heuristics/#g7-base-classes-depending-on-their-derivatives

The actions.py module containing the base class should not know about derived actions. As you run the application, at one time all actions have to be loaded, so the point of time loading the actions doesn't matter.

I would prefer using the `__init__.py` as some kind of encapsulation: You may set up the rule, only to impoert from the `__init__.py` (https://moderatemisbehaviour.github.io/clean-code-smells-and-heuristics/#g36-avoid-transitive-navigation for modules). Why should a user of the actions module know, that there is a action module inside the action module with the implementation (e.g. here: https://github.com/OpenSlides/openslides-backend/blob/c27d56e444ca14de614e37659bf24f6c522f2e12/openslides_backend/http/views.py#L2)? A `from ..actions import ActionsHandler` is a cleaner encapsulation.

The last point are circular dependencies, which are introduces in the first appraoch. The actions module depends on a specific actions which again depends on the actions module. I think, this is the reason why you have to call a function to import the classes and this seems a bit strange.

**Comment by ThomasJunk** [comment]
Technical addition: 

In order to trigger the `decorator` closuers the according _module_ has to be loaded / imported.
For me the most convenient way was doing it during package initialization such that importing one thing from the package triggers the registry to be filled. 

In order to achieve the technical equivalent -of the subsequent loading to fill the registry - an _automatic invoked function_ is needed which executes on loading the module. So postponing the import postpones only the costs of said imports shifting from package to module.

**Comment by FinnStutzenstein** [comment]
I'll close this since it seems deprecated.
