### ISSUE TITLE
Add projector relations to meeting.update

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#473]
Check, if the relations

1. meeting/reference_projector_id
2. meeting/default_projector_$_id

are settable in `meeting.update`. Note that

- For 1.: It cannot be null
- For 2.: Only [these replacements](https://github.com/OpenSlides/OpenSlides/pull/5900/files#diff-85b0a31f7049307d71a5f45638c4e94b48a27026985d64891ac5c7be878d0b7eR844) are allowed and the relation cannot be null.

Write explicit tests for these fields.

Update the documentation here: https://github.com/OpenSlides/OpenSlides/wiki/meeting.update

**Comment by reiterl** [comment]
Looked at `meeting/create_update_delete.py`: I don't see code to set `reference_projector_id` or `default_projector_$_id` in the update action. 
The doc link links into the void.

**Comment by FinnStutzenstein** [comment]
Ok, I've updated the link. The `meeting.update` action has to be changed then.
