### ISSUE TITLE
Use the exec form for CMD

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#475]
https://docs.docker.com/engine/reference/builder/#cmd

Splitup from #450

**Comment by jsangmeister** [comment]
What's the advantage?

**Comment by FinnStutzenstein** [comment]
recommended - I wonder why Ralf had problems using the exec form, so I want to see why it might give problems and understand it.

**Comment by jsangmeister** [comment]
done with #539
