### ISSUE TITLE
Backend sets value '0' for undefined options

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#493]
I sent the following request to the backend:
```
[{'action': 'poll.create', 'data': [{'meeting_id': 1, 'title': 'Abstimmung', 'majority_method': 'simple', 'onehundred_percent_base': 'YNA', 'pollmethod': 'YNA', 'type': 'analog', 'options': [{'content_object_id': 'motion/3'}], 'content_object_id': 'motion/3'}]}]
```

In the client I received then the following data:
![Initial_0_Werte](https://user-images.githubusercontent.com/10206688/108817823-c5ece100-75b8-11eb-80fd-8efd45751c08.png)

![Initial_0_Werte_Autoupdate](https://user-images.githubusercontent.com/10206688/108818014-12382100-75b9-11eb-98e2-9ee2212ffe5d.png)

Please leave undefined values as undefined. :)

**Comment by FinnStutzenstein** [comment]
I would expect the values to be set to `-2` (undocumented).

**Comment by GabrielInTheWorld** [comment]
> I would expect the values to be set to `-2` (undocumented).

This is also a possible value.

**Comment by GabrielInTheWorld** [comment]
But I need here another value than '0'.

**Comment by FinnStutzenstein** [comment]
Ok, the default for analog votes should be -2. This has to be changed for all places special logic for analog polls exists.

**Comment by FinnStutzenstein** [comment]
@GabrielInTheWorld Please add the behaviour here: https://github.com/OpenSlides/OpenSlides/wiki/Voting#analog-polls

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld Please add the behaviour here: https://github.com/OpenSlides/OpenSlides/wiki/Voting#analog-polls

Done. I've updated the wiki.
