### ISSUE TITLE
meeting.create_from_template

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#494]
https://github.com/OpenSlides/OpenSlides/wiki/meeting.create_from_template

**Comment by jsangmeister** [comment]
Isn't this done with `meeting.clone`? Do we still need this action?

**Comment by jsangmeister** [comment]
> Isn't this done with `meeting.clone`? Do we still need this action?

It does not seem like it, so closing it for now.
