### ISSUE TITLE
user.merge_together

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#495]
https://github.com/OpenSlides/OpenSlides/wiki/user.merge_to_non_temporary

**Comment by jsangmeister** [comment]
> All reverse relations to the given temporary users must be changed to the new id of the created user.

This will be tricky to do, we'll have to circumvent the automatic relation handling for this case...

**Comment by reiterl** [comment]
Temporary users are deleted, while user restructure. So this issue is no longer needed. Or?
Just reopen it, if it is still needed.

**Comment by jsangmeister** [comment]
As far as I understood it, we will still need some kind of merge action, since the problem will persist: The same physical person can be created multiple times as a user in different meetings (because he is there as a guest or why not) and some time later, these users should be merged to one. Only the name changes, the needed aciton itself should be similar.

**Comment by FinnStutzenstein** [comment]
Right, [user.merge_together](https://github.com/OpenSlides/OpenSlides/wiki/user.merge_together) is the new name for the old action. The content is basically the same.

**Comment by reiterl** [comment]
The information in user.merge_together are outdated. We don't have temporary users anymore.

**Comment by tsiegleauq** [comment]
link to wiki
https://github.com/OpenSlides/OpenSlides/wiki/user.merge_together

**Comment by reiterl** [comment]
Mmh, we need to update the action description. I think we should wait until the template fields are gone, because merging template fields seems to be ugly.

**Comment by reiterl** [comment]
Talked to @rrenkert  about it. We want to add this feature after the removal of the template fields.
If two different users are in the same meeting, the  case will be complicated. I would say, we allow only to merge users, which are not in the same meetings. Okay?

**Comment by jsangmeister** [comment]
As I understood it, the plan is for the user to select one "main user", into which all other users will be merged. So, if another user is present in the same meeting, the fields for that user will just be dropped.
