### ISSUE TITLE
Analog Poll: From state 'created' to 'finished'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#497]
I have created a poll, published it and then reset its state. Then, the poll is in state 'created', but the state does not change, event though I update the options.

Steps to reproduce:
1. Create a poll and enter values for different options in the poll-dialog.
2. Publish the poll.
3. Reset the poll's state.
4. Re-enter some values for the different options.

Expected behaviour:
The poll's state is changed from 'created' to 'finished' again.

Current behaviour:
The poll's state remains in 'created'.

Did I fail to notice anything?

**Comment by FinnStutzenstein** [comment]
I think this is done, if #498 is done, since the state changes discussed there will help here, right?

**Comment by GabrielInTheWorld** [comment]
> I think this is done, if #498 is done, since the state changes discussed there will help here, right?

I think so too, that #498 goes hand in hand with this problem.
