### ISSUE TITLE
Analog Polls: Initial state 'created'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#498]
I know, in the [wiki](https://github.com/OpenSlides/OpenSlides/wiki/Voting#analog-polls) is defined, that an analog poll started in the state 'finished' - whether or not votes were casted. But, I think it makes more sense, that a poll started in state 'created', if there are no votes were casted. (Besides, this is the same behaviour as in OS3)

**Comment by FinnStutzenstein** [comment]
So you do a `poll.create`, and if there are no votes, the state should be created, right? This means, that the three `votes_*` fields, the three `amount_global_*` fields and each `Y`, `N`, `A` field for each option has no value.

So when doing poll.update or option.update the state may be set to `finished` (or `published`, if the right flag is provided)? So both actions and poll.create needs an optional `publish_immediately`.

If this is all right, I'll adjust the docs and inform the backend devs what to do.

**Comment by GabrielInTheWorld** [comment]
> So you do a `poll.create`, and if there are no votes, the state should be created, right? This means, that the three `votes_*` fields, the three `amount_global_*` fields and each `Y`, `N`, `A` field for each option has no value.
> 
> So when doing poll.update or option.update the state may be set to `finished` (or `published`, if the right flag is provided)? So both actions and poll.create needs an optional `publish_immediately`.
> 
> If this is all right, I'll adjust the docs and inform the backend devs what to do.

Yes, that all is right.
This is the same behaviour as in OS3. Another thing: If an analog poll started in state 'finished' - whether or not votes were casted - a user can publish the poll without any votes.

**Comment by FinnStutzenstein** [comment]
Ok, A summary what is to do in the action service (Everything is only for analog polls!):

- `poll.create`:
  * set the state to finished only, if at least one vote is given. the three `votes*` fields, the three `amount_global_*` fields and each `Y`, `N`, `A` for each given option has to be checked, if something is given (different from None).
  * Only if votes are given and the `publish_immediately` flag, the state should be set to published.
- `poll.update`: Add `publish_immediately`. See new description here: https://github.com/OpenSlides/openslides-backend-coordination/issues/117
- `option.update`: Add `publish_immediately`. See new description here: https://github.com/OpenSlides/openslides-backend-coordination/issues/168

**Comment by r-peschke** [comment]
@FinnStutzenstein : I can't find any amount_global_* field in the whole models.py?

**Comment by FinnStutzenstein** [comment]
These values are global votes (https://github.com/OpenSlides/OpenSlides/wiki/Voting#global-votes). There exists a auto-generated *global option* for each poll, so the values must be saved as vote objects for the global option:

> [...] global vote amounts are saved within the global option

form https://github.com/OpenSlides/OpenSlides/wiki/Voting#analog-polls
