### ISSUE TITLE
poll.create: Options must be unique

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#504]
I updated https://github.com/OpenSlides/openslides-backend-coordination/issues/117 and https://github.com/OpenSlides/OpenSlides/wiki/Voting#creating-a-poll-pollcreate

> The options must be unique in the way that each non-empty `text` is unique and each non-empty `content_object_id` is unique.

This resolves most tests in #502

Note: #500 must be done, too.

**Comment by r-peschke** [comment]
> I updated https://github.com/OpenSlides/openslides-backend-coordination/issues/117 and https://github.com/OpenSlides/OpenSlides/wiki/Voting#creating-a-poll-pollcreate
> 
> > The options must be unique in the way that each non-empty `text` is unique and each non-empty `content_object_id` is unique.

I understood that the combination of object/text and vote (Y or N for instance) must be unique, not only the `text` or `content_object_id`.To clarify see examples further down
> 
> This resolves most tests in #502
> 
> Note: #500 must be done, too.

       
- **allowed, because combinations _test/Y_, _test/N_ and _test/A_ are all unique 
or is it not allowed, because _test_ is not unique**

                "options": [
                    {"text": "test", "Y": "10.000000"},
                    {"text": "test", "N": "11.000000"},
                    {"text": "test", "A": "12.000000"},
                ],
- **not allowed, because combination _test/Y_ is not unique**

                "options": [
                    {"text": "test", "Y": "10.000000"},
                    {"text": "test", "Y": "11.000000"},      
                    {"text": "test", "N": "12.000000"},
                ],

**Comment by FinnStutzenstein** [comment]
No, just `text` and `content_object_id` is relevant here, so both your cases are not allowed. To do the first case a user must send:
```
{"text": "test", "Y": "10.000000", "N": "11.000000", "A": "12.000000"},
```

**Comment by FinnStutzenstein** [comment]
I think in #502 it is currently correct (-> `o_obj = f"{c_letter},{content}"`).
