### ISSUE TITLE
Implement projector_countdown.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#509]
https://github.com/OpenSlides/OpenSlides/wiki/projector_countdown.create

Needs #505

**Comment by reiterl** [comment]
Someone added a default to `default_time`. This doesn't make sense, as we want to use the meeting.projector_countdown_default_time as default, as described in the wiki.

**Comment by FinnStutzenstein** [comment]
I did this. It should not hurt since you will always overwrite it, right?
