### ISSUE TITLE
motion_change_recommendation.create: Check for colliding change recommendations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#513]
See https://github.com/OpenSlides/OpenSlides/wiki/motion_change_recommendation.create

The check for `line_from` <= `line_to` is also missing.

**Comment by jsangmeister** [comment]
Is the `<=`/`>=` correct in the description? Because if `a.line_to = b.line_from` this means that a and b overlap on exactly one line where they could have differing recommendations, or not?

**Comment by FinnStutzenstein** [comment]
I think one of them is exclusive. I hope, that I translated it correctly from OS3: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/models.py#L696

**Comment by jsangmeister** [comment]
> I think one of them is exclusive

Ah ok, I will take that as granted then :D
