### ISSUE TITLE
Cache layer for datastore adapter

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#518]
#486 already made the start and moved the `fetch_model` method into the datastore adapter since it was needed outside of the actions. Currently, we have now at least 3 places where different `additional_relation_models` are created and managed which can become quite confusing. I suggest we fully move this away from the actions and integrate a cache layer in the datastore adapter which can not only hold the new changes to models which are not written to the datastore yet, but also all models that were fetched during the current action. This would reduce redundant datastore calls and should have no logical impact, since we have to lock them anyway on the lowest position (which will most likely be the one from the first fetch).

Of course we would have to adjust the adapter methods to also accomendate the cached models, but I guess this should be relatively easy to do. The `get` methods are simple anyway, the more complicated things will be the `filter` methods.

This will solve many problems we've had with not up-to-date models being fetched from the datastore and also remove the manual handling of all the `additional_relation_models`. What do you think?

**Comment by FinnStutzenstein** [comment]
This sounds like my initial idea of having a layer reflecting already-done changes by previous actions. So it is ok for me.
