### ISSUE TITLE
Return value execute_other_action

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#520]
The [PullRequest for meeting.create](https://github.com/OpenSlides/openslides-backend/pull/486) declares the write_request and the action_results as return values for method action.execute_other_action.
action_results are just a list of dictionary with key "id" and the number, but no checking of data is possible. To validate data the write_request can be used (Collection, data like group name etc. can be checked/searched for etc.).
Without write_requests you have to trust the sequence and get the id for the admin"-group for instance as action_results[3]["id"], knowing that the admin group is the 4. group to be added.

**Comment by jsangmeister** [comment]
> Without write_requests you have to trust the sequence and get the id for the admin"-group for instance as action_results[3]["id"], knowing that the admin group is the 4. group to be added.

Yes, I would much prefer that. It is guaranteed that the order is the same since the action data is processed one-by-one. The mentioned validation of the data is not necessary since you given e.g. 3 groups as action data and get exactly the matching 3 action results as a return value.

**Comment by FinnStutzenstein** [comment]
Quick note: See #522 it seems, that the return values are not ok in some times.

**Comment by jsangmeister** [comment]
> Quick note: In #522 it seems, that the return values are not ok in some times.

Solved.

**Comment by r-peschke** [comment]
> > Without write_requests you have to trust the sequence and get the id for the admin"-group for instance as action_results[3]["id"], knowing that the admin group is the 4. group to be added.
> 
> Yes, I would much prefer that. It is guaranteed that the order is the same since the action data is processed one-by-one. The mentioned validation of the data is not necessary since you given e.g. 3 groups as action data and get exactly the matching 3 action results as a return value.

Will rebuild the return value to only return the ActionResult
