### ISSUE TITLE
Test needed: speaker.create foreign user

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#521]
> The user must belong to the meeting

(https://github.com/OpenSlides/OpenSlides/wiki/speaker.create)

Please write a test for `speaker.create` adding a new user, which is not associated ([see here](https://github.com/OpenSlides/OpenSlides/wiki/Organisation-level#user-association-to-meetings)) to the meeting of the list of speakers which to create the speaker for. It must be denied.

**Comment by jsangmeister** [comment]
Will (hopefully) be also implemented with #365

**Comment by FinnStutzenstein** [comment]
(moved back to the backlog, so it can be checked later)
