### ISSUE TITLE
Why is there a global_option in a poll?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#529]
The need for a global_option is not yet clear to me.
For motion_polls I have options for an analog type and a global_option for electronic types, right?
For assignment_polls I have options for all of them... Right?

**Comment by FinnStutzenstein** [comment]
for every poll (regardless of assignment/motion/... and regardless of analog/electronic) there are your regular options in `poll/option_ids`. These are the options you pass to the server when doing `poll.create`.

The server will automatically create `poll/global_option_id`. This option is not part of `poll_option_ids`. It will be created even if you have all three `global_*` set to false.

The global option is used to save global votes. Global votes are possible to give in analog and electronic case (as long it is enabled). I just looked into the OS3 client: We disallow global votes for analog types - but we can add them easily in the future!

So for electronic voting: If someone votes for global yes, you must send the vote request for the global option. Also the global results are available via the global option.
