### ISSUE TITLE
How can I remove my "point of order"?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#533]
In OS3, I can create a "point of order" and also remove it.
In OS4, I can create a "point of order", too - but how can I remove it?

**Comment by GabrielInTheWorld** [comment]
Okay, will be closed in favor of [openslides-client#127](https://github.com/OpenSlides/openslides-client/pull/127)

**Comment by FinnStutzenstein** [comment]
Looking at the PR: You did a speaker.delete, right?
