### ISSUE TITLE
Add `disabled` as default for majority_method and onehundred_percent_base for polls

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#542]
We either need default values here or need to make them required in the schema.

**Comment by FinnStutzenstein** [comment]
OS3 forces the user to give values, but I'm not a fan of this. I vote for not-required and `disabled` as defaults for both.

**Comment by jsangmeister** [comment]
Sounds good to me. Although in the client interface, there will probably always a default set, or not?

**Comment by FinnStutzenstein** [comment]
Yes, the client (currently) always provides values.
