### ISSUE TITLE
Users are created without a password

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#546]
When calling `user.create[_temporary]`, no password is created. I don't think this is intended. Before `user_set_password[_temporary]` is called, the user cannot log in.

**Comment by FinnStutzenstein** [comment]
Yes, the provided `default_password` must be hashed via the auth service. If there is no `default_password` a random password must be created.

**Comment by jsangmeister** [comment]
Ok. The generation algorithm should be the same as for `generate_new_password` or the action can just be called.
