### ISSUE TITLE
Electronic votes for motion-polls are saved as 'global_options'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#548]
In the client, I received electronic votes for a motion-poll in its `global_option`. This cannot be right, because nobody can give a global vote for a motion-poll.

**Comment by FinnStutzenstein** [comment]
> This cannot be right, because nobody can give a global vote for a motion-poll

It is possible, if `global_*` is true (which is currently the default). I think you are sending votes wrong. You should send `{<option_id>: 'Y'}` instead of `Y`.
