### ISSUE TITLE
Permissions (easy): list_of_speakers

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#570]
- https://github.com/OpenSlides/OpenSlides/wiki/list_of_speakers.delete_all_speakers
- https://github.com/OpenSlides/OpenSlides/wiki/list_of_speakers.re_add_last
- https://github.com/OpenSlides/OpenSlides/wiki/list_of_speakers.update

**Comment by reiterl** [comment]
The action `delete_all_speakers` and `re_add_last` are problematic. The model of this actions is `Speaker()`, the permission
code getting the meeting_id cannot handle this.

**Comment by reiterl** [comment]
Ahh, you can overwrite `get_meeting_id()` to fix these problems.
