### ISSUE TITLE
Permissions (moderate): motions

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#573]
easy:
- https://github.com/OpenSlides/OpenSlides/wiki/motion.sort
- https://github.com/OpenSlides/OpenSlides/wiki/motion.follow_recommendation
- https://github.com/OpenSlides/OpenSlides/wiki/motion.set_recommendation
- https://github.com/OpenSlides/OpenSlides/wiki/motion.reset_recommendation
- https://github.com/OpenSlides/OpenSlides/wiki/motion.set_support_self
- https://github.com/OpenSlides/OpenSlides/wiki/motion.reset_state

moderate:
- https://github.com/OpenSlides/OpenSlides/wiki/motion.set_state
- https://github.com/OpenSlides/OpenSlides/wiki/motion.delete
- https://github.com/OpenSlides/OpenSlides/wiki/motion.create
- https://github.com/OpenSlides/OpenSlides/wiki/motion.update

**Comment by reiterl** [comment]
motion create and motion.update are not moderate.
what does "The values of category_id and motion_block_id are set to the values from the lead motion." in motion.create permissions mean? Shouldn't the whitelist include "id" and "meeting_id"?

**Comment by jsangmeister** [comment]
> what does "The values of category_id and motion_block_id are set to the values from the lead motion." in motion.create permissions mean?

I would interpret it as written: if `lead_motion_id` is given, the values for `category_id` and `motion_block_id` are not taken from the payload, but instead copied from the given lead motion.

> Shouldn't the whitelist include "id" and "meeting_id"?

Yes, of course, for `motion.create`, `meeting_id` is still needed as well as `id` for `motion.update`. The whitelist just refers to _additional_ payload fields.

**Comment by reiterl** [comment]
Okay, then I don't have to do extra permission check logic for the category_id and the motion_block_id. Good.
