### ISSUE TITLE
Permissions (moderate): personal_note

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#583]
- https://github.com/OpenSlides/OpenSlides/wiki/personal_note.create
- https://github.com/OpenSlides/OpenSlides/wiki/personal_note.delete
- https://github.com/OpenSlides/OpenSlides/wiki/personal_note.update

**Comment by jsangmeister** [comment]
The check that the personal note belongs to the request user (for update and delete) should belong to the permission check as well, shouldn't it? If so, it must be changed in the wiki and the PR.

**Comment by FinnStutzenstein** [comment]
For me it is a bit diffused: Is it logic or a permission, that a personal note is bound to one user, the request user? Since the code in the PR is relatively small, I do not have a preference there.

**Comment by jsangmeister** [comment]
I would say permission: If you give an id of another user's note, the request will fail since you do not have the permission to edit that note. Also, we already have some other cases where the object must "belong" to the request user (e.g. he must be submitter) which is the same kind of check.

**Comment by jsangmeister** [comment]
@reiterl Then please move the check that the note belongs to the request user to the permission method and raise a permission exception except of an action exception. I will change the wiki.

**Comment by jsangmeister** [comment]
And actually, the additional checks for the update/delete case are not necessary: if the user id matches, the other conditions are automatically fulfilled.
