### ISSUE TITLE
Permissions (moderate/difficult): user

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#587]
moderate:
- https://github.com/OpenSlides/OpenSlides/wiki/user.create
- https://github.com/OpenSlides/OpenSlides/wiki/user.delete
- https://github.com/OpenSlides/OpenSlides/wiki/user.generate_new_password
- https://github.com/OpenSlides/OpenSlides/wiki/user.reset_password_to_default
- https://github.com/OpenSlides/OpenSlides/wiki/user.set_password
- https://github.com/OpenSlides/OpenSlides/wiki/user.merge_to_non_temporary

difficult:
- https://github.com/OpenSlides/OpenSlides/wiki/user.update

**Comment by r-peschke** [comment]
The action `user.set_password` should check for temporary user and raise an error. But it is used as base class to set the password for  `user.generate_new_password`, `user.set_password_temporary`, `user.generate_new_password_temporary` and itself. 
Except the check for temporary user yes/no, demanded on both sides, there is no difference between them. Let's talk about it.
