### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#60]
Hi, when starting the dev-container, `python -m openslides_backend` has a constant 100% cpu load. Can you verify this?

**Comment by normanjaeckel** [comment]
I can confirm. The bug is somewhere here: https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/main.py#L82

**Comment by normanjaeckel** [comment]
Should be fixed with #58 .

**Comment by FinnStutzenstein** [comment]
Confirmed.
