### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#61]
Just inrease value in .travis.yml and then try to get it run successfully.

**Comment by jsangmeister** [comment]
Some increases in #189. Most of the missing percentages come from the `relations.py`, if we want to increase it further you'd have to write extensive unit tests for this.

**Comment by jsangmeister** [comment]
We're currently at 98% (value in `setup.cfg` is not up to date). Closing this
