### ISSUE TITLE
Implement projector.toggle_stable

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#611]
https://github.com/OpenSlides/OpenSlides/wiki/Projection#toggle-stable-projections-projectortoggle_stable

**Comment by reiterl** [comment]
What does happen if the projectors have different meeting_ids? That could be a problem for permissions
What is with the empty ids case? I have disallowed this case.
What about "meeting" or "user" is in the content_object_id? This won't work, because of the equal field in projection.

**Comment by FinnStutzenstein** [comment]
I've added a `meeting_id` to the payload (see wiki). This was previously done for projector.project to simplify checks. Now all content objects and projectors must belong to that meeting. You might find code to check this in projector.project.

> What is with the empty ids case? I have disallowed this case.

Ok
