### ISSUE TITLE
Create `user_token` for each vote

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#628]
(see last paragraph of https://github.com/OpenSlides/OpenSlides/wiki/Voting#user-in-vote-objects)

Changes to `models.yml` done in https://github.com/OpenSlides/OpenSlides/pull/5993/.

The token should be a 16-digit, alphanumerical string. If the user gives a vote for multiple options simultaniously, the token has to be the same (so only one token should be created per call to `poll.vote`).

**Comment by reiterl** [comment]
The field `projector_countdown_warning_time` is required and has a default of zero. That leads to problems with tests.
Isn't zero an allowed value for required fields? Why not?

**Comment by reiterl** [comment]
To continue here, I will set a value of 1.

**Comment by jsangmeister** [comment]
Ah, yes. @r-peschke remember that I was against `0` as an invalid value for an required field? :D do we want to change the required handling for integer fields or do you have another proposed solution?

**Comment by reiterl** [comment]
Perhaps use another default, so it doesn't trigger an error.

**Comment by FinnStutzenstein** [comment]
No, 0 is wanted as a default and a valid value (the `projector_countdown_warning_time` can also be negative).

**Comment by r-peschke** [comment]
We have projector_countdown_warning_time defined as an IntegerField. Our schema definition of IntegerField has no value limitation, see models/fields.py. The field itself has a minimum constraint of 0. That way it should pass the validation. Where does it crash on schema validation?

**Comment by r-peschke** [comment]
> Ah, yes. @r-peschke remember that I was against `0` as an invalid value for an required field? :D do we want to change the required handling for integer fields or do you have another proposed solution?

For an integer a 0 or a negative should and is valid in schema validation. For a relation id it shouldn't, I think.
