### ISSUE TITLE
Check permission code,  whether hierarchy in OrganisationManagentLevel is incorporated

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#642]
Just check existing backend code, whether the higher levels SUPERADMIN and CAN_MANAGE_ORGANISATION are recognized as sufficient for the required OrganisationManagementLevel CAN_MANAGE_USERS. You can do that with the permission_helper function has_organisation_management_level.

**Comment by jsangmeister** [comment]
Just did a quick check and it seems the only place where it's currently used (incorrectly) is the ressource permission helper. Do you mind just replacing it there with the new ``has_organisation_management_level` in your PR #640? Then you can close this issue.

**Comment by jsangmeister** [comment]
(maybe also add a test that e.g. `superadmin` also suffices)
