### ISSUE TITLE
New action: motion.create_forwarded

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#646]
See https://github.com/OpenSlides/OpenSlides/wiki/motion.create_forwarded

If there are any questions don't hesitate to ask! Maybe it is good for the one implementing it to speak about the new action.

**Comment by reiterl** [comment]
I will try this one.

**Comment by reiterl** [comment]
The motion create action is a complex action. The committees are checked in the create action.
