### ISSUE TITLE
Automatically create username

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#656]
One of the fields [`first_name`, `last_name`, `username`] must be required.
If a `username` is not provided, a username must be generated from first_name and/or last_name by the backend.

**Comment by FinnStutzenstein** [comment]
Fair point, but the server can only try to append a number or so - this can also be done by the user - just prompt him to enter a not-used username.

**Comment by jsangmeister** [comment]
> just prompt him to enter a not-used username.

That's exactly what @tsiegleauq does not want: If a user does not give a username, it should be automatically generated. The client doesn't have the possibilities to do that, the server can just try admin 1, 2, 3... until one doesn't exist yet.

**Comment by tsiegleauq** [comment]
Appending a number would be enough I suppose. Depending an who, how, and where you add a new user, you might not have the chance to know which usernames are free. Successfully guessing user names by searching for collisions is a security flaw. `JohnSmith1` to `JohnSmith9` might all have been taken. The Server Should then generate `JohnSmith10` for us.

**Comment by jsangmeister** [comment]
See https://github.com/OpenSlides/OpenSlides/blob/bdbb5839cc127393f2ff32687b5470d1630bc53e/server/openslides/users/models.py#L90 for OS3 username generation.

**Comment by FinnStutzenstein** [comment]
Ok. SO what is to do:
- edit user.create (also temporary) wiki to have the username not required
- add the username generation in the backend
- add tests for it, especially with the counter

**Comment by jsangmeister** [comment]
Note: counter should only be added if the username is generated. For explicitly given usernames from the client, an error should be thrown (analogous to OS3).

**Comment by FinnStutzenstein** [comment]
Documentation is done here: https://github.com/OpenSlides/OpenSlides/wiki/user.create#generate-a-username
