### ISSUE TITLE
Deleting a committee throws an error

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#657]
I sent the following payload:
```json
[
  {
    "action":"committee.delete",
    "data":[
      {
        "id":5
      }
    ]
  }
]
```

and got the following error:
```
Fehler: You can not delete committee/5 because you have to delete the following related models first: [FullQualifiedId('meeting/23')]
```

**Comment by jsangmeister** [comment]
Yes, I think this is intentional. We did not want a cascade deletion here because this could lead to huge data loss if the user does not pay enough attention.

**Comment by FinnStutzenstein** [comment]
This is right, you have to delete all meetings in the committee (by hand).

The generated message could be user friendlier - in OS3 we had some nice messages in these cases (e.g. deleting a workflow where motions are assigned to states), which also were translated in the client.

**Comment by jsangmeister** [comment]
Ok, creating a new issue for that.
