### ISSUE TITLE
Improve message in PermissionDenied

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#671]
the first sentence is repeated and it is the same for each action. Can the code executing the action except the PermissionDenied, attach the action name to the exception and reraise it? In the PermissionDenied.__str__ a nice error message can be built upon the information.

```
try:
    #execute action
except PermissionDenied as e:
    e.action_name = action_name
    raise e
```

_Originally posted by @FinnStutzenstein in https://github.com/OpenSlides/openslides-backend/pull/643#r615581092_

**Comment by jsangmeister** [comment]
This would probably need to be a wrapper around the `perform` method to get the right action name even for nested actions. Should be easy to do then.
