### ISSUE TITLE
Sending emails and user.send_invitation_email

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#676]
Some quick common nodes:
- See https://github.com/OpenSlides/OpenSlides/wiki/Action-Service#sending-emails
- Maybe you can reuse some code. Especially the error handling is important
- Make sure that one connection to the email host is shared within multiple actions.

This is the action: https://github.com/OpenSlides/OpenSlides/wiki/user.send_invitation_email
We can use the containerized OS3-smtp-server

**Comment by reiterl** [comment]
If we want to use the smtp-lib of python for this, we will need a smtp-server and a way to test the outgoing mails.

**Comment by FinnStutzenstein** [comment]
Right, for testing while developing, you may use your corporate smtp server. The settings (TLS, password, user, host, port, ...) must be provided via environment variables, so you can set them for yourself personally.

**Comment by r-peschke** [comment]
The python-included [smtpd-server](https://docs.python.org/3/library/smtpd.html) recommends using [aiosmtpd](http://aiosmtpd.readthedocs.io/) as smtp-server and I think we should do. Documentation you'll find [here](https://aiosmtpd.readthedocs.io/en/latest/).
