### ISSUE TITLE
User restructure: Permissions of user-altering actions

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#683]
All user altering actions have a changed permission check:
- https://github.com/OpenSlides/OpenSlides/wiki/user.delete
- https://github.com/OpenSlides/OpenSlides/wiki/user.generate_new_password
- https://github.com/OpenSlides/OpenSlides/wiki/user.reset_password_to_default
- https://github.com/OpenSlides/OpenSlides/wiki/user.set_password

Instead of the OML `can_manage_users` the check in https://github.com/OpenSlides/OpenSlides/wiki/Users#permissions-for-altering-a-user is needed. Note: This check is also needed for [user.update](https://github.com/OpenSlides/OpenSlides/wiki/user.update) (#681).

**Comment by jsangmeister** [comment]
Since `send_invitation_email` does not exist yet, that can be done when the action is first implemented. Updated description.
