### ISSUE TITLE
User restructure: user/meeting_ids

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#684]
Add the calculated field `user/meeting_ids` (See models.yml or https://github.com/OpenSlides/OpenSlides/pull/6029)

**Comment by reiterl** [comment]
What is about the reverse field `meeting/user_ids`?

**Comment by reiterl** [comment]
A user belongs to a meeting, if the user is in one or more groups of the meeting.

**Comment by reiterl** [comment]
So if a user is created or updated with group change, the meeting_ids must be set.

**Comment by jsangmeister** [comment]
`user/meeting_ids` can just be a copy of `user/group_$_ids` but with ints instead of strings. You should be able to use a `CalculatedFieldHandler` for this, analogous to `meeting/user_ids`.
