### ISSUE TITLE
User restructure: Alter user-committee relation and `committee_$_management_level`

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#685]
See models.yml (or https://github.com/OpenSlides/OpenSlides/pull/6029) for new fields.

**Comment by jsangmeister** [comment]
Add tests for CML to ensure the template field works correctly with committees. E.g. add a structured field with a replacement committee id which doesn't exist and make sure it is rejected.

**Comment by jsangmeister** [comment]
@r-peschke please add this in #723
