### ISSUE TITLE
Add test for meeting.delete

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#693]
Add a test with a full meeting with groups, motions, workflows, etc. Assert that all models are deleted afterwards. Explicitely test that structured fields for this meeting are deleted as well. We probably need a method that iterates over all structured fields of all users and deletes them.

**Comment by FinnStutzenstein** [comment]
Note: meeting-scoped users may also be deleted (Or shouldn't they?).

@emanuelschuetze Whats your opinion here?

**Comment by jsangmeister** [comment]
Will implement without deleting these users for now. Can still be added later
