### ISSUE TITLE
Error thrown, if a paragraph based amendment is created

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#696]
I sent the following payload:
```json
[
  {
    "action":"motion.create",
    "data":[
      {
        "meeting_id":1,
        "lead_motion_id":11,
        "title":"Änderungsantrag zu B001",
        "workflow_id":1,
        "category_id":2,
        "reason":"<p>Nur dann, wenn jemand Burger isst.</p>",
        "amendment_paragraph_$1":"<p>Jeder hier kennt einen Hund;</p>",
        "amendment_paragraph_$2":"<p>Jeder hier kennt Herr der Ringe, der auch Burger isst.</p>"
      }
    ]
  }
]
```

But this throws an error: 
`Fehler: data must not contain {'amendment_paragraph_$2', 'amendment_paragraph_$1'} properties`

Why?

The specification describes it as follows:
```
amendment_paragraph_$<paragraph_number>: HTML;
```

Is there another restriction, I overseen?

**Comment by jsangmeister** [comment]
The specification is outdated, it should say:
```
amendment_paragraph_$: {
  <paragraph number>: HTML;
}
```
Can you try that and report if it works? Then I'll edit it in the wiki.

This is the common structure for template fields btw, all of them should work this way.

**Comment by FinnStutzenstein** [comment]
> The specification is outdated

I did not use the new format everywhere - please search for all template fields and adjust it everywhere.

**Comment by GabrielInTheWorld** [comment]
> The specification is outdated, it should say:
> 
> ```
> amendment_paragraph_$: {
>   <paragraph number>: HTML;
> }
> ```
> 
> Can you try that and report if it works? Then I'll edit it in the wiki.
> 
> This is the common structure for template fields btw, all of them should work this way.

Thanks! Yes, this works.
