### ISSUE TITLE
Resolve read_only TODO

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#697]
https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/models/fields.py#L46

**Comment by jsangmeister** [comment]
This can just be removed - I overlooked it in #383

**Comment by reiterl** [comment]
What can be removed here? The `read_only` attribute is used in the code, so it cannot be removed.

**Comment by jsangmeister** [comment]
The comment in the linked line can be removed
