### ISSUE TITLE
Add test for organisation tags

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#700]
Missing from #675

assert, that it is linked to the organisation. check if `organisation/1/organisation_tag_ids` is `[]`.

_Originally posted by @FinnStutzenstein in https://github.com/OpenSlides/openslides-backend/pull/675#discussion_r624882615_

**Comment by jsangmeister** [comment]
Don't you mean `organisation/1/organisation_tag_ids == [1]`?

**Comment by FinnStutzenstein** [comment]
Right, it must be `[1]`.

**Comment by reiterl** [comment]
Update the tests.
