### ISSUE TITLE
Add users on meeting.create

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#710]
Requirement: A committee manager can give users on meeting.create which should be added to the meeting.

Problem: This cannot be done in one request, since to update the users the default group id and meeting id must be known beforehand.

Suggestion: Add `user_ids` to the meeting.create payload. It must be a subset of `committee/user_ids`, so there is no initial support for guests. After the meeting create has done it's current job, the freshly created default group is added to each given user.

Opinions?

**Comment by jsangmeister** [comment]
Sounds good

**Comment by r-peschke** [comment]
LGTM
Don't you want initial support for guest users? Without the subset condition it would be realized I think.

**Comment by FinnStutzenstein** [comment]
> Don't you want initial support for guest users? Without the subset condition it would be realized I think.

I excluded it for the ease of permission checks: When restricting, a committee-manager is allowed to do it. When allowing arbitrary users, you have to check for the OML `can_manage_users` when there is at least one user which is not in the committee.

I do not have any preference here since it currently is not needed from the UI

I added this to the wiki:

> If `user_ids`  are given, it must be checked, that it is a subset of `committee/user_ids` and the request user is excluded. Each user is added to the meeting by being added to the default group. In every case, the request user is added to the admin group.

Also watch out for the "request user"-part. Currently when creating a meeting, no one can do something in it. This is a way of letting the creator of the meeting be the initial admin in it.

If we allow guest users, I will change it.

**Comment by FinnStutzenstein** [comment]
It is ready to be implemented!
