### ISSUE TITLE
Missing responses for multi-delete

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#750]
The client deletes three mediafiles: `[{action: "mediafile.delete", data: [{id: 2}, {id: 4}, {id: 1}]}]`

This is the response: `{"success": true, "message": "Actions handled successfully", "results": [[null]]}`. I would expect it to return either `[null]` or `[[null,null,null]]`, but `[[null]]` is invalid.

**Comment by reiterl** [comment]
This is not the first time with problems in this area. 
See https://github.com/OpenSlides/openslides-backend/pull/540 .
The `mediafile.delete` action overwrite  `get_updated_instances` and then special code is fired, which set
the results to `[[None]]`. See openslides_backend/action/action.py L. 135 (is_original_instances).
I don't know how to continue here, Joshua can you look at this?
