### ISSUE TITLE
`user.update` and `meeting.update` leads to model locked error

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#751]
Meeting update:
User hinzufügen führt zu Fehler -> "Database service sends HTTP 400. Model meeting/3 raises MODEL_LOCKED error"
It seems, that this error appears every time multiple actions are sent to the backend (for example `motion.update` & `motion.set_state`).

Sent payload:
```json
[
  {
    "action":"meeting.update",
    "data":[
      {
        "name":"Neues Meeting",
        "welcome_title":"Hallo",
        "welcome_text":"",
        "description":"",
        "location":"",
        "start_time":1623016800,
        "end_time":1623016800,
        "enable_anonymous":true,
        "organization_tag_ids":[
          
        ],
        "id":3
      }
    ]
  },
  {
    "action":"user.update",
    "data":[
      {
        "id":4,
        "group_$_ids":{
          "3":[
            11
          ]
        }
      }
    ]
  }
]
```

**Comment by jsangmeister** [comment]
Please create an issue for all cases where you encounter this: This is not a structural problem it seems, but we rather have to go through each affected action and check which fields really need to get locked and which not.

**Comment by jsangmeister** [comment]
It seems like #776 already fixed this. I added a test in #786 and it works. Please check and report back; if it does not work for you, please provide more information on the request user (groups, CML, OML, etc.).
