### ISSUE TITLE
Remove unrelated fields for meeting.create

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#754]
Please remove the following fields for meeting.create:

- welcome_title
- welcome_text
- enable_anonymous

See also [openslides-client#253](https://github.com/OpenSlides/openslides-client/pull/253) and the wiki.

**Comment by jsangmeister** [comment]
Since these were all optional, I don't think this is a high prio issue, right? Also, you can move these king of bug reports directly to "TODO" or else they might not be done.

Also, how can these fields be updated instead?

**Comment by GabrielInTheWorld** [comment]
`welcome_title` is until now a required field. Removing this from the client view will cause that no meetings can be created.

**Comment by GabrielInTheWorld** [comment]
> Also, how can these fields be updated instead?

These are meeting-specific fields. They will be updated in the meeting settings for example or just in the update-view.

**Comment by GabrielInTheWorld** [comment]
> > They will be updated in the meeting settings.
> 
> But the settings are updated in `meeting.update`, or am I missing something?

Yes, this remains as it is.

**Comment by jsangmeister** [comment]
Ah okay, this makes sense then
