### ISSUE TITLE
Speaker.create does not work

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#755]
I sent this payload:
```json
[
  {
    "action":"speaker.create",
    "data":[
      {
        "list_of_speakers_id":3,
        "user_id":2,
        "marked":false,
        "point_of_order":false
      }
    ]
  }
]
```

and get the following error:
```
data must not contain {'marked'} properties
```

This is wrong, because the property `marked` is an optional property for the [speaker.create-action](https://github.com/OpenSlides/OpenSlides/wiki/speaker.create).

**Comment by FinnStutzenstein** [comment]
Yes, I missed updating `speaker.create`. `speaker.update` was updated correctly.

I've added `speech_state` to it and two new requirements:

- `speech_state` can only be set to `pro` or `contra` if `meeting/list_of_speakers_enable_pro_contra_speech` is true
- `speech_state` can only be set to `contribution` if `list_of_speakers.can_manage` or `meeting/list_of_speakers_can_set_contribution_self` is true

@jsangmeister Can you quickly check, if it is implemented in the backend? If not it has to be done and I'll create a fresh issue.

**Comment by jsangmeister** [comment]
> @jsangmeister Can you quickly check, if it is implemented in the backend? If not it has to be done and I'll create a fresh issue.

It is not, I created an issue for it

**Comment by jsangmeister** [comment]
This can be closed then, I think
