### ISSUE TITLE
meeting.create does not respects all ids in user_ids

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#758]
I sent the following payload:
```json
[
  {
    "action":"meeting.create",
    "data":[
      {
        "committee_id":1,
        "welcome_title":"Hello World",
        "name":"Kuchen backen ist angesagt",
        "start_time":1623189600,
        "end_time":1623189600,
        "user_ids":[
          5,
          6
        ],
        "organization_tag_ids":[
          
        ]
      }
    ]
  }
]
```

The meeting is correctly created, but has the following `user_ids`:
```json
{
  "id":5,
  "name":"Kuchen backen ist angesagt",
  "end_time":1623189600,
  "user_ids":[
    1,
    5
  ],
  "group_ids":[
    22,
    23,
    24,
    25,
    26
  ],
 ...
}
```

Did I miss anything? Do you need more information?

**Comment by reiterl** [comment]
Can you look if the user 5 and 6 are in the default group of the meeting?

**Comment by GabrielInTheWorld** [comment]
> Can you look if the user 5 and 6 are in the default group of the meeting?

Yes, they are both in the default group of `meeting/5`.

**Comment by FinnStutzenstein** [comment]
Sounds like some calculated fields is not updated correctly. Can someone write a test and verify this?
