### ISSUE TITLE
meeting.update is missing 'projector_countdown_default_time'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#759]
To update a meeting's settings I sent the following payload:
```json
[
  {
    "action":"meeting.update",
    "data":[
      {
        "name":"OpenSlides",
        "description":"Presentation and assembly system",
        "conference_show":false,
        "conference_auto_connect":false,
        "conference_los_restriction":false,
        "projector_countdown_warning_time":0,
        "projector_default_countdown_time":60,
        "enable_anonymous":false,
        "export_csv_separator":",",
        "export_csv_encoding":"utf-8",
        "export_pdf_pagenumber_alignment":"center",
        "export_pdf_fontsize":10,
        "export_pdf_pagesize":"A4",
        "id":5
      }
    ]
  }
]
```

But then, the backend sent me the following error as answer:
`data must not contain {'projector_default_countdown_time'} properties`

**Comment by reiterl** [comment]
The field is named **'projector_countdown_default_time'** not projector_default_countdown_time.

**Comment by GabrielInTheWorld** [comment]
> The field is named **'projector_countdown_default_time'** not projector_default_countdown_time.

You're right. I was wondering, because this field is also written as `projector_default_countdown_time`. But, I will change this, too.
