### ISSUE TITLE
Add speaker changes to `speaker.create`

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#760]
I've added `speech_state` to it and two new requirements:

- `speech_state` can only be set to `pro` or `contra` if `meeting/list_of_speakers_enable_pro_contra_speech` is true
- `speech_state` can only be set to `contribution` if `list_of_speakers.can_manage` or `meeting/list_of_speakers_can_set_contribution_self` is true

_Originally posted by @FinnStutzenstein in https://github.com/OpenSlides/openslides-backend/issues/755#issuecomment-858318397_

see also https://github.com/OpenSlides/OpenSlides/wiki/speaker.create

**Comment by reiterl** [comment]
The req are different from update to create. Look at the actions in the wiki. So I cannot use a mixin.
