### ISSUE TITLE
clear entitled_users_at_stop and votes* on poll.reset

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#761]

**Comment by jsangmeister** [comment]
Probably the `votes*` fields as well, right?

**Comment by FinnStutzenstein** [comment]
Yes, it must have a pristine set of fields, like when freshly created. This is important since users can expect to have previous results cleared when resetting.

**Comment by jsangmeister** [comment]
Ok, I looked through the model definition and those two kinds of fields are the only ones missing, I think
