### ISSUE TITLE
Prevent forbidden usernames

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#762]
~~When receiving a username, trim it first. Sending `" "` should result in generating a username since it is trimmed to `""` and `not username` is triggered.~~

This can be done in the `validate_fields` action method.

**Comment by FinnStutzenstein** [comment]
Raise errors on invalid usernames (e.g. empty usernames after they are trimmed)

> Do we have any more forbidden chars or something? Do we want to restrict it to ASCII or do we allow all Unicode characters?

Currently even emojis are allowed ;)

**Comment by jsangmeister** [comment]
> Raise errors on invalid usernames (e.g. empty usernames after they are trimmed)

We would need a list of what is forbidden :D currently, I know only of empty usernames after trimming of whitespaces and tabulators. If there's any more, please add.

On another note, this means `" username"` is allowed?

**Comment by FinnStutzenstein** [comment]
> On another note, this means " username" is allowed?

Yes, we should think about trimming it - but this is another issue that can be tackled later
