### ISSUE TITLE
Custom translations should be only in meeting

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#765]
Currently, the settings-field `custom_translations` is only orga-wide, but in OS3 this was meeting-specific (yeah, there was only one meeting). But we should accept custom translations per meeting or per committee (maybe a committee want a different for 'motions' than another committee).
Maybe we could pass custom translations in both places (orga and meeting/committee). (It seems to me, that we already had this discussion..?)

**Comment by FinnStutzenstein** [comment]
Yes, we have moved it to the highest level together with Emanuel some months ago.

**Comment by r-peschke** [comment]
Yesterday we decided to have the translation only on meeting level.
