### ISSUE TITLE
[META-issue] `MODEL_LOCKED` error on actions

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#769]
This issue should be a summarize of all action-combinations, for which the error `MODEL_LOCKED` occurs.

See also #747 
See also #751 

Actions:
["motion.update", "motion.set_state"]
["motion.update", "motion.set_recommendation"]

**Comment by jsangmeister** [comment]
> Actions:
> ["motion.update", "motion.set_state"]
> ["motion.update", "motion.set_recommendation"]

Please create an issue for each of these and provide a payload so I can recreate the bug.

**Comment by jsangmeister** [comment]
@GabrielInTheWorld ping

**Comment by jsangmeister** [comment]
I'll close this, if more errors occur, please open a seperate issue for each one
