### ISSUE TITLE
Allow users with no OML, committee or meeting relation

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#774]
Please assign users as discussed with no relations (a group in one meeting, member of a committee or at least the OML `can_manage_users`) to the default OML (`OML.default`).

**Comment by jsangmeister** [comment]
There is no `OML.default` from a datastore/backend POV, it is just left empty, so all that has to be done is remove the check that currently prevents it.

**Comment by jsangmeister** [comment]
I updated https://github.com/OpenSlides/OpenSlides/wiki/user.create accordingly (the paragraph was obsolet now and could just be removed)
