### ISSUE TITLE
Mediafile Upload: Cannot guess mimetype for ***.ttf

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#777]
I tried to to upload a font file, the upload failed with the error:

```
action_data_error_index: 0
action_error_index: 0
message: "Cannot guess mimetype for Roboto-Bold.ttf."
success: false
```

I observed the same error for:
*.ttf
*.otf
*.7z
*.odt

Apparently, the filter for uploading files is too strikt.

Some other formats are working fine, such as *.csv, *.pdf, *png, *.jpg

**Comment by jsangmeister** [comment]
Interesting. The error is thrown here, before the media service is called, so it is a backend problem for sure: https://github.com/OpenSlides/openslides-backend/blob/40169804ea470eca239820c59cb3e71257a20c46/openslides_backend/action/actions/mediafile/upload.py#L57

But I we do not provide a list of valid file endings, we just call `mimetypes.guess_type`. If I execute `mimetypes.guess_type("test.ttf")` locally, it returns `("font/ttf", None)`, which means it should theoretically return the correct type...

**Comment by GabrielInTheWorld** [comment]
I still get this error if I try to upload a mediafile. My payload:

```json
[
  {
    "action":"mediafile.upload",
    "data":[
      {
        "meeting_id":1,
        "file":"[Base64-string]",
        "filename":"CascadiaCode-Light.otf",
        "title":"CascadiaCode-Light.otf",
        "access_group_ids":[
          
        ],
        "parent_id":1
      }
    ]
  }
]
```

The error:
```json
{
  "success":false,
  "message":"Cannot guess mimetype for CascadiaCode-Light.otf.",
  "action_error_index":0,
  "action_data_error_index":0
}
```

The exact same error occurs, if I try to upload a *.ttf or *.woff2 file.

**Comment by tsiegleauq** [comment]
@GabrielInTheWorld your backend need to support the following PR
https://github.com/OpenSlides/openslides-backend/pull/781
after this your backend-docker needs to install a new debian package to support mimetypes
