### ISSUE TITLE
Fields in action `committee.update` as well as in action `committee.create`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#778]
Please add the fields 

- `receive_forwardings_from_committee_ids`
- `forward_to_committee_ids`

also to the action `committee.create`.

**Comment by FinnStutzenstein** [comment]
Please add these to the wiki, too!

**Comment by jsangmeister** [comment]
Maybe https://github.com/OpenSlides/openslides-backend/issues/772 can be done in conjunction with this
