### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#78]
From #76 :

> I think your approach to system/integration tests is way too heavy: In your fake_services/database.py, you are basically rewriting the whole datastore. This is not the intention of a system test. The better way would be to just patch the right method(s), in this case the get/filter/... methods of the adapter. You have to then specifiy in each test what they should return so you can test the actions/presenters with different outputs. I could not figure out how to access the DI from the tests, else I would have implemented an example. Please ask if you have any questions.

**Comment by normanjaeckel** [comment]
Ahh I am not convinced. Especially I do not like to path single db methods in non-unit test.

You can access DI in tests by using another create_test_application in tests/utils.py.

**Comment by jsangmeister** [comment]
Currently, I cannot test the mediafile presenter correctly because the `And` filter is not implemented in the fake datastore. It's wrong that in order to test the presenter, I have to implement datastore code in the backend. You are testing both the backend code as well as your fake datastore with the tests. If you have an error in your fake datastore, you may not notice since the tests all succeed, but the behaviour is different from the actual datastore. It is safer to just mock it and check that your code handles the return value from the datastore as it should.

I'm going to try to create an example test for the mediafile presenter.

**Comment by FinnStutzenstein** [comment]
Yes: Do we want to have two implementations of the DataStore? Maybe a third in JS, if the auth-service also needs one for testing? This is not the way this should be tested at all.

Unit and Integration tests should only test to boundaries, but not past them. So you have provide the return-value (or exception) for each call to external services. System tests should use external dependencies. This can wonderfully be done with a docker-compose setup: Just start everything and run your tests agains real services.

This should have a high priority *before* implementing every bit of the busineslogic. I do not want a test coverage as in OS3. @jsangmeister Has good experience with the different testing mechanics and you have a DI. It shouldn't be hard to implement tests.

You both: @normanjaeckel  and @jsangmeister please make a plan how to fix the tests before implementing a bunch of actions (Ludwig may just imlement them, so he hasn't to deal with it).

**Comment by jsangmeister** [comment]
In #85 I implemented a prototype of better integration tests. If we stick with that, all fake services could be removed (we have to handle auth in the same way).

**Comment by normanjaeckel** [comment]
I do not see how to test an complete action response without a fake http engine. We have multiple datastor request during this action performing so you can not easily patch the retrieve method or something like this. The better way would be to give a dummy datastore content and the expected write call as I did for the tests that are called "...WSGITester". For some actions I have some old style tests the should be refactored of course.

**Comment by jsangmeister** [comment]
As said before, it is wrong and not needed to reimplement the datastore in these tests. We have to fix this in some way, so just dummy datastore content will not do it.

What we do with the mocking are integration tests. Maybe the better alternative would be to just start the full setup with docker compose and use the real services (=> system tests). System and integration tests double a lot of code, anyway. We would only need to mock them to test the error handling. Would that be fine with you @normanjaeckel?

**Comment by jsangmeister** [comment]
resolved by #95
