### ISSUE TITLE
A motion can be created with an empty title and empty text

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#783]
I have successfully sent the following payload:
```json
[
  {
    "action":"motion.create",
    "data":[
      {
        "meeting_id":4,
        "title":"   ",
        "text":"<p>&nbsp; &nbsp; &nbsp;</p>",
        "workflow_id":5,
        "attachment_ids":[
          
        ],
        "agenda_create":true,
        "agenda_type":"internal"
      }
    ]
  }
]
```

In the datastore its stored as:
```json
{
  "id":25,
  "text":"<p>&nbsp; &nbsp; &nbsp;</p>",
  "title":"   ",
  "number":"2",
  "created":1623824098,
  "state_id":23,
  "meeting_id":4,
  "sort_weight":10000,
  "meta_deleted":false,
  "number_value":2,
  "agenda_create":true,
  "last_modified":1623824098,
  "meta_position":690,
  "submitter_ids":[
    32
  ],
  "agenda_item_id":81,
  "attachment_ids":[
    
  ],
  "category_weight":10000,
  "personal_note_ids":[
    13
  ],
  "sequential_number":2,
  "list_of_speakers_id":68,
  "forwarding_tree_motion_ids":[
    
  ]
}
```

Maybe the backend can catch those invalid "attempts" to create a motion.

**Comment by FinnStutzenstein** [comment]
> empty title and empty text

**Comment by jsangmeister** [comment]
> > empty title and empty text
> 
> Technically, they are not empty... The title - yes, we could start stripping fields, but no chance with the text.

I agree, that kind of goes in the same direction as the recent username discussion - if people want to send invalid/empty stuff, they will always be able to. They could alse send something like "This is empty", which would be even more impossible to catch ;) So I vote for closing and ignoring this
