### ISSUE TITLE
Move motions to a TOP does not work as expected

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#784]
I have the following agenda-item for a motion in my agenda:
```json
{
  "id":93,
  "type":"common",
  "level":0,
  "closed":false,
  "weight":10000,
  "is_hidden":false,
  "meeting_id":1,
  "is_internal":false,
  "meta_deleted":false,
  "meta_position":717,
  "content_object_id":"motion/4"
}
```

Then I sent the following payload to move that motion as a child of a TOP:
```json
[
  {
    "action":"agenda_item.assign",
    "data":[
      {
        "ids":[
          93
        ],
        "parent_id":87,
        "meeting_id":1
      }
    ]
  }
]
```

But only the `parent_id` of the related agenda-item is changed:
```json
{
  "id":93,
  "type":"common",
  "level":0,
  "closed":false,
  "weight":10000,
  "is_hidden":false,
  "parent_id":87,
  "meeting_id":1,
  "is_internal":false,
  "meta_deleted":false,
  "meta_position":718,
  "content_object_id":"motion/4"
}
```

Can you please adjust the `weight` and the `level` of the agenda-item? I know, that this is not specified by the [wiki](https://github.com/OpenSlides/OpenSlides/wiki/agenda_item.assign) but maybe we should change this.
I you cannot do this (easily), please inform me.

**Comment by jsangmeister** [comment]
Please also add a test making sure that you can create no circles.
