### ISSUE TITLE
move the datavalidator into the backend and use it to validate the payload

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#800]
The [datavalidator](https://github.com/OpenSlides/OpenSlides/tree/openslides4-dev/docs/datavalidator) has to be moved into the backend (probably as a subfolder in `openslides_backend`, but I'm not sure here) and should be used in `meeting.import` to validate the given data.

While doing that, the validator should be adjusted to use the `models.py` instead of the `models.yml`, so no unecessary overhead is created while loading the file. Some functions using this definition must be adjusted then, since the previous schema is just a dict, while the new are full classes with their own helper functions. This also means that many validator helper functions can be removed, like `is_template_field` and most other functions regarding template/structured fields. Please go through the code and check for any other places which can be replaced.

The thrown `CheckException` should be handled explicitly by the action.

At the same time, the github action in the main repo (https://github.com/OpenSlides/OpenSlides/blob/d1d69954f5f20bfd332cec646995235382d985bf/.github/workflows/models.yml#L29 ff) has to be adjusted since the directory of the validator changed. Since the backend is included as a submodule, it should suffice to just change the path to point into the correct folder.

**Comment by jsangmeister** [comment]
Proposal: We could also move the data validator to its own, seperate repository. This way, we could include it in the backend as well as the main repo as a submodule, so we can use it there in the GH actions and here in our code.

**Comment by FinnStutzenstein** [comment]
Is it worth for a single file since if it is in the backend, the main repo can access it through the submodule

**Comment by jsangmeister** [comment]
You're right, forgot that it would already be included if it is mvoed to the backend. Thats fine then

**Comment by jsangmeister** [comment]
Updated description.

**Comment by FinnStutzenstein** [comment]
> The thrown CheckException can be subclassed from ActionException, so the exception handling does not have to be touched.

This is not good if you want to recycle the datavalidator in the main repo. It should live in it's own space and do not import anything from other backend code (theoretically).

**Comment by jsangmeister** [comment]
> This is not good if you want to recycle the datavalidator in the main repo. It should live in it's own space and do not import anything from other backend code (theoretically).

Ok, I agree, edited the description.

I think implementing additional features should be put in it's own issue, I will move the one from the main repo to here, so we can gather all missing features there.
