### ISSUE TITLE
Prevent entitled percent base for analog polls

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#807]
see https://github.com/OpenSlides/OpenSlides/pull/6134 for OS3 changes

**Comment by reiterl** [comment]
It is not clear, what should be done in OS4.
poll create action does not have entitled percent base.

**Comment by reiterl** [comment]
Prevent the setting of **entitled_group_ids** in poll.create action, if type is analog.  For update, this is not needed, as the check is already in place.

**Comment by jsangmeister** [comment]
No, you misunderstood: The percent base of a poll is saved in the field `onehundred_percent_base`. This field is defined [here](https://github.com/OpenSlides/OpenSlides/blob/77f6516438c93e790fd2915a32d416bb3a0f88a5/docs/models.yml#L1760) and can, among others, take `"entitled"` as a value. This is not valid for analog polls and therefore has to be prevented.
