### ISSUE TITLE
Should removing a user from a committee remove it also from 'child'-meetings?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#808]
I have a committee with the user_ids `[1, 2, 3]` and a meeting, in which these user_ids are participants.
I have noticed, that when I remove one of the user_ids from the committee's user, the meeting still has the three user_ids as participants.
Should every participant of a meeting in the committee of the meeting?
I don't know what we've discussed, but I ask, because the wiki describes the following:

> from [meeting.create](https://github.com/OpenSlides/OpenSlides/wiki/meeting.create)
> If `user_ids` are given, it must be checked, that it is a subset of `committee/user_ids`

**Comment by jsangmeister** [comment]
No, being a participant in a meeting is independent of belonging to the meeting's committee, at least in our current model. The check in `meeting.import` is necessary so you are not able to assign random users to your imported meeting, but rather only users which are part of the committee for which you import it. A user with OML `can_manage_users` could still add more users to the meeting afterwards which do not belong to the committee.

**Comment by GabrielInTheWorld** [comment]
Okay
