### ISSUE TITLE
Modify weight calculation for agenda items

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#809]
New meaning of the weight: only relative sorting inside of one parent.

If a new agenda item is created, the weight should be the maximum of all existing children + 1 (or 1, if none exist). Existing children are agenda items with the same parent id.

For agenda_item.sort: All agenda items with the same parent on the same level should have a simple increment order (1, 2, 3, ...)

**Comment by reiterl** [comment]
Should the `MotionSort` and the `MotionCategorySort` also be modified? Is this change only for `AgendaItems`?

**Comment by jsangmeister** [comment]
> Should the `MotionSort` and the `MotionCategorySort` also be modified?

Yes, the mixin can just be adjusted
