### ISSUE TITLE
Create tests for poll actions with no content object

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#816]
Check that the permission `poll.can_manage` is checked correctly

**Comment by reiterl** [comment]
It is not allowed to use another content object then assignment or motion.
```
Poll...
content_object_id = fields.GenericRelationField(
        to={Collection("motion"): "poll_ids", Collection("assignment"): "poll_ids"},
        equal_fields="meeting_id",
    )
...
```

**Comment by FinnStutzenstein** [comment]
But it is allowed to not give any content object ("standalone poll").

**Comment by jsangmeister** [comment]
> But it is allowed to not give any content object ("standalone poll").

Correct, I will update the title, I think I mixed it up when I opened this issue.

**Comment by FinnStutzenstein** [comment]
I guess Emanuel sometimes talk about polls for agenda_items; We can add this relation, if this he will definitly needs this ;)

**Comment by reiterl** [comment]
Yes, we can add the relation, if needed. I looked at the poll tests and there a lot of tests without content_object. 
Can you be more specific which tests are missing? Action? What kind of tests?

**Comment by jsangmeister** [comment]
It seems you are correct, we probably missed it when creating this issue (?). I will close this for now, if we notice in the future that specific tests are missing, we can open a new issue.
