### ISSUE TITLE
Can only set forwarding for unique commitees

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#817]
- set forwarding for one committee (works)
- select all committees, including the previous, set forwarding

results in:

`Error: data.forward_to_committee_ids must contain unique items`

```
{"success": false, "message": "data.forward_to_committee_ids must contain unique items", "action_error_index": 0, "action_data_error_index": 0}
```

This error is obviously intended. However, the backend should be able to skip a committee if the forwarding was set already.

**Comment by jsangmeister** [comment]
Can you provide the sent payload? The error sounds like it comes from the schema checker which would mean that the client sends duplicate in the payload field `forward_to_committee_ids`, which would make this a client error.

**Comment by tsiegleauq** [comment]
```json
[
  {
    "action": "committee.update",
    "data": [
      { "id": 1, "forward_to_committee_ids": [3] },
      { "id": 2, "forward_to_committee_ids": [3, 3] },
      { "id": 4, "forward_to_committee_ids": [3, 3] },
      { "id": 5, "forward_to_committee_ids": [3, 3] }
    ]
  }
]
```

while `2` can already forward to `3`.
As mentioned before:
> the backend should be able to skip a committee if the forwarding was set already.

**Comment by jsangmeister** [comment]
Yes, I agree, _if the forwarding was set already_ (meaning previously, in another request for example), the backend should skip it. But your payload is invalid: You provide the 3 two times, which is invalid. So the backend report an error before anything is written to the datastore and this is correct. You have to strip the duplicates from the payload, then this request should work.

**Comment by tsiegleauq** [comment]
hm thats weird

**Comment by tsiegleauq** [comment]
closed for https://github.com/OpenSlides/openslides-client/issues/345
