### ISSUE TITLE
Implement forwarding tree

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#818]
When `motion.create_forwarded` is called, `all_origin_ids` and `all_derived_motion_ids` must be (re-)calculated for the newly created motion as well as the forwarding motion.

Implementation note: The newly created motion always has `all_derived_motion_ids == []` and `all_origin_ids` must be set to `all_origin_ids` of its parent plus the parent id. Then, the newly created id must be added to `all_derived_motion_ids` of all motions in the new `all_origin_ids`.

Deleting motions should analogously update the fields correctly.

Also, in the first test a check is missing that `derived_motion_ids` is set correctly.

**Comment by FinnStutzenstein** [comment]
>  as well as the forwarding motion.

And every motion in the tree.

**Comment by jsangmeister** [comment]
> > as well as the forwarding motion.
> 
> And every motion in the tree.

Actually, only all (grand-)parents, right? Siblings do not appear in the tree, at least not according to the linked description.

**Comment by jsangmeister** [comment]
Field split in two in https://github.com/OpenSlides/OpenSlides/pull/6145 - logic should be similar, except that only all parents need to be updated on a new forward.

**Comment by reiterl** [comment]
How should the delete logic work?
Let motion 1 -> 2 ->3 and motion 2 is deleted. What should happen with the two fields?

**Comment by jsangmeister** [comment]
Good question. Maybe @emanuelschuetze has an opinion here

**Comment by jsangmeister** [comment]
The logic for creation is added here: https://github.com/OpenSlides/OpenSlides/wiki/motion.create_forwarded#forwarding-tree-fields. Please double check, but I think it is already implemented correctly. I discussed the delete case with @emanuelschuetze and for display purposes it is best to just leave the deleted motion ids in the trees, so it can still be correctly displayed in the client. So I think there should be nothing to do.
