### ISSUE TITLE
Fix mypy with fastjsonschema

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#82]
Currently, you have to `# type: ignore` all imports of `fastjsonschema` or else mypy fails with the following message:

    error: Cannot find implementation or library stub for module named 'fastjsonschema'
    note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

@FinnStutzenstein this is not the case in the datastore, what are we doing different? Not of high importance, but I find a quite annoying (and also wrong) to ignore all these imports.

**Comment by FinnStutzenstein** [comment]
My guess: https://github.com/OpenSlides/openslides-datastore-service/blob/master/scripts/setup.cfg#L16
