### ISSUE TITLE
Remove `majority_method` from all poll related methods

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#833]
The field no longer exists

**Comment by reiterl** [comment]
I have done a generate models and fixed the issues. It could be, that it fixes this too.

**Comment by reiterl** [comment]
See https://github.com/OpenSlides/openslides-backend/pull/840

**Comment by jsangmeister** [comment]
There are still 3 mentions in `test_import.py` (and I'm wondering why they don't make the tests fail...). Can you go ahead and fix that?

**Comment by reiterl** [comment]
I looked at the meeting/test_import.py code and looked for it, but found no appearances.

**Comment by jsangmeister** [comment]
Yes, sorry, I had to fix in in order to get the tests in https://github.com/OpenSlides/openslides-backend/pull/841 to work and forgot to mention it here. This should be done then
