### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#836]
Every time I try to delete a user, I get the following error-message:
```
Uncaught (in promise): Fehler: Update of speaker/15: You try to set following required fields to an empty value: ['user_id']
```

**Comment by reiterl** [comment]
Hmm, I can reproduce the error, if the user is a speaker.
I think a cascading deletion is missing. Oh, user/speaker_$_ids is a template field. We don't have cascade deletion for
these kind of fields. Hmm, no idea how to continue here. Joshua?

**Comment by jsangmeister** [comment]
Yes, I will take a look at it.
