### ISSUE TITLE
Change JSON format for import and export

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#846]
At the moment we use a format with arrays like this:
```json
{
  "meeting": [
    {
      "id": 1,
      "foo":"bar"
    },
    {
      "id": 2
    }
  ],
  "motion":[
    
  ]
}
```

Is this correct?

Can we please switch to a object-only format?

```
{
  "meeting": {
    "1": {
      "id": 1,  # We can discuss if this line is really necessary?
      "foo":"bar"
    },
    "2": {
      "id": 2
    }
  },
  "motion": {}
}
```

This has many advantages later when parsing and searching in large data. If we omit the id we have also no redundancy there.
@ostcar: Some more advantages?

**Comment by FinnStutzenstein** [comment]
Note: Also affects the Datastore's https://github.com/OpenSlides/openslides-datastore-service/blob/master/cli/create_initial_data.py
