### ISSUE TITLE
User gender: only accept diverse, female, male, null

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#847]
It was required (with low priority) that the client filters for a users gender. Currently, the server accepts any string to enter for the gender field. Practically this can be done by importing a `.csv`. To successfully filter, it is required that the backend only accepts `diverse`, `female`, `male` and `undefined`/`null` as a users gender

Related:
https://github.com/OpenSlides/openslides-client/pull/380

**Comment by FinnStutzenstein** [comment]
Was this also the case in OS3?

**Comment by tsiegleauq** [comment]
> Was this also the case in OS3?

OS3 also accepted any string as gender, but the requirement has already been there that we needed to filter for gender, which we of course could not offer in this time.

**Comment by FinnStutzenstein** [comment]
I just want to hint, that we had a broad discussion about that back than. For me this is OK, but maybe someone is not happy with this; gender is a hot topic... So I'm not against it, but want to raise awareness about the topic ;)

**Comment by tsiegleauq** [comment]
Indeed. That is why I marked this as "needs discussion", someone who might have a better idea than what we can currently offer can happily engage, even after this issue was resolved.
Originally, I was against adding a gender field at all, yet it seems to be a hard requirement for certain parties.
The client already offers the four named values since OpenSlides 3.2 or 3.1 over the `user-edit` which has not caused any controversy so far.
The (sole) problem remains csv import (validation from the server) and thus filtering.

**Comment by FinnStutzenstein** [comment]
So what filder options do users want? male, felame, diverse, none -> One can define matches for male and female (e.g. `["m", "male"]`, case ignored, for male; similar for female). Then filtering would match these patters, or catch null and all other strings are captured with diverse.

**Comment by tsiegleauq** [comment]
That is barely a solution. By simply miscounting the commata in your csv, the users gender might become their username or structure level which should be prevented. So the server has to ensure that entries make actual sense.

If we **really** wanted to play safe we might offer a custom configurable orga setting or meeting setting where the administration can add all entries they want; but even then the server has to ensure that create and update request match any entry of the list.

**Comment by jsangmeister** [comment]
> That is barely a solution. By simply miscounting the commata in your csv, the users gender might become their username or structure level which should be prevented. So the server has to ensure that entries make actual sense.

Well, the question is who is miscounting here. On the server side, we must of course ensure that we import the data correctly. On the export side, same thing. So the only time any "miscounting" happens is when the user imports manually created or from some other source exported data. Even then we can still ensure that the correct amount of fields is given (or even validate it by defining column headers which have to be used.

I would argue that this niche case is not our problem - the user has to provide valid data if he wants to import it. I don't think this is a gender-related problem. For your point - filtering the data - I'm all for @FinnStutzenstein proposal: Filter for fixed strings, which the user can use if he wants, but still provide the possibility to enter custom strings if one wants to. Maybe this can be solved in the client with a drop-down which enables a text input if "custom" is selected.

**Comment by tsiegleauq** [comment]
you are not supposed to trust that the client is sending you the correct data (this applies absolutely anywhere). Neither is the user supposed to be trusted to be able to ensure that their csv files are correct if the server itself confirms the correctness of data - which is does. This, also, is fundamental. The server has to provide checks here.

**Comment by jsangmeister** [comment]
> The server has to provide checks here.

Yes, of the general structure, where I mentioned methods of doing that which have nothing to do with the gender field. If you define the field as "can contain anything", you can also make sure that you allow that while also checking all other data.

**Comment by FinnStutzenstein** [comment]
@tsiegleauq A new opinion: https://github.com/OpenSlides/OpenSlides/issues/6180

**Comment by tsiegleauq** [comment]
free text is hard, since for sorting and filtering we would require a to just display options for. I do not consider creating a set of a potentially unlimited amount of users an option. Thus we might offer a configurable gender list in openslides/settings/users

**Comment by jsangmeister** [comment]
> free text is hard, since for sorting and filtering we would require some premade list just display the options for. I do not consider creating a set of a potentially unlimited amount of users an option to collect all entered genders. Thus we might offer a configurable gender list in openslides/settings/users

Configurable gender list is of course an option, but I think it's overkill. How about these options:
- female
- male
- divers
- custom (which then enables a free text field)

For filtering you can provide the same options, where custom would be a catch-all filter which shows all users which did enter anything else then female/male/divers.

**Comment by LaluSys** [comment]
From a gender inclusive position, a mix with the now given options and free Entry would be really good. The current options do not represent all People.

**Comment by jsangmeister** [comment]
> From a gender inclusive position, a mix with the now given options and free Entry would be really good. The current options do not represent all People.

Just out of curiosity, isn't "divers" supposed to be the catch-all category for everyone not falling into the other genders? If not, what would be the correct term for such a catch-all category (meaning, everyone who does not define themselves as male or female)?

**Comment by tsiegleauq** [comment]
> > free text is hard, since for sorting and filtering we would require some premade list just display the options for. I do not consider creating a set of a potentially unlimited amount of users an option to collect all entered genders. Thus we might offer a configurable gender list in openslides/settings/users
> 
> Configurable gender list is of course an option, but I think it's overkill. How about these options:
> 
> * female
> * male
> * divers
> * custom (which then enables a free text field)
> 
> For filtering you can provide the same options, where custom would be a catch-all filter which shows all users which did enter anything else then female/male/divers.

That would partially be a solution, the problem that a malformed CSV import can add literally anything would still persist, which could be prevented by providing a (configurable) list. The very same principle is then very plausible for the structure level field, which also usually makes 5 to 15 different entries and could desire filtering.

**Comment by LaluSys** [comment]
> > From a gender inclusive position, a mix with the now given options and free Entry would be really good. The current options do not represent all People.
> 
> Just out of curiosity, isn't "divers" supposed to be the catch-all category for everyone not falling into the other genders? If not, what would be the correct term for such a catch-all category (meaning, everyone who does not define themselves as male or female)?

Divers is a term that comes out of a legislative perspective and is not an preffered option from a community perspective. 
There are people who use this, i dont want to deny this, but the overall feedback that people say its just another category from goverments without talking with the people who are affected by this.

**Comment by jsangmeister** [comment]
> That would partially be a solution, the problem that a malformed CSV import can add literally anything would still persist, which could be prevented by providing a (configurable) list. The very same principle is then very plausible for the structure level field, which also usually makes 5 to 15 different entries and could desire filtering.

Yes, sure, but the point is that literally anything CAN be added, isn't it? The same argument goes for other free text fields as well, like `comment` or `username` (although I'm not sure if the former is included in user imports). The CSV can be checked anyway that it is correct by asserting the correct number of fields is given and verifying all values that are checkable. I don't really see the problem there. Maybe we should talk about it tomorrow.

**Comment by jsangmeister** [comment]
> > > From a gender inclusive position, a mix with the now given options and free Entry would be really good. The current options do not represent all People.
> > 
> > 
> > Just out of curiosity, isn't "divers" supposed to be the catch-all category for everyone not falling into the other genders? If not, what would be the correct term for such a catch-all category (meaning, everyone who does not define themselves as male or female)?
> 
> Divers is a term that comes out of a legislative perspective and is not an preffered option from a community perspective.
> There are people who use this, i dont want to deny this, but the overall feedback that people say its just another category from goverments without talking with the people who are affected by this.

Thanks for the input!

**Comment by LaluSys** [comment]
And i would not underestimate the potential of the integration of preffered pronouns. When users can add their pronouns in their profile, unintentional missgendering could be drastically reduced which would lower barriers for TIN* (Trans, Inter and non- binary people) to participate in democratic processes. This is another Issue from a technical perspective, but same topic regarding the content, I cannot support on a technical level but i can give more context :)
https://github.com/OpenSlides/OpenSlides/issues/6179

**Comment by jsangmeister** [comment]
Solution from the initial comment will be implemented as a fix for now. We will see how this can be extended later

**Comment by FinnStutzenstein** [comment]
Which comment exactly?

**Comment by tsiegleauq** [comment]
> Which comment exactly?

Misleading. This was regarding to the opening post.

https://github.com/OpenSlides/openslides-backend/issues/847#issue-945136140

**Comment by jsangmeister** [comment]
> > Which comment exactly?
> 
> Misleading. This was regarding to the opening post.
> 
> [#847 (comment)](https://github.com/OpenSlides/openslides-backend/issues/847#issue-945136140)

Yes, sorry. But I think in githubs nomenclature even the openning post is a comment, that's why I formulated it that way ;)
