### ISSUE TITLE
datavalidator: recalculate/check calculated fields

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#849]
List of fields which I noticed so far:
- `mediafile/is_public`
- `mediafile/inherited_access_group_ids`
- `motion/number_value`
- `motion/sequential_number`

**Comment by FinnStutzenstein** [comment]
They should be valid when importing, so only a check must be done (so to check equality, you have to recalculate, but not overwrite).

**Comment by FinnStutzenstein** [comment]
> `motion/number_value`
> `motion/sequential_number`

They are not "calculated"; you cannot verify them I guess since they represent a state only "calculateable" when having the whole history of the meeting.

**Comment by jsangmeister** [comment]
> > `motion/number_value`
> > `motion/sequential_number`
> 
> They are not "calculated"; you cannot verify them I guess since they represent a state only "calculateable" when having the whole history of the meeting.

Ah, ok. But at least the sequential_number must be ensured to be unique, right?

**Comment by FinnStutzenstein** [comment]
> Ah, ok. But at least the sequential_number must be ensured to be unique, right?

Technically not, but for the user this would be nice ;)
