### ISSUE TITLE
Group create and update should calculate permissions according to permission.yml 

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-backend#851]
As discussed today with @emanuelschuetze and @tsiegleauq : 

On group create and group update the client sends so permission strings for the group: The backend should append all permissions according to our https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/permission.yml.

**Comment by jsangmeister** [comment]
Mmh ok. In the backend, we implemented a function to check if a permission is a child of another permission. What's the reason not to do the same in the client?

**Comment by jsangmeister** [comment]
Discussed this in the daily and we came to the conclusion that it is better (especially regarding https://github.com/OpenSlides/openslides-client/issues/394) to generate the permission tree in the client and check it there. Only thing the backend should do is clean up the permission list to explicitly NOT include redundant permissions, which I will open a new issue for
