### ISSUE TITLE
`committee.create`: Add manager_ids

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#855]
see https://github.com/OpenSlides/OpenSlides/wiki/committee.create

**Comment by jsangmeister** [comment]
see https://github.com/OpenSlides/OpenSlides/wiki/committee.create

**Comment by reiterl** [comment]
I don't know, how this should work. If I use UserUpdate, a user mit cml perms must be part of the committee.

**Comment by reiterl** [comment]
What data should I give the UserUpdate action?
