### ISSUE TITLE
motion.create: Set motion submitter weight according to order

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#872]
From the [wiki](https://github.com/OpenSlides/OpenSlides/wiki/motion.create):
- `submitter_ids`: [...] For each id in the list a motion_submitter model is created. **The weight must be set to the order of the given list.**

This is missing from the implementation. Also a test is needed that the weights are set correctly.

**Comment by reiterl** [comment]
Can I add the weight property to the motion_submitter.create action? This would make this issue easy.

**Comment by jsangmeister** [comment]
> Can I add the weight property to the motion_submitter.create action? This would make this issue easy.

From [motion_submitter.create](https://github.com/OpenSlides/OpenSlides/wiki/motion_submitter.create):
> The weight must be set to max+1 from all submitters of the motion.

It seems like this isn't implemented either. If you add this (with tests), then theoretically this issue should be resolved as well, since the submitters are created one by one in the order provided by the payload. Please add a test for that also.

**Comment by reiterl** [comment]
No, it does not work that way. When creating the second submitter, the datastore does not include the first submitter. So a wrong weight is calculated.

**Comment by reiterl** [comment]
Do we allow to have an action with multi payload? That could be a problem, if in motion_submitter.create the same payload is given twice.

**Comment by jsangmeister** [comment]
> No, it does not work that way. When creating the second submitter, the datastore does not include the first submitter. So a wrong weight is calculated.

Did you use `fetch_model` instead of `get`?

**Comment by reiterl** [comment]
I did use `datastore.max`.
