### ISSUE TITLE
Add permission check to `check_mediafile_id` presenter

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#878]
If the [see property](https://github.com/OpenSlides/OpenSlides/wiki/mediafile-restrictions#see-property) of the mediafile is not fulfilled for the request user, the presenter should fail.

**Comment by reiterl** [comment]
In the "see property", what does "user can see the meeting and [...]" mean (point 2)?

**Comment by reiterl** [comment]
Talk with the others about the question above. See 
https://github.com/OpenSlides/OpenSlides/wiki/meeting-restrictions
for meeting can see.

**Comment by reiterl** [comment]
How do I check for mediafile/used_as_logo_$_in_meeting_id  and mediafile/used_as_font_$_in_meeting_id ?

**Comment by FinnStutzenstein** [comment]
E.g. for `mediafile/used_as_logo_$_in_meeting_id`: Get this template field from the datastore (not any structured field, so no replacements for `$`). Ifit is `None` or `[]` it is empty.

If one of the two fields is not empty (and the user can see the meeting), the permission check results in "allowed".

**Comment by reiterl** [comment]
Ah, okay, I did it that way. So I have understood it right.
