### ISSUE TITLE
orgaadmin can edit superadmin

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#883]
Create an orgaadmin. 
Edit existing superadmin and change permission to "can_manage_organization".
Login as superadmin: You have no superadmin permissions and cannot change it back!

**Comment by jsangmeister** [comment]
What should the intended behaviour be here? I would suggest that one can only downgrade another user in his OML if he would have permission to upgrade him again - meaning he needs at least the same OML. One can then still lock himself out, but that's another issue that we need to tackle.

**Comment by emanuelschuetze** [comment]
> I would suggest that one can only downgrade another user in his OML if he would have permission to 
> upgrade him again - meaning he needs at least the same OML.

Ok for me.

**Comment by jsangmeister** [comment]
Clarification: One should only be able to edit another user if he at least matches the user's OML. If no one has objections I will add this to the wiki.

**Comment by jsangmeister** [comment]
Added to wiki: https://github.com/OpenSlides/OpenSlides/wiki/user.update#permissions
