### ISSUE TITLE
Implement archiving of meetings

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#899]
see https://github.com/OpenSlides/OpenSlides/wiki/MeetingArchived also for backend details

23.09.2021 Ralf
Most things are made with [PR933](https://github.com/OpenSlides/openslides-backend/pull/933) and [PR949](https://github.com/OpenSlides/openslides-backend/pull/949).
Still missing: No action can change data in an archived meeting, exept meeting.unarchive => close it in all single actions. A delete from external relation still may change archived meetings (users in groups etc.)

Done:
1. Action organization.update with limit_of_meetings: Done
2. Action meeting.create: Check limit_of_meetings,  set is_active_in_organization_id to the current organization's id per default: Done
3. Action meeting.archive: Done
4. Action meeting.unarchiving: Done
5. Importing, cloning und creating from template meetings have to respect the limit_of_meetings: done
6. Don't count archived meetings on rights scope => ready in branch, in PR949
7. Presenter get_forwarding_meetings don't return archived meetings: done with organization_tags

**Comment by GabrielInTheWorld** [comment]
Please add the information about an archived meeting to the presenter "get_forwarding_meetings", so we have this information already for the presenter.

**Comment by jsangmeister** [comment]
> Please add the information about an archived meeting to the presenter "get_forwarding_meetings", so we have this information already for the presenter.

Should the meeting get a flag that it is archieved or should it not even be listed? I think the latter makes more sense since it is not possible to edit archieved meetings (which would happen if you forward a motion there).

**Comment by GabrielInTheWorld** [comment]
> > Please add the information about an archived meeting to the presenter "get_forwarding_meetings", so we have this information already for the presenter.
> 
> Should the meeting get a flag that it is archieved or should it not even be listed? I think the latter makes more sense since it is not possible to edit archieved meetings (which would happen if you forward a motion there).

You can also implement it so, that the archieved meetings are not returned by the presenter. With such a flag I want to prevent to forward a motion to an archieved meeting.

**Comment by FinnStutzenstein** [comment]
Note: `limit_of_meetings` must also be checked when importing and cloning meetings.

**Comment by r-peschke** [comment]
Most things are made with [PR933](https://github.com/OpenSlides/openslides-backend/pull/933), but not all
