### ISSUE TITLE
Reduce the number of get(-many) requests

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#904]
Before making the "big solution" with a cache layer one can improve single, seemingly heavy actions. This is an excerpt of tests from @reiterl and @jsangmeister:

```
=================================================
Anzahl get Aufrufe, Anzahl get_many Aufrufe, Test
=================================================
147 2 meeting.test_delete.MeetingDeleteActionTest.test_delete_full_meeting
16 0 meeting.test_create.MeetingCreateActionTest.test_create_simple
12 1 
motion_category.test_sort.MotionCategorySortActionTest.test_sort_complex_correct
12 1 agenda_item.test_sort.AgendaItemSortActionTest.test_sort_complex_correct
10 1 
list_of_speakers.test_delete_all_speakers.ListOfSpeakersDeleteAllSpeakersActionTester.test_delete_all_correct
9 2 meeting.test_import.MeetingImport.test_double_import
9 1 meeting.test_import.MeetingImport.test_replace_ids_and_write_to_datastore
7 1 projector.test_project.ProjectorProject.test_project
6 6 user.test_update.UserUpdateActionTest.test_update_change_group
6 1 user.test_update.UserUpdateActionTest.test_update_template_fields
=================================================
```
- Especially sorting (`motion_category.test_sort.MotionCategorySortActionTest.test_sort_complex_correct`, ...) and `list_of_speakers.test_delete_all_speakers.ListOfSpeakersDeleteAllSpeakersActionTester.test_delete_all_correct` seems to make lineary many get requests; This needs to be checked and improved
- `projector.test_project.ProjectorProject.test_project`: Seems to be heavy, since it is a very common operation during an assembly. It should be fast.

Generally: You should redo the measurements with a real setup. Maybe, when testing with the client, other pain points arise.

**Comment by jsangmeister** [comment]
Just ran a few tests and you seem to be correct:
- `agenda_item.sort` with 15 items: Depending on the tree structure, about 80-90 GET calls
- `list_of_speakers.delete_all_speakers` with about 25 speakers: 104/16
- `projector.project`: about 17 GETs on my instance, but I don't exactly know on what it depends
We could start by locally optimizing a first action and see by how much we can improve this and then, if we want to, still implement the generic cache layer solution.

**Comment by jsangmeister** [comment]
(Check out backend in the main repo to https://github.com/jsangmeister/openslides-backend/tree/request-counts if someone wants to also play around, the amount is logged near the end of the request lifecycle)

**Comment by FinnStutzenstein** [comment]
This sounds like one should definitely improve these actions!

**Comment by reiterl** [comment]
I look into the `agenda_item.sort` and `list_of_speakers.delete_all_speakers`. The get calls do not come from the action, but from the relation handle code under it. As we don't want to touch this code, we can close this issue.

**Comment by jsangmeister** [comment]
Ok, thank you for the investigation. This is exactly what I thought beforehand - that the relation handler generates a lot of requests. We now have two possibilities:
- improve the relation handler: Currently, every relation for every touched model is fetched independently. One could go ahead and fetch them all in one call (in the `RelationHandler`, before even calling the `SingleRelationHandler`) and then reuse the results in the `SingleRelationHandler`.
- implement the cache layer like initially planned

The latter would be more work, partly because the work has to be done on lower level, partly because one has to go through all the actions afterwards and find out all models and fields that are used and prefetch them (for the first approach, this could be done automatically), but the potential improvement is better. The question is if the heavier workload is worth it, especially since almost all calls seem to stem from the relation handler. Any thoughts? I'm leaning towards the first possibility, but I'm not convinced.

**Comment by jsangmeister** [comment]
Another idea as I mentioned in https://github.com/OpenSlides/openslides-backend/issues/417: We could change the relation handling to only use list updates. This way, the old data does not have to be fetched and we also would greatly reduce the number of queries

**Comment by FinnStutzenstein** [comment]
I would like a solution that does not really touch the relating handling (i.e., making it more complicated). My dream solution would be a two-part system: One cache/enhancment part and the relation-handling part; both separated, so the complexity stays down. With the list updates, it may be good to overhaul the relating handling to always use the list updates. IDK if it already does that since most of the code is older than the list update feature.

**Comment by jsangmeister** [comment]
I agree. I would suggest to implement list updates for the relation handling in a first step (since it is not used there; as you said, the relation handling is older than the list update feature).

**Comment by jsangmeister** [comment]
moved to 4.1 since only performance improvements (or low 4.0 would also be okay). @tsiegleauq what infos yould you like here?
