### ISSUE TITLE
Enhance the presenter "get_forwarding_meetings"

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#906]
Please enhance the presenter "get_forwarding_meetings" so, the returned committees contain the additional information `default_meeting_id`.
This refers to OpenSlides/openslides-client#327. I cannot implement a status icon without the `default_meeting_id`.

**Comment by FinnStutzenstein** [comment]
Please document the changes here: https://github.com/OpenSlides/OpenSlides/wiki/get_forwarding_meetings

**Comment by GabrielInTheWorld** [comment]
> Please document the changes here: https://github.com/OpenSlides/OpenSlides/wiki/get_forwarding_meetings

Done.
