### ISSUE TITLE
Add migrations to CI

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#907]
Followup from #901 

The migration folder has separate tests, coverage and style checks. This should be included into the CI as an extra step. The dev setup may not be used since the volume mount `- ../../openslides-datastore-service/:/datastore-service` in the docker-compose.yml. Instead the datastore reader and writer must be installed via pip.[1] It must be ensured that in both variants (mounted/installed with pip) the cleanup scripts and tests work.

[1] Or: the datastore is cloned in the exact needed position by hand with the commit hash from the requirements.txt on the root level.

**Comment by jsangmeister** [comment]
moved to 4.1 since only relevant for dev purposes
