### ISSUE TITLE
Implement TODO in model checker

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#909]
See https://github.com/OpenSlides/openslides-backend/blob/7daa76ed20d6dca61c7c292e03b6bfa3b123bc5c/openslides_backend/models/checker.py#L211

**Comment by jsangmeister** [comment]
How should the blobs be handled? Asserted that they are empty?

**Comment by FinnStutzenstein** [comment]
I don't know how this is called, but when importing, the json fill will have `blob` fields, that the checker will not be happy about. Since the import works (see tests) this seems to be resolved. But this needs to be verified.

**Comment by jsangmeister** [comment]
This should be done by now
