### ISSUE TITLE
Add permissions to meeting.clone

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-backend#924]
The permissions in meeting.clone are missing.
Add the permissions to the action and add some tests.
See: https://github.com/OpenSlides/OpenSlides/wiki/meeting.clone for details.

**Comment by jsangmeister** [comment]
Is OML `can_manage_users` really enough to clone a meeting? I was under the assumption that this OML was solely for managing the users and everything else (like creating/cloning a meeting) needed `can_manage_organization`. This would also be analogous to https://github.com/OpenSlides/OpenSlides/wiki/meeting.create, where CML `can_manage` (or, indirectly, OML `can_manage_organization` is needed).

**Comment by jsangmeister** [comment]
Use CML  `can_manage`, as changed in https://github.com/OpenSlides/OpenSlides/wiki/meeting.clone
