### ISSUE TITLE
motion_workflow.import

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#925]
Implement the new action [motion_workflow.import](https://github.com/OpenSlides/OpenSlides/wiki/motion_workflow.import)

**Comment by jsangmeister** [comment]
> If two or more states are found, that match a string, then the first reference will be used.

Seems more like the user did something wrong at this point, since it's almost always unintended behaviour to just "randomly" select one of many. Can't we just require the names to be unique?

**Comment by GabrielInTheWorld** [comment]
> > If two or more states are found, that match a string, then the first reference will be used.
> 
> Seems more like the user did something wrong at this point, since it's almost always unintended behaviour to just "randomly" select one of many. Can't we just require the names to be unique?

For me it is okay to require that every motion-state has to be unique in a motion-workflow.

**Comment by jsangmeister** [comment]
> For me it is okay to require that every motion-state has to be unique in a motion-workflow.

Ok, than I would suggest to implement that. Please change the wiki accordingly and @reiterl check that in your implementation.
