### ISSUE TITLE
meeting.clone Check relations between derived, forwared and received motions from other meetings

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-backend#931]
# Work in progress
In import (external, at the moment only from OS3) there are no relations from motion of other meetings.
On cloning inside of OS4 there are.
Check relation!

## Checks/Tests
1. Precondition: clone is always in one organization, import is this time always import from other organization/no organization/OS3
1. All relations with equal fields `meeting_id` plus more should be cloned and import, with all relations mapped to instances in new meeting
1. Relations without equal field meeting should be cloned, but must be empty on importing
1. Relation to collection user are treated like all: user copy on import, same user in clone
1. Some special fields we have to look for motion/all_origin_ids, motion/all_derived_motion_ids
1. WIP: motion_workflow and the 3 default meetings 

### Motion

    lead_motion_id = fields.RelationField( to={Collection("motion"): "amendment_ids"}, equal_fields="meeting_id")
    amendment_ids = fields.RelationListField( to={Collection("motion"): "lead_motion_id"}, equal_fields="meeting_id")
    sort_parent_id = fields.RelationField(to={Collection("motion"): "sort_child_ids"}, equal_fields="meeting_id")
    sort_child_ids = fields.RelationListField( to={Collection("motion"): "sort_parent_id"}, equal_fields="meeting_id" )
    origin_id = fields.RelationField(to={Collection("motion"): "derived_motion_ids"})
    derived_motion_ids = fields.RelationListField( to={Collection("motion"): "origin_id"})
    all_origin_ids = fields.NumberArrayField()
    all_derived_motion_ids = fields.NumberArrayField()
    state_id = fields.RelationField(to={Collection("motion_state"): "motion_ids"}, required=True, equal_fields="meeting_id")
    recommendation_id = fields.RelationField(to={Collection("motion_state"): "motion_recommendation_ids"}, equal_fields="meeting_id")
    recommendation_extension_reference_ids = fields.GenericRelationListField(to={Collection("motion"): "referenced_in_motion_recommendation_extension_ids"}, equal_fields="meeting_id")
    referenced_in_motion_recommendation_extension_ids = fields.RelationListField(to={Collection("motion"):  "recommendation_extension_reference_ids"}, equal_fields="meeting_id")
    category_id = fields.RelationField(to={Collection("motion_category"): "motion_ids"}, equal_fields="meeting_id")
    block_id = fields.RelationField(to={Collection("motion_block"): "motion_ids"}, equal_fields="meeting_id")
    submitter_ids = fields.RelationListField( to={Collection("motion_submitter"): "motion_id"}, equal_fields="meeting_id")
    supporter_ids = fields.RelationListField( to={Collection("user"): "supported_motion_$_ids"})
    poll_ids = fields.RelationListField(to={Collection("poll"): "content_object_id"},  equal_fields="meeting_id",)
    option_ids = fields.RelationListField(to={Collection("option"): "content_object_id"}, equal_fields="meeting_id",)
    change_recommendation_ids = fields.RelationListField( to={Collection("motion_change_recommendation"): "motion_id"}, equal_fields="meeting_id")
    statute_paragraph_id = fields.RelationField(to={Collection("motion_statute_paragraph"): "motion_ids"},     equal_fields="meeting_id")
    comment_ids = fields.RelationListField(to={Collection("motion_comment"): "motion_id"},  equal_fields="meeting_id" )
    agenda_item_id = fields.RelationField(to={Collection("agenda_item"): "content_object_id"}, equal_fields="meeting_id")
    list_of_speakers_id = fields.RelationField(to={Collection("list_of_speakers"): "content_object_id"}, equal_fields="meeting_id")
    tag_ids = fields.RelationListField(to={Collection("tag"): "tagged_ids"}, equal_fields="meeting_id")
    attachment_ids = fields.RelationListField(to={Collection("mediafile"): "attachment_ids"}, equal_fields="meeting_id")
    projection_ids = fields.RelationListField(to={Collection("projection"): "content_object_id"}, equal_fields="meeting_id")
    personal_note_ids = fields.RelationListField(to={Collection("personal_note"): "content_object_id"},  equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_ids"}, required=True)

### MotionSubmitter
    user_id = fields.RelationField(to={Collection("user"): "submitted_motion_$_ids"})
    motion_id = fields.RelationField(to={Collection("motion"): "submitter_ids"}, equal_fields="meeting_id" )
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_submitter_ids"}, required=True))

### MotionComment
    motion_id = fields.RelationField(to={Collection("motion"): "comment_ids"},  equal_fields="meeting_id")
    section_id = fields.RelationField(to={Collection("motion_comment_section"): "comment_ids"},  equal_fields="meeting_id" )
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_comment_ids"}, required=True)

### MotionCommentSection
    comment_ids = fields.RelationListField(to={Collection("motion_comment"): "section_id"}, equal_fields="meeting_id")
    read_group_ids = fields.RelationListField(to={Collection("group"): "read_comment_section_ids"}, equal_fields="meeting_id")
    write_group_ids = fields.RelationListField(to={Collection("group"): "write_comment_section_ids"}, equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_comment_section_ids"}, required=True)

### MotionCategory
    parent_id = fields.RelationField(to={Collection("motion_category"): "child_ids"}, equal_fields="meeting_id")
    child_ids = fields.RelationListField(to={Collection("motion_category"): "parent_id"}, equal_fields="meeting_id")
    motion_ids = fields.RelationListField(to={Collection("motion"): "category_id"}, equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_category_ids"}, required=True)

### MotionBlock
    motion_ids = fields.RelationListField(to={Collection("motion"): "block_id"}, equal_fields="meeting_id")
    agenda_item_id = fields.RelationField(to={Collection("agenda_item"): "content_object_id"}, equal_fields="meeting_id")
    list_of_speakers_id = fields.RelationField(to={Collection("list_of_speakers"): "content_object_id"}, required=True,  equal_fields="meeting_id")
    projection_ids = fields.RelationListField(to={Collection("projection"): "content_object_id"}, equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_block_ids"}, required=True)

### MotionChangeRecommendation
    motion_id = fields.RelationField(to={Collection("motion"): "change_recommendation_ids"}, equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_change_recommendation_ids"}, required=True)

### MotionState
    next_state_ids = fields.RelationListField(to={Collection("motion_state"): "previous_state_ids"}, equal_fields=["meeting_id", workflow_id"],)
    previous_state_ids = fields.RelationListField( to={Collection("motion_state"): "next_state_ids"}, equal_fields=["meeting_id", "workflow_id"])
    motion_ids = fields.RelationListField(to={Collection("motion"): "state_id"}, equal_fields="meeting_id")
    motion_recommendation_ids = fields.RelationListField(to={Collection("motion"): "recommendation_id"}, equal_fields="meeting_id")
    workflow_id = fields.RelationField(to={Collection("motion_workflow"): "state_ids"}, required=True, equal_fields="meeting_id")
    first_state_of_workflow_id = fields.RelationField(to={Collection("motion_workflow"): "first_state_id"},    equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_state_ids"}, required=True)

### MotionWorkflow
    state_ids = fields.RelationListField(to={Collection("motion_state"): "workflow_id"}, equal_fields="meeting_id")
    first_state_id = fields.RelationField(to={Collection("motion_state"): "first_state_of_workflow_id"},  equal_fields="meeting_id")
    default_workflow_meeting_id = fields.RelationField(to={Collection("meeting"): "motions_default_workflow_id"} )
    default_amendment_workflow_meeting_id = fields.RelationField(to={Collection("meeting"): 
motions_default_amendment_workflow_id"})
    default_statute_amendment_workflow_meeting_id = fields.RelationField(to={Collection("meeting"): "motions_default_statute_amendment_workflow_id"})
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_workflow_ids"}, required=True)

### MotionStatuteParagraph
    motion_ids = fields.RelationListField(to={Collection("motion"): "statute_paragraph_id"}, equal_fields="meeting_id")
    meeting_id = fields.RelationField(to={Collection("meeting"): "motion_statute_paragraph_ids"}, required=True)

**Comment by tsiegleauq** [comment]
See #811 for more information

**Comment by jsangmeister** [comment]
And please update https://github.com/OpenSlides/OpenSlides/wiki/meeting.clone when done, as requested in #811

**Comment by r-peschke** [comment]
> And please update https://github.com/OpenSlides/OpenSlides/wiki/meeting.clone when done, as requested in #811

#811 is about clone and export. I think you are referring to the special cases of motion handling or what do you mean?

**Comment by jsangmeister** [comment]
> I think you are referring to the special cases of motion handling or what do you mean?

Yes
