### ISSUE TITLE
`meeting.clone` throws (until now) two errors

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#937]
If no mediafiles are uploaded to a meeting, which should be cloned, the following error came up:
```
Error: meeting/3/font_$_id: Replacements for the template field must be a list meeting/3/logo_$_id: Replacements for the template field must be a list
```

If mediafiles in that meeting uploaded, then this error came up:
```
Error: Mediaservice Error: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'
```

Commit hash of the used backend: c8799863ffae31859eec0e27a414ccd3471655af

**Comment by reiterl** [comment]
The logo_$_id error is solved. You can clone simple meetings without mediafile.
The first mediafile problem is about system for get and internal for post bug. Here I have a hotfix, but it needs some more work.
There is a second media get problem. He tries to get it as user/0(?) and throws an error.

**Comment by GabrielInTheWorld** [comment]
> There is a second media get problem. He tries to get it as user/0(?) and throws an error.

This sounds like you try to get a mediafile without being authenticated (as anonymous). Maybe you forget to include the `refreshId` (as cookie) or you have to include it in your requests.

**Comment by reiterl** [comment]
How do I include the `refreshId` to the request?

**Comment by GabrielInTheWorld** [comment]
> How do I include the `refreshId` to the request?

As I wrote earlier, the `refreshId` is given as a cookie. I don't know the code in detail, but you have to just pass the incoming `refreshId` from the backend to the media-service.
We can talk together and look through the code.

**Comment by reiterl** [comment]
Joshua, we want to dl media files in export_meeting (needed for clone meeting). So we need the request header for this.
Actions don't know the header of the request. (`openslides_backend/http/views.py`). How can we handle this?

**Comment by GabrielInTheWorld** [comment]
@jsangmeister As I found out with @reiterl, the backend does not send any cookies to the media-service, doesn't it? For the `meeting.clone`-action we need to duplicate mediafiles as well as other models. So, how can the backend download mediafiles to re-upload them for a duplicated meeting? Please discuss this with @reiterl.

**Comment by jsangmeister** [comment]
> the backend does not send any cookies to the media-service

I don't think so, because it wasn't needed for uploading.

I would favor another apporach: Downloading and then uploading again seems like unnecessary work. Can we instead create a new route for the media service which duplicates a file? This could then also be called without authentification so we would'nt have to adjust much of the backend code.

**Comment by jsangmeister** [comment]
We'll do as suggested above, as per meeting with @reiterl and @r-peschke
