### ISSUE TITLE
When `meeting.create` is called, create the "simple workflow" as well as the "complex workflow"

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#939]
Every meeting has a pre-configured "simple workflow". Please create a pre-configured "complex workflow" for every meeting (every time "meeting.create" is called).
See the current state in OS3:
https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/server/openslides/motions/signals.py#L53
See the complex workflow in a live-demo:
https://nightly.demo.openslides.org/motions/workflow/2

**Comment by r-peschke** [comment]
What's about the default:

-        default_workflow_meeting_id,
-        default_amendment_workflow_meeting_id
-        default_statute_amendment_workflow_meeting_id

Which workflow will become default for the meeting?
