### ISSUE TITLE
Implement the `user.forget_password` and `user.forget_password_confirm` actions

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#948]
Since OpenSlides/openslides-auth-service#102, the auth-library can create and verify authorization tokens. The backend can create those for users, who forgot their passwords and create new ones.
See [user.forget_password](https://github.com/OpenSlides/OpenSlides/wiki/user.forget_password) and [user.forget_password_confirm](https://github.com/OpenSlides/OpenSlides/wiki/user.forget_password_confirm) for further information.

**Comment by jsangmeister** [comment]
Sending the text from the client is a major security flaw, any attacker can send any text he wants (ads, phishing mails,...) to any registered OS user. We probably need to implement some kind of backend translations (either fully generic with a framework or a simple hotfix for especially this email) for this to work

**Comment by GabrielInTheWorld** [comment]
> We probably need to implement some kind of backend translations (either fully generic with a framework or a simple hotfix for especially this email) for this to work

This is one way. Another way is, that the client sends a token, that confirms its integrity (like a `jsonwebtoken` by a signature). This could be done by a secret, that only the client (and the backend) knows, or by an asynchronous key-pair. An environment variable could be injected into the client, for example.

**Comment by jsangmeister** [comment]
> Another way is, that the client sends a token, that confirms its integrity (like a `jsonwebtoken` by a signature). This could be done by a secret, that only the client (and the backend) knows, or by an asynchronous key-pair. An environment variable could be injected into the client, for example.

Is the token reusable? Then the problem persists. I can just send my request, copy the token, and re-send it with the same token, but different data. If there is a secure way to do this, you'll have to elaborate a little bit more (especially why scenarios like the above are not possible), I'm not so experienced in cryptography :D

**Comment by GabrielInTheWorld** [comment]
> > Another way is, that the client sends a token, that confirms its integrity (like a `jsonwebtoken` by a signature). This could be done by a secret, that only the client (and the backend) knows, or by an asynchronous key-pair. An environment variable could be injected into the client, for example.
> 
> Is the token reusable? Then the problem persists. I can just send my request, copy the token, and re-send it with the same token, but different data. If there is a secure way to do this, you'll have to elaborate a little bit more (especially why scenarios like the above are not possible), I'm not so experienced in cryptography :D

No, just copying such a token is not enough. The cryptographical signature of a `jsonwebtoken` is calculated by hashing the payload using a given secret. Then, the signature is only valid with the exact same payload.

**Comment by jsangmeister** [comment]
Potentially still unsafe. Will need to discuss this further to find a viable solution

**Comment by GabrielInTheWorld** [comment]
Email-text:
```
You receive this email, because you have requested a new password for your OpenSlides-account.

Please open the following link and choose a new password:
<link>

For completeness your username: <username>

--
<instance>
```

**Comment by jsangmeister** [comment]
Currently, I don't think we have the option to access the instance url from the backend. I would suggest to just implement it without the last line for now @reiterl until @gsiv (or someone else) builds a way to access it.

**Comment by gsiv** [comment]
> > What is the "instance"?
> 
> An "instance" can we maybe find in a config-file. Maybe @gsiv can tell, where we find the instance- or domain-name?

Unlike in OpenSlides 3, the instance domain is generally not intended to be available in OpenSlides 4 as far as I know; however, the proxy recently gained awareness of it.  As of https://github.com/OpenSlides/OpenSlides/commit/bad1e131ee8ccfcf9bd2d74ece935214930d2563 there is an `EXTERNAL_ADDRESS` variable.

I expect that it would require additional changes to the manage service to make use of the proxy's new feature and to expose the variable to the backend.  You might need to open an issue for the manage service.

Of course, the variable is not always going to be set, so any functionality must be able to handle that.

**Comment by GabrielInTheWorld** [comment]
It sounds like the effort to get the domain is to high for the benefit we gain (especially because every user will probably be only in one OS4-instance). Therefore, we ignore this. I will change the wiki accordingly.

**Comment by reiterl** [comment]
A question about `forget_password_confirm`: How do I access a header from an action? I think actions have no idea of the request and the header. I think the client should give the token in the payload.

**Comment by GabrielInTheWorld** [comment]
Okay, I changed the wiki accordingly.

**Comment by reiterl** [comment]
I found that `create_authorization_token` creates something like `"bearer <token>"`. The bearer and the space are problematic. I cut them in `forget_password` and readd them in `forget_password_confirm`. For now, but add a comment
for this.
