### ISSUE TITLE
`meeting.clone`: Add a suffix to the clone's title

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#958]
Add a suffix to the clone's title to distinguish between a clone and its original.
This should be a variable like a number starting at `(1)` (for example). So, this variable is increased after each cloning.

**Comment by reiterl** [comment]
Adding a suffix to the meeting title is simple. Like "- Kopie" or "(1)".
But we don't have a way to determine the copies count. 
Copies could be a kind of tree. By the way.

**Comment by GabrielInTheWorld** [comment]
> But we don't have a way to determine the copies count. 

It is sufficient, if you count all meetings in one committee - regardless if a meeting is a clone from one another.
It's just a matter of a clone can be distinguished from its original one.

**Comment by reiterl** [comment]
What is the title of the meeting? welcome_title or name? name has a max length.

**Comment by GabrielInTheWorld** [comment]
`name` -> Yeah, but this is ~256, isn't it?

**Comment by reiterl** [comment]
The name of the meeting has a  max length of 100.
I will add the info to the `name`, if it fit.

**Comment by jsangmeister** [comment]
Can't we do the same as for `username`, i.e. check if "name (1)" exists, then "name (2)" etc. until we find a name which is not in use?

**Comment by reiterl** [comment]
I use the count of all meetings of a committee plus 1 as copy identifier behind the name string. (as Gabriel said).
I cut it, if it is too long.

**Comment by jsangmeister** [comment]
I would argue it's more intuitive for the user if he copies his meeting "xy" and gets "xy (1)" (or maybe even "xy (2)"?) instead of "xy (42)" just because there are 41 meetings before, but if that suits your needs it's fine for me.

**Comment by GabrielInTheWorld** [comment]
> Can't we do the same as for `username`, i.e. check if "name (1)" exists, then "name (2)" etc. until we find a name which is not in use?

If you can implement such a logic, I would prefer this. As @jsangmeister already said, this is more intuitive than only counting all meetings.

**Comment by reiterl** [comment]
I will look at the username logic and try to implement it.
