### ISSUE TITLE
Enhance the `meeting.clone`-action to update the clone

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#962]
When a meeting is cloned, the clone takes all models and metadata of the original meeting.
Enhance the interface, so an update to the clone can be done by the backend.
For example:
```js
{
  title?: string;
  description?: string;
  start_time?: number;
  end_time?: number;
  location?: string;
  organization_tag_ids?: Id[];
}
```

**Comment by reiterl** [comment]
Meeting doesn't have the field `title`, do you mean `welcome_title`?
