### ISSUE TITLE
More migration tests

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#974]
see https://github.com/OpenSlides/openslides-backend/pull/956#pullrequestreview-776245444

Two parts of this suggestion:
- asserting that a migration only writes fields which are present in the models file and fills them with valid values (we test this already in the "normal" backend tests for the filling of the datastore, so this should be easy to implement
- asserting that a migration does not destroy any relations, i.e. always touches both ends. This would be more work, but technically the logic is already present in the JSON checker for importing/cloning and could be extracted.

**Comment by jsangmeister** [comment]
I would like to raise the priority on this to assert that no broken migrations are implemented after we deploy a first version of OS4. @r-peschke @reiterl do have anything to add/change here? Or should this be implemented as suggested?

**Comment by reiterl** [comment]
The migrations tests don't know anything about the openslides_backend. If I try to import it, I get an error. I need the models of the backend to validate the fields. Why do I fuddle the stuff into the migration docker code?

**Comment by reiterl** [comment]
This won't work. Checking an old migration against the current models will not work.
We must check the old migration against the models **of this migration**.  But we don't have a mechanism to ask the models about past models.

**Comment by jsangmeister** [comment]
You are correct, I did not realize this. I guess the part about checking the content of fields is off the table then ( we don't want to hold deprecated code somewhere just for test purposes). But the (IMO) more important part was anyway the relation checking. I think you can just remove the whole migration container and move the code into the backend (there already is a `migrations` folder where this could belong). The separate container was created because the idea was that the migration would be executed apart from the main backend container, but this idea was thrown out of the window anyway and the main backend already accesses these files, so I don't think it should do any harm (except if @r-peschke has any objections). If you need help moving these files, just ask.

**Comment by r-peschke** [comment]
Good idea:-)
