### ISSUE TITLE
Translations for password reset emails

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#994]
After https://github.com/OpenSlides/openslides-backend/issues/948 is implemented, we will need server-side translations for these mails. Either hardcoded with if-else (as long as it's just for this case) or (better) we need to use a python translation framework like babel.

**Comment by jsangmeister** [comment]
The better approach is to use a full framework. It can probably be implemented analogous to the website: https://github.com/OpenSlides/openslides.com

**Comment by reiterl** [comment]
It cannot be implemented analogous, because openslides.com uses flask and the backend is barebone.
I don't know how to continue here.

**Comment by reiterl** [comment]
We want the client to send the language with Accept Language in the header.
We will pass the lang to the action, which get a translation function.
Then translate the forget_password action.

**Comment by reiterl** [comment]
The commands pybabel compile/update/extract need a place to work. Should I include make commands for them?

**Comment by jsangmeister** [comment]
> The commands pybabel compile/update/extract need a place to work. Should I include make commands for them?

yes

**Comment by jsangmeister** [comment]
done in https://github.com/OpenSlides/openslides-backend/pulls?q=is%3Apr+is%3Aclosed
