### ISSUE TITLE
Committee-user rework

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#995]
Since the relation `committee/user_ids` has no real use case and adding users first to the committee (by an user manager) and then to the meeting (by a committee manager) is too long-winded for the users, we want to restructure the usage. The changes:

A user does not have to be part of the committee to be added to the meeting. Meeting admins should be able to add users to their meeting, but should not have full access to all users. Therefore, we will offer 2 indirect ways for a meeting admin to add an user to the meeting:
  - via a search field: The admin can enter the users' username or email in separate fields. All matching users are then displayed with their first and last name and their email. The admin then selects the users he wants to add to the meeting or create new ones or ...
    - This is also (more or less) done automatically on `user.create`: if an email address is sent which already exists, a confirmation dialog appears to add the existing user to the meeting instead of creating a new one. **No, there is no such logic in user.create. If we need this, we should create a new action for it.**
  - via CSV import: The admin can also, analogously to the OS3 CSV import, upload a list of all users to import. All users which match in first name, last name and email are added to the meeting, the rest is created.
  - depending the usage of this sort, we'll send a scope (Organization, Committee or Meeting) and in case of the latter 2 an id to check permissions.

The relation `committee/user_ids` becomes a passive indicator if the user has access to the committee: As soon as a user is added to a meeting or gains CommitteeManagementRights, the user is also added or removed from the committee.

Backend implementation details:
- [ ] Presenter to return all matching users for one or more emails/usernames-tuples
- [x] This presenter is also called first before `user.create` is executed to implement the above mentioned matching. [Deprecated]
- [ ] Same logic for the user import
- [x] Everything regarding  `committee/user_ids` has to be restructured: The relation can no longer be filled manually, but is instead filled automatically. The relation has to be removed from all payloads.
- [x] discuss if and how the user scope should be adjusted. If we let it as-is, no user will be in the meeting scope, since they all belong to a committee together with the meeting. This means that meeting admins cannot change the user data, even if the user is only in their meeting. This can be wanted or not and needs to be discussed => 
**Read about changed user scope conditions:**
    https://github.com/OpenSlides/OpenSlides/wiki/Users
    https://github.com/OpenSlides/OpenSlides/wiki/user.update

**Comment by r-peschke** [comment]
To discuss  if and how the user scope should be adjusted, I added some **bold marked** proposals to the following wiki-pages:

1.  https://github.com/OpenSlides/OpenSlides/wiki/Users
2. https://github.com/OpenSlides/OpenSlides/wiki/user.update
